// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/balance/balance.proto

/*
Package fomo_balances is a generated protocol buffer package.

It is generated from these files:
	proto/balance/balance.proto

It has these top-level messages:
	GetUserBalanceRequest
	GetUserBalancesRequest
	AccountBalances
	Balance
	UserBalanceData
	BalanceResponse
	BalancesResponse
*/
package fomo_balances

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Requests
type GetUserBalanceRequest struct {
	UserID   string `protobuf:"bytes,1,opt,name=userID" json:"userID"`
	KeyID    string `protobuf:"bytes,2,opt,name=keyID" json:"keyID"`
	Currency string `protobuf:"bytes,3,opt,name=currency" json:"currency"`
}

func (m *GetUserBalanceRequest) Reset()                    { *m = GetUserBalanceRequest{} }
func (m *GetUserBalanceRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserBalanceRequest) ProtoMessage()               {}
func (*GetUserBalanceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetUserBalanceRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetUserBalanceRequest) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *GetUserBalanceRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type GetUserBalancesRequest struct {
	UserID string `protobuf:"bytes,1,opt,name=userID" json:"userID"`
	KeyID  string `protobuf:"bytes,2,opt,name=keyID" json:"keyID"`
	Symbol string `protobuf:"bytes,3,opt,name=symbol" json:"symbol"`
}

func (m *GetUserBalancesRequest) Reset()                    { *m = GetUserBalancesRequest{} }
func (m *GetUserBalancesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserBalancesRequest) ProtoMessage()               {}
func (*GetUserBalancesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetUserBalancesRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetUserBalancesRequest) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *GetUserBalancesRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type AccountBalances struct {
	Balances []*Balance `protobuf:"bytes,4,rep,name=balances" json:"balances"`
}

func (m *AccountBalances) Reset()                    { *m = AccountBalances{} }
func (m *AccountBalances) String() string            { return proto.CompactTextString(m) }
func (*AccountBalances) ProtoMessage()               {}
func (*AccountBalances) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AccountBalances) GetBalances() []*Balance {
	if m != nil {
		return m.Balances
	}
	return nil
}

// Responses
type Balance struct {
	ID                string  `protobuf:"bytes,1,opt,name=ID" json:"ID"`
	UserID            string  `protobuf:"bytes,2,opt,name=userID" json:"userID"`
	KeyID             string  `protobuf:"bytes,3,opt,name=keyID" json:"keyID"`
	ExchangeName      string  `protobuf:"bytes,4,opt,name=exchangeName" json:"exchangeName"`
	CurrencyName      string  `protobuf:"bytes,5,opt,name=currencyName" json:"currencyName"`
	Available         float64 `protobuf:"fixed64,6,opt,name=available" json:"available"`
	Locked            float64 `protobuf:"fixed64,7,opt,name=locked" json:"locked"`
	ExchangeTotal     float64 `protobuf:"fixed64,8,opt,name=exchangeTotal" json:"exchangeTotal"`
	ExchangeAvailable float64 `protobuf:"fixed64,9,opt,name=exchangeAvailable" json:"exchangeAvailable"`
	ExchangeLocked    float64 `protobuf:"fixed64,10,opt,name=exchangeLocked" json:"exchangeLocked"`
}

func (m *Balance) Reset()                    { *m = Balance{} }
func (m *Balance) String() string            { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()               {}
func (*Balance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Balance) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Balance) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Balance) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *Balance) GetExchangeName() string {
	if m != nil {
		return m.ExchangeName
	}
	return ""
}

func (m *Balance) GetCurrencyName() string {
	if m != nil {
		return m.CurrencyName
	}
	return ""
}

func (m *Balance) GetAvailable() float64 {
	if m != nil {
		return m.Available
	}
	return 0
}

func (m *Balance) GetLocked() float64 {
	if m != nil {
		return m.Locked
	}
	return 0
}

func (m *Balance) GetExchangeTotal() float64 {
	if m != nil {
		return m.ExchangeTotal
	}
	return 0
}

func (m *Balance) GetExchangeAvailable() float64 {
	if m != nil {
		return m.ExchangeAvailable
	}
	return 0
}

func (m *Balance) GetExchangeLocked() float64 {
	if m != nil {
		return m.ExchangeLocked
	}
	return 0
}

type UserBalanceData struct {
	Balance *Balance `protobuf:"bytes,1,opt,name=balance" json:"balance"`
}

func (m *UserBalanceData) Reset()                    { *m = UserBalanceData{} }
func (m *UserBalanceData) String() string            { return proto.CompactTextString(m) }
func (*UserBalanceData) ProtoMessage()               {}
func (*UserBalanceData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UserBalanceData) GetBalance() *Balance {
	if m != nil {
		return m.Balance
	}
	return nil
}

type BalanceResponse struct {
	Status  string           `protobuf:"bytes,1,opt,name=status" json:"status"`
	Message string           `protobuf:"bytes,2,opt,name=message" json:"message"`
	Data    *UserBalanceData `protobuf:"bytes,3,opt,name=data" json:"data"`
}

func (m *BalanceResponse) Reset()                    { *m = BalanceResponse{} }
func (m *BalanceResponse) String() string            { return proto.CompactTextString(m) }
func (*BalanceResponse) ProtoMessage()               {}
func (*BalanceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *BalanceResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *BalanceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BalanceResponse) GetData() *UserBalanceData {
	if m != nil {
		return m.Data
	}
	return nil
}

type BalancesResponse struct {
	Status  string           `protobuf:"bytes,1,opt,name=status" json:"status"`
	Message string           `protobuf:"bytes,2,opt,name=message" json:"message"`
	Data    *AccountBalances `protobuf:"bytes,3,opt,name=data" json:"data"`
}

func (m *BalancesResponse) Reset()                    { *m = BalancesResponse{} }
func (m *BalancesResponse) String() string            { return proto.CompactTextString(m) }
func (*BalancesResponse) ProtoMessage()               {}
func (*BalancesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *BalancesResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *BalancesResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BalancesResponse) GetData() *AccountBalances {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*GetUserBalanceRequest)(nil), "fomo.balances.GetUserBalanceRequest")
	proto.RegisterType((*GetUserBalancesRequest)(nil), "fomo.balances.GetUserBalancesRequest")
	proto.RegisterType((*AccountBalances)(nil), "fomo.balances.AccountBalances")
	proto.RegisterType((*Balance)(nil), "fomo.balances.Balance")
	proto.RegisterType((*UserBalanceData)(nil), "fomo.balances.UserBalanceData")
	proto.RegisterType((*BalanceResponse)(nil), "fomo.balances.BalanceResponse")
	proto.RegisterType((*BalancesResponse)(nil), "fomo.balances.BalancesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for BalanceService service

type BalanceServiceClient interface {
	GetUserBalance(ctx context.Context, in *GetUserBalanceRequest, opts ...client.CallOption) (*BalanceResponse, error)
	GetUserBalances(ctx context.Context, in *GetUserBalancesRequest, opts ...client.CallOption) (*BalancesResponse, error)
}

type balanceServiceClient struct {
	c           client.Client
	serviceName string
}

func NewBalanceServiceClient(serviceName string, c client.Client) BalanceServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "fomo.balances"
	}
	return &balanceServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *balanceServiceClient) GetUserBalance(ctx context.Context, in *GetUserBalanceRequest, opts ...client.CallOption) (*BalanceResponse, error) {
	req := c.c.NewRequest(c.serviceName, "BalanceService.GetUserBalance", in)
	out := new(BalanceResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceServiceClient) GetUserBalances(ctx context.Context, in *GetUserBalancesRequest, opts ...client.CallOption) (*BalancesResponse, error) {
	req := c.c.NewRequest(c.serviceName, "BalanceService.GetUserBalances", in)
	out := new(BalancesResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BalanceService service

type BalanceServiceHandler interface {
	GetUserBalance(context.Context, *GetUserBalanceRequest, *BalanceResponse) error
	GetUserBalances(context.Context, *GetUserBalancesRequest, *BalancesResponse) error
}

func RegisterBalanceServiceHandler(s server.Server, hdlr BalanceServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&BalanceService{hdlr}, opts...))
}

type BalanceService struct {
	BalanceServiceHandler
}

func (h *BalanceService) GetUserBalance(ctx context.Context, in *GetUserBalanceRequest, out *BalanceResponse) error {
	return h.BalanceServiceHandler.GetUserBalance(ctx, in, out)
}

func (h *BalanceService) GetUserBalances(ctx context.Context, in *GetUserBalancesRequest, out *BalancesResponse) error {
	return h.BalanceServiceHandler.GetUserBalances(ctx, in, out)
}

func init() { proto.RegisterFile("proto/balance/balance.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xdf, 0x8b, 0xd3, 0x40,
	0x10, 0x36, 0x69, 0xaf, 0x3f, 0xe6, 0xbc, 0x56, 0x07, 0x2d, 0x4b, 0x95, 0xb3, 0x2c, 0xa7, 0xf4,
	0x41, 0xaa, 0xc4, 0xbf, 0xe0, 0xb4, 0x22, 0x07, 0xe2, 0x43, 0x54, 0x10, 0x04, 0x61, 0xb3, 0x37,
	0x9e, 0xc7, 0x25, 0xd9, 0x33, 0xbb, 0x39, 0xaf, 0x7f, 0x9e, 0x4f, 0xfe, 0x5b, 0x72, 0x9b, 0xdd,
	0xb4, 0x89, 0xad, 0x0f, 0x82, 0x4f, 0xe1, 0xfb, 0xe6, 0x63, 0xbe, 0x99, 0x9d, 0x99, 0xc0, 0x83,
	0xcb, 0x42, 0x19, 0xf5, 0x2c, 0x11, 0xa9, 0xc8, 0x25, 0xf9, 0xef, 0xc2, 0xb2, 0x78, 0xf0, 0x55,
	0x65, 0x6a, 0xe1, 0x38, 0xcd, 0x05, 0xdc, 0x7f, 0x43, 0xe6, 0xa3, 0xa6, 0xe2, 0x65, 0x45, 0xc5,
	0xf4, 0xbd, 0x24, 0x6d, 0x70, 0x02, 0xbd, 0x52, 0x53, 0x71, 0xb2, 0x64, 0xc1, 0x2c, 0x98, 0x0f,
	0x63, 0x87, 0xf0, 0x1e, 0xec, 0x5d, 0xd0, 0xea, 0x64, 0xc9, 0x42, 0x4b, 0x57, 0x00, 0xa7, 0x30,
	0x90, 0x65, 0x51, 0x50, 0x2e, 0x57, 0xac, 0x63, 0x03, 0x35, 0xe6, 0x5f, 0x60, 0xd2, 0xb4, 0xd0,
	0xff, 0xe6, 0x31, 0x81, 0x9e, 0x5e, 0x65, 0x89, 0x4a, 0x9d, 0x83, 0x43, 0xfc, 0x35, 0x8c, 0x8f,
	0xa5, 0x54, 0x65, 0x6e, 0x7c, 0x7e, 0x8c, 0x60, 0xe0, 0x3b, 0x64, 0xdd, 0x59, 0x67, 0xbe, 0x1f,
	0x4d, 0x16, 0x8d, 0xbe, 0x17, 0xbe, 0xdb, 0x5a, 0xc7, 0x7f, 0x86, 0xd0, 0x77, 0x2c, 0x8e, 0x20,
	0xac, 0x8b, 0x0a, 0x2b, 0x6b, 0x57, 0x68, 0xb8, 0xbd, 0xd0, 0xce, 0x66, 0xa1, 0x1c, 0x6e, 0xd3,
	0xb5, 0xfc, 0x26, 0xf2, 0x33, 0x7a, 0x27, 0x32, 0x62, 0x5d, 0x1b, 0x6c, 0x70, 0x37, 0x1a, 0xff,
	0x40, 0x56, 0xb3, 0x57, 0x69, 0x36, 0x39, 0x7c, 0x08, 0x43, 0x71, 0x25, 0xce, 0x53, 0x91, 0xa4,
	0xc4, 0x7a, 0xb3, 0x60, 0x1e, 0xc4, 0x6b, 0xe2, 0xa6, 0xa6, 0x54, 0xc9, 0x0b, 0x3a, 0x65, 0x7d,
	0x1b, 0x72, 0x08, 0x8f, 0xe0, 0xc0, 0x3b, 0x7d, 0x50, 0x46, 0xa4, 0x6c, 0x60, 0xc3, 0x4d, 0x12,
	0x9f, 0xc2, 0x5d, 0x4f, 0x1c, 0xd7, 0x1e, 0x43, 0xab, 0xfc, 0x33, 0x80, 0x4f, 0x60, 0xe4, 0xc9,
	0xb7, 0x95, 0x27, 0x58, 0x69, 0x8b, 0xe5, 0xaf, 0x60, 0xbc, 0x31, 0xe7, 0xa5, 0x30, 0x02, 0x9f,
	0x43, 0xdf, 0x3d, 0xb1, 0x7d, 0xcf, 0xdd, 0x93, 0xf0, 0x32, 0xfe, 0x03, 0xc6, 0xf5, 0x2e, 0xea,
	0x4b, 0x95, 0x6b, 0xdb, 0xab, 0x36, 0xc2, 0x94, 0xda, 0x2f, 0x4a, 0x85, 0x90, 0x41, 0x3f, 0x23,
	0xad, 0xc5, 0x19, 0xb9, 0xc1, 0x78, 0x88, 0x11, 0x74, 0x4f, 0x85, 0x11, 0x76, 0x30, 0xfb, 0xd1,
	0x61, 0xcb, 0xb3, 0x55, 0x64, 0x6c, 0xb5, 0xfc, 0x1a, 0xee, 0xac, 0x37, 0xf4, 0x3f, 0x39, 0xb7,
	0x36, 0xb5, 0x72, 0x8e, 0x7e, 0x05, 0x30, 0x72, 0xd4, 0x7b, 0x2a, 0xae, 0xce, 0x25, 0xe1, 0x27,
	0x18, 0x35, 0xaf, 0x06, 0x8f, 0x5a, 0xa9, 0xb6, 0xde, 0xed, 0xf4, 0x70, 0xc7, 0xf3, 0xba, 0x86,
	0xf8, 0x2d, 0xfc, 0x0c, 0xe3, 0xd6, 0x3d, 0xe2, 0xe3, 0xbf, 0xa6, 0xf6, 0xf7, 0x3a, 0x7d, 0xb4,
	0x3d, 0xb7, 0x5e, 0x27, 0x4f, 0x7a, 0xf6, 0x2f, 0xf3, 0xe2, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xae, 0x7d, 0xde, 0x3d, 0x84, 0x04, 0x00, 0x00,
}
