// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/asciiu/gomo/plan-service/proto/order/order.proto

/*
Package order is a generated protocol buffer package.

It is generated from these files:
	github.com/asciiu/gomo/plan-service/proto/order/order.proto

It has these top-level messages:
	TriggerRequest
	UpdateOrderRequest
	NewOrderRequest
	GetUserOrderRequest
	GetUserOrdersRequest
	RemoveOrderRequest
	Order
	Trigger
	UserOrderData
	UserOrdersData
	OrderResponse
	OrderListResponse
	OrdersPage
*/
package order

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Requests
type TriggerRequest struct {
	TriggerID         string   `protobuf:"bytes,1,opt,name=triggerID" json:"triggerID,omitempty"`
	Name              string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Code              string   `protobuf:"bytes,3,opt,name=code" json:"code,omitempty"`
	TriggerTemplateID string   `protobuf:"bytes,4,opt,name=triggerTemplateID" json:"triggerTemplateID,omitempty"`
	Actions           []string `protobuf:"bytes,5,rep,name=actions" json:"actions,omitempty"`
}

func (m *TriggerRequest) Reset()                    { *m = TriggerRequest{} }
func (m *TriggerRequest) String() string            { return proto.CompactTextString(m) }
func (*TriggerRequest) ProtoMessage()               {}
func (*TriggerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TriggerRequest) GetTriggerID() string {
	if m != nil {
		return m.TriggerID
	}
	return ""
}

func (m *TriggerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TriggerRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *TriggerRequest) GetTriggerTemplateID() string {
	if m != nil {
		return m.TriggerTemplateID
	}
	return ""
}

func (m *TriggerRequest) GetActions() []string {
	if m != nil {
		return m.Actions
	}
	return nil
}

type UpdateOrderRequest struct {
	OrderID         string            `protobuf:"bytes,1,opt,name=orderID" json:"orderID,omitempty"`
	OrderType       string            `protobuf:"bytes,2,opt,name=orderType" json:"orderType,omitempty"`
	OrderTemplateID string            `protobuf:"bytes,3,opt,name=orderTemplateID" json:"orderTemplateID,omitempty"`
	KeyID           string            `protobuf:"bytes,4,opt,name=keyID" json:"keyID,omitempty"`
	ParentOrderID   string            `protobuf:"bytes,5,opt,name=parentOrderID" json:"parentOrderID,omitempty"`
	PlanID          string            `protobuf:"bytes,6,opt,name=planID" json:"planID,omitempty"`
	PlanDepth       string            `protobuf:"bytes,7,opt,name=planDepth" json:"planDepth,omitempty"`
	Exchange        string            `protobuf:"bytes,8,opt,name=exchange" json:"exchange,omitempty"`
	MarketName      string            `protobuf:"bytes,9,opt,name=marketName" json:"marketName,omitempty"`
	Side            string            `protobuf:"bytes,10,opt,name=side" json:"side,omitempty"`
	LimitPrice      float64           `protobuf:"fixed64,11,opt,name=limitPrice" json:"limitPrice,omitempty"`
	PercentBalance  float64           `protobuf:"fixed64,12,opt,name=percentBalance" json:"percentBalance,omitempty"`
	BaseBalance     float64           `protobuf:"fixed64,13,opt,name=baseBalance" json:"baseBalance,omitempty"`
	CurrencyBalance float64           `protobuf:"fixed64,14,opt,name=currencyBalance" json:"currencyBalance,omitempty"`
	Action          string            `protobuf:"bytes,15,opt,name=action" json:"action,omitempty"`
	Triggers        []*TriggerRequest `protobuf:"bytes,16,rep,name=triggers" json:"triggers,omitempty"`
}

func (m *UpdateOrderRequest) Reset()                    { *m = UpdateOrderRequest{} }
func (m *UpdateOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateOrderRequest) ProtoMessage()               {}
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpdateOrderRequest) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *UpdateOrderRequest) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func (m *UpdateOrderRequest) GetOrderTemplateID() string {
	if m != nil {
		return m.OrderTemplateID
	}
	return ""
}

func (m *UpdateOrderRequest) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *UpdateOrderRequest) GetParentOrderID() string {
	if m != nil {
		return m.ParentOrderID
	}
	return ""
}

func (m *UpdateOrderRequest) GetPlanID() string {
	if m != nil {
		return m.PlanID
	}
	return ""
}

func (m *UpdateOrderRequest) GetPlanDepth() string {
	if m != nil {
		return m.PlanDepth
	}
	return ""
}

func (m *UpdateOrderRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *UpdateOrderRequest) GetMarketName() string {
	if m != nil {
		return m.MarketName
	}
	return ""
}

func (m *UpdateOrderRequest) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *UpdateOrderRequest) GetLimitPrice() float64 {
	if m != nil {
		return m.LimitPrice
	}
	return 0
}

func (m *UpdateOrderRequest) GetPercentBalance() float64 {
	if m != nil {
		return m.PercentBalance
	}
	return 0
}

func (m *UpdateOrderRequest) GetBaseBalance() float64 {
	if m != nil {
		return m.BaseBalance
	}
	return 0
}

func (m *UpdateOrderRequest) GetCurrencyBalance() float64 {
	if m != nil {
		return m.CurrencyBalance
	}
	return 0
}

func (m *UpdateOrderRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *UpdateOrderRequest) GetTriggers() []*TriggerRequest {
	if m != nil {
		return m.Triggers
	}
	return nil
}

type NewOrderRequest struct {
	OrderID         string            `protobuf:"bytes,1,opt,name=orderID" json:"orderID,omitempty"`
	OrderType       string            `protobuf:"bytes,2,opt,name=orderType" json:"orderType,omitempty"`
	OrderTemplateID string            `protobuf:"bytes,3,opt,name=orderTemplateID" json:"orderTemplateID,omitempty"`
	KeyID           string            `protobuf:"bytes,4,opt,name=keyID" json:"keyID,omitempty"`
	ParentOrderID   string            `protobuf:"bytes,5,opt,name=parentOrderID" json:"parentOrderID,omitempty"`
	PlanID          string            `protobuf:"bytes,6,opt,name=planID" json:"planID,omitempty"`
	PlanDepth       string            `protobuf:"bytes,7,opt,name=planDepth" json:"planDepth,omitempty"`
	Exchange        string            `protobuf:"bytes,8,opt,name=exchange" json:"exchange,omitempty"`
	MarketName      string            `protobuf:"bytes,9,opt,name=marketName" json:"marketName,omitempty"`
	Side            string            `protobuf:"bytes,10,opt,name=side" json:"side,omitempty"`
	LimitPrice      float64           `protobuf:"fixed64,11,opt,name=limitPrice" json:"limitPrice,omitempty"`
	PercentBalance  float64           `protobuf:"fixed64,12,opt,name=percentBalance" json:"percentBalance,omitempty"`
	BaseBalance     float64           `protobuf:"fixed64,13,opt,name=baseBalance" json:"baseBalance,omitempty"`
	CurrencyBalance float64           `protobuf:"fixed64,14,opt,name=currencyBalance" json:"currencyBalance,omitempty"`
	Triggers        []*TriggerRequest `protobuf:"bytes,15,rep,name=triggers" json:"triggers,omitempty"`
}

func (m *NewOrderRequest) Reset()                    { *m = NewOrderRequest{} }
func (m *NewOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*NewOrderRequest) ProtoMessage()               {}
func (*NewOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *NewOrderRequest) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *NewOrderRequest) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func (m *NewOrderRequest) GetOrderTemplateID() string {
	if m != nil {
		return m.OrderTemplateID
	}
	return ""
}

func (m *NewOrderRequest) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *NewOrderRequest) GetParentOrderID() string {
	if m != nil {
		return m.ParentOrderID
	}
	return ""
}

func (m *NewOrderRequest) GetPlanID() string {
	if m != nil {
		return m.PlanID
	}
	return ""
}

func (m *NewOrderRequest) GetPlanDepth() string {
	if m != nil {
		return m.PlanDepth
	}
	return ""
}

func (m *NewOrderRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *NewOrderRequest) GetMarketName() string {
	if m != nil {
		return m.MarketName
	}
	return ""
}

func (m *NewOrderRequest) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *NewOrderRequest) GetLimitPrice() float64 {
	if m != nil {
		return m.LimitPrice
	}
	return 0
}

func (m *NewOrderRequest) GetPercentBalance() float64 {
	if m != nil {
		return m.PercentBalance
	}
	return 0
}

func (m *NewOrderRequest) GetBaseBalance() float64 {
	if m != nil {
		return m.BaseBalance
	}
	return 0
}

func (m *NewOrderRequest) GetCurrencyBalance() float64 {
	if m != nil {
		return m.CurrencyBalance
	}
	return 0
}

func (m *NewOrderRequest) GetTriggers() []*TriggerRequest {
	if m != nil {
		return m.Triggers
	}
	return nil
}

type GetUserOrderRequest struct {
	OrderID string `protobuf:"bytes,1,opt,name=orderID" json:"orderID,omitempty"`
	UserID  string `protobuf:"bytes,2,opt,name=userID" json:"userID,omitempty"`
}

func (m *GetUserOrderRequest) Reset()                    { *m = GetUserOrderRequest{} }
func (m *GetUserOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserOrderRequest) ProtoMessage()               {}
func (*GetUserOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetUserOrderRequest) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *GetUserOrderRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetUserOrdersRequest struct {
	UserID string `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
}

func (m *GetUserOrdersRequest) Reset()                    { *m = GetUserOrdersRequest{} }
func (m *GetUserOrdersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserOrdersRequest) ProtoMessage()               {}
func (*GetUserOrdersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetUserOrdersRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type RemoveOrderRequest struct {
	OrderID string `protobuf:"bytes,1,opt,name=orderID" json:"orderID,omitempty"`
	UserID  string `protobuf:"bytes,2,opt,name=userID" json:"userID,omitempty"`
}

func (m *RemoveOrderRequest) Reset()                    { *m = RemoveOrderRequest{} }
func (m *RemoveOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveOrderRequest) ProtoMessage()               {}
func (*RemoveOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RemoveOrderRequest) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *RemoveOrderRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type Order struct {
	PlanID             string     `protobuf:"bytes,1,opt,name=planID" json:"planID,omitempty"`
	PlanDepth          uint32     `protobuf:"varint,2,opt,name=planDepth" json:"planDepth,omitempty"`
	OrderID            string     `protobuf:"bytes,3,opt,name=orderID" json:"orderID,omitempty"`
	Side               string     `protobuf:"bytes,4,opt,name=side" json:"side,omitempty"`
	OrderTemplateID    string     `protobuf:"bytes,5,opt,name=orderTemplateID" json:"orderTemplateID,omitempty"`
	KeyID              string     `protobuf:"bytes,19,opt,name=keyID" json:"keyID,omitempty"`
	OrderType          string     `protobuf:"bytes,6,opt,name=orderType" json:"orderType,omitempty"`
	LimitPrice         float64    `protobuf:"fixed64,7,opt,name=limitPrice" json:"limitPrice,omitempty"`
	Status             string     `protobuf:"bytes,8,opt,name=status" json:"status,omitempty"`
	ParentOrderID      string     `protobuf:"bytes,9,opt,name=parentOrderID" json:"parentOrderID,omitempty"`
	Exchange           string     `protobuf:"bytes,10,opt,name=exchange" json:"exchange,omitempty"`
	ExchangeMarketName string     `protobuf:"bytes,11,opt,name=exchangeMarketName" json:"exchangeMarketName,omitempty"`
	MarketName         string     `protobuf:"bytes,12,opt,name=marketName" json:"marketName,omitempty"`
	BaseBalance        float64    `protobuf:"fixed64,13,opt,name=baseBalance" json:"baseBalance,omitempty"`
	CurrencyBalance    float64    `protobuf:"fixed64,14,opt,name=currencyBalance" json:"currencyBalance,omitempty"`
	PercentBalance     float64    `protobuf:"fixed64,15,opt,name=percentBalance" json:"percentBalance,omitempty"`
	CreatedOn          string     `protobuf:"bytes,16,opt,name=createdOn" json:"createdOn,omitempty"`
	UpdatedOn          string     `protobuf:"bytes,17,opt,name=updatedOn" json:"updatedOn,omitempty"`
	Triggers           []*Trigger `protobuf:"bytes,18,rep,name=triggers" json:"triggers,omitempty"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Order) GetPlanID() string {
	if m != nil {
		return m.PlanID
	}
	return ""
}

func (m *Order) GetPlanDepth() uint32 {
	if m != nil {
		return m.PlanDepth
	}
	return 0
}

func (m *Order) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *Order) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *Order) GetOrderTemplateID() string {
	if m != nil {
		return m.OrderTemplateID
	}
	return ""
}

func (m *Order) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *Order) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func (m *Order) GetLimitPrice() float64 {
	if m != nil {
		return m.LimitPrice
	}
	return 0
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Order) GetParentOrderID() string {
	if m != nil {
		return m.ParentOrderID
	}
	return ""
}

func (m *Order) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *Order) GetExchangeMarketName() string {
	if m != nil {
		return m.ExchangeMarketName
	}
	return ""
}

func (m *Order) GetMarketName() string {
	if m != nil {
		return m.MarketName
	}
	return ""
}

func (m *Order) GetBaseBalance() float64 {
	if m != nil {
		return m.BaseBalance
	}
	return 0
}

func (m *Order) GetCurrencyBalance() float64 {
	if m != nil {
		return m.CurrencyBalance
	}
	return 0
}

func (m *Order) GetPercentBalance() float64 {
	if m != nil {
		return m.PercentBalance
	}
	return 0
}

func (m *Order) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *Order) GetUpdatedOn() string {
	if m != nil {
		return m.UpdatedOn
	}
	return ""
}

func (m *Order) GetTriggers() []*Trigger {
	if m != nil {
		return m.Triggers
	}
	return nil
}

type Trigger struct {
	TriggerID         string   `protobuf:"bytes,1,opt,name=triggerID" json:"triggerID,omitempty"`
	OrderID           string   `protobuf:"bytes,2,opt,name=orderID" json:"orderID,omitempty"`
	TriggerNumber     uint32   `protobuf:"varint,3,opt,name=triggerNumber" json:"triggerNumber,omitempty"`
	TriggerTemplateID string   `protobuf:"bytes,4,opt,name=triggerTemplateID" json:"triggerTemplateID,omitempty"`
	Name              string   `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	Code              string   `protobuf:"bytes,6,opt,name=code" json:"code,omitempty"`
	Triggered         bool     `protobuf:"varint,7,opt,name=triggered" json:"triggered,omitempty"`
	CreatedOn         string   `protobuf:"bytes,8,opt,name=createdOn" json:"createdOn,omitempty"`
	UpdatedOn         string   `protobuf:"bytes,9,opt,name=updatedOn" json:"updatedOn,omitempty"`
	Actions           []string `protobuf:"bytes,10,rep,name=actions" json:"actions,omitempty"`
}

func (m *Trigger) Reset()                    { *m = Trigger{} }
func (m *Trigger) String() string            { return proto.CompactTextString(m) }
func (*Trigger) ProtoMessage()               {}
func (*Trigger) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Trigger) GetTriggerID() string {
	if m != nil {
		return m.TriggerID
	}
	return ""
}

func (m *Trigger) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *Trigger) GetTriggerNumber() uint32 {
	if m != nil {
		return m.TriggerNumber
	}
	return 0
}

func (m *Trigger) GetTriggerTemplateID() string {
	if m != nil {
		return m.TriggerTemplateID
	}
	return ""
}

func (m *Trigger) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Trigger) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Trigger) GetTriggered() bool {
	if m != nil {
		return m.Triggered
	}
	return false
}

func (m *Trigger) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *Trigger) GetUpdatedOn() string {
	if m != nil {
		return m.UpdatedOn
	}
	return ""
}

func (m *Trigger) GetActions() []string {
	if m != nil {
		return m.Actions
	}
	return nil
}

// Responses
type UserOrderData struct {
	Order *Order `protobuf:"bytes,1,opt,name=order" json:"order,omitempty"`
}

func (m *UserOrderData) Reset()                    { *m = UserOrderData{} }
func (m *UserOrderData) String() string            { return proto.CompactTextString(m) }
func (*UserOrderData) ProtoMessage()               {}
func (*UserOrderData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UserOrderData) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type UserOrdersData struct {
	Orders []*Order `protobuf:"bytes,1,rep,name=orders" json:"orders,omitempty"`
}

func (m *UserOrdersData) Reset()                    { *m = UserOrdersData{} }
func (m *UserOrdersData) String() string            { return proto.CompactTextString(m) }
func (*UserOrdersData) ProtoMessage()               {}
func (*UserOrdersData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UserOrdersData) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type OrderResponse struct {
	Status  string         `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Message string         `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Data    *UserOrderData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *OrderResponse) Reset()                    { *m = OrderResponse{} }
func (m *OrderResponse) String() string            { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()               {}
func (*OrderResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *OrderResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OrderResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *OrderResponse) GetData() *UserOrderData {
	if m != nil {
		return m.Data
	}
	return nil
}

type OrderListResponse struct {
	Status  string          `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Message string          `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Data    *UserOrdersData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *OrderListResponse) Reset()                    { *m = OrderListResponse{} }
func (m *OrderListResponse) String() string            { return proto.CompactTextString(m) }
func (*OrderListResponse) ProtoMessage()               {}
func (*OrderListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *OrderListResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OrderListResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *OrderListResponse) GetData() *UserOrdersData {
	if m != nil {
		return m.Data
	}
	return nil
}

type OrdersPage struct {
	Page     uint32   `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	PageSize uint32   `protobuf:"varint,2,opt,name=pageSize" json:"pageSize,omitempty"`
	Total    uint32   `protobuf:"varint,3,opt,name=total" json:"total,omitempty"`
	Orders   []*Order `protobuf:"bytes,4,rep,name=orders" json:"orders,omitempty"`
}

func (m *OrdersPage) Reset()                    { *m = OrdersPage{} }
func (m *OrdersPage) String() string            { return proto.CompactTextString(m) }
func (*OrdersPage) ProtoMessage()               {}
func (*OrdersPage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *OrdersPage) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *OrdersPage) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *OrdersPage) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *OrdersPage) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func init() {
	proto.RegisterType((*TriggerRequest)(nil), "order.TriggerRequest")
	proto.RegisterType((*UpdateOrderRequest)(nil), "order.UpdateOrderRequest")
	proto.RegisterType((*NewOrderRequest)(nil), "order.NewOrderRequest")
	proto.RegisterType((*GetUserOrderRequest)(nil), "order.GetUserOrderRequest")
	proto.RegisterType((*GetUserOrdersRequest)(nil), "order.GetUserOrdersRequest")
	proto.RegisterType((*RemoveOrderRequest)(nil), "order.RemoveOrderRequest")
	proto.RegisterType((*Order)(nil), "order.Order")
	proto.RegisterType((*Trigger)(nil), "order.Trigger")
	proto.RegisterType((*UserOrderData)(nil), "order.UserOrderData")
	proto.RegisterType((*UserOrdersData)(nil), "order.UserOrdersData")
	proto.RegisterType((*OrderResponse)(nil), "order.OrderResponse")
	proto.RegisterType((*OrderListResponse)(nil), "order.OrderListResponse")
	proto.RegisterType((*OrdersPage)(nil), "order.OrdersPage")
}

func init() {
	proto.RegisterFile("github.com/asciiu/gomo/plan-service/proto/order/order.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 838 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x56, 0xdd, 0x6e, 0xeb, 0x44,
	0x10, 0x96, 0x1b, 0xc7, 0x49, 0x26, 0x4d, 0x72, 0xba, 0xa7, 0xa7, 0x5a, 0xa1, 0x0a, 0x45, 0x51,
	0x85, 0x02, 0x82, 0x44, 0xb4, 0x12, 0x37, 0xdc, 0xa1, 0x88, 0xaa, 0x12, 0xb4, 0x95, 0x69, 0x1f,
	0x60, 0xe3, 0x8c, 0x52, 0xab, 0xf1, 0x0f, 0xde, 0x75, 0x69, 0x79, 0x11, 0xee, 0x78, 0x07, 0x9e,
	0x8c, 0x17, 0xe0, 0x02, 0xed, 0x8f, 0xed, 0xb5, 0x93, 0xd2, 0xa2, 0x72, 0x85, 0xce, 0x4d, 0xbb,
	0xf3, 0xcd, 0xac, 0x67, 0x32, 0xf3, 0x7d, 0xbb, 0x0b, 0xdf, 0xae, 0x43, 0x71, 0x97, 0x2f, 0x67,
	0x41, 0x12, 0xcd, 0x19, 0x0f, 0xc2, 0x30, 0x9f, 0xaf, 0x93, 0x28, 0x99, 0xa7, 0x1b, 0x16, 0x7f,
	0xc5, 0x31, 0x7b, 0x08, 0x03, 0x9c, 0xa7, 0x59, 0x22, 0x92, 0x79, 0x92, 0xad, 0x30, 0xd3, 0x7f,
	0x67, 0x0a, 0x21, 0x6d, 0x65, 0x4c, 0x7e, 0x77, 0x60, 0x78, 0x93, 0x85, 0xeb, 0x35, 0x66, 0x3e,
	0xfe, 0x9c, 0x23, 0x17, 0xe4, 0x18, 0x7a, 0x42, 0x23, 0x17, 0x0b, 0xea, 0x8c, 0x9d, 0x69, 0xcf,
	0xaf, 0x00, 0x42, 0xc0, 0x8d, 0x59, 0x84, 0x74, 0x4f, 0x39, 0xd4, 0x5a, 0x62, 0x41, 0xb2, 0x42,
	0xda, 0xd2, 0x98, 0x5c, 0x93, 0x2f, 0xe1, 0xc0, 0x6c, 0xba, 0xc1, 0x28, 0xdd, 0x30, 0x81, 0x17,
	0x0b, 0xea, 0xaa, 0x80, 0x6d, 0x07, 0xa1, 0xd0, 0x61, 0x81, 0x08, 0x93, 0x98, 0xd3, 0xf6, 0xb8,
	0x35, 0xed, 0xf9, 0x85, 0x39, 0xf9, 0xcd, 0x05, 0x72, 0x9b, 0xae, 0x98, 0xc0, 0x2b, 0x59, 0x70,
	0x51, 0x24, 0x85, 0x8e, 0xfa, 0x01, 0x65, 0x89, 0x85, 0x29, 0xcb, 0x57, 0xcb, 0x9b, 0xa7, 0xb4,
	0xa8, 0xb2, 0x02, 0xc8, 0x14, 0x46, 0xda, 0xa8, 0x8a, 0xd2, 0x55, 0x37, 0x61, 0x72, 0x08, 0xed,
	0x7b, 0x7c, 0x2a, 0x8b, 0xd6, 0x06, 0x39, 0x81, 0x41, 0xca, 0x32, 0x8c, 0xc5, 0x95, 0xc9, 0xde,
	0x56, 0xde, 0x3a, 0x48, 0x8e, 0xc0, 0x93, 0x43, 0xb8, 0x58, 0x50, 0x4f, 0xb9, 0x8d, 0x25, 0x6b,
	0x93, 0xab, 0x05, 0xa6, 0xe2, 0x8e, 0x76, 0x74, 0x6d, 0x25, 0x40, 0x3e, 0x81, 0x2e, 0x3e, 0x06,
	0x77, 0x2c, 0x5e, 0x23, 0xed, 0x2a, 0x67, 0x69, 0x93, 0x4f, 0x01, 0x22, 0x96, 0xdd, 0xa3, 0xb8,
	0x94, 0xcd, 0xef, 0x29, 0xaf, 0x85, 0xc8, 0x11, 0xf0, 0x70, 0x85, 0x14, 0xf4, 0x08, 0xe4, 0x5a,
	0xee, 0xd9, 0x84, 0x51, 0x28, 0xae, 0xb3, 0x30, 0x40, 0xda, 0x1f, 0x3b, 0x53, 0xc7, 0xb7, 0x10,
	0xf2, 0x19, 0x0c, 0x53, 0xcc, 0x02, 0x8c, 0xc5, 0x77, 0x6c, 0xc3, 0xe2, 0x00, 0xe9, 0xbe, 0x8a,
	0x69, 0xa0, 0x64, 0x0c, 0xfd, 0x25, 0xe3, 0x58, 0x04, 0x0d, 0x54, 0x90, 0x0d, 0xc9, 0xae, 0x06,
	0x79, 0x96, 0x61, 0x1c, 0x3c, 0x15, 0x51, 0x43, 0x15, 0xd5, 0x84, 0x65, 0x67, 0xf4, 0x64, 0xe9,
	0x48, 0x77, 0x46, 0x5b, 0xe4, 0x6b, 0xe8, 0x1a, 0x56, 0x70, 0xfa, 0x6e, 0xdc, 0x9a, 0xf6, 0x4f,
	0x3f, 0xcc, 0x34, 0x5d, 0xeb, 0xec, 0xf4, 0xcb, 0xb0, 0xc9, 0x5f, 0x2d, 0x18, 0x5d, 0xe2, 0x2f,
	0x1f, 0x69, 0xf1, 0x3f, 0xa0, 0x85, 0x3d, 0xfe, 0xd1, 0xeb, 0xc6, 0x7f, 0x0e, 0xef, 0xcf, 0x51,
	0xdc, 0x72, 0xcc, 0x5e, 0xc9, 0x80, 0x23, 0xf0, 0x72, 0xae, 0x1c, 0x7a, 0xfc, 0xc6, 0x9a, 0xcc,
	0xe0, 0xd0, 0xfe, 0x10, 0x2f, 0xbe, 0x54, 0xc5, 0x3b, 0xb5, 0xf8, 0xef, 0x81, 0xf8, 0x18, 0x25,
	0x0f, 0xf8, 0xc6, 0xbc, 0x7f, 0xba, 0xd0, 0x56, 0x9f, 0xb0, 0x78, 0xe1, 0x3c, 0xcf, 0x0b, 0xb9,
	0x79, 0x60, 0xf3, 0xc2, 0xca, 0xd8, 0xaa, 0x67, 0x2c, 0xa6, 0xee, 0x5a, 0x53, 0xdf, 0xc1, 0xf0,
	0xf6, 0x0b, 0x0c, 0x7f, 0x6f, 0x33, 0xbc, 0xa6, 0x1f, 0xaf, 0xa9, 0x9f, 0x3a, 0xa7, 0x3a, 0x5b,
	0x9c, 0x3a, 0x02, 0x8f, 0x0b, 0x26, 0x72, 0x6e, 0x18, 0x6c, 0xac, 0x6d, 0xdd, 0xf4, 0x76, 0xe9,
	0xc6, 0x56, 0x00, 0x34, 0x14, 0x30, 0x03, 0x52, 0xac, 0x7f, 0xac, 0x94, 0xd0, 0x57, 0x51, 0x3b,
	0x3c, 0x0d, 0xc5, 0xec, 0x6f, 0x29, 0xe6, 0xbf, 0x64, 0xf5, 0xb6, 0x92, 0x46, 0x3b, 0x95, 0x74,
	0x0c, 0xbd, 0x20, 0x43, 0x26, 0x70, 0x75, 0x15, 0xd3, 0x77, 0xba, 0xb7, 0x25, 0x20, 0xbd, 0xb9,
	0xba, 0x00, 0xa5, 0xf7, 0x40, 0x7b, 0x4b, 0x80, 0x7c, 0x61, 0x29, 0x87, 0x28, 0xe5, 0x0c, 0x1b,
	0xca, 0xa9, 0x24, 0xf3, 0xc7, 0x1e, 0x74, 0x0c, 0xfa, 0xc2, 0x2d, 0x6f, 0x71, 0x6b, 0xaf, 0xce,
	0xad, 0x13, 0x18, 0x98, 0xb0, 0xcb, 0x3c, 0x5a, 0x62, 0xa6, 0xb8, 0x37, 0xf0, 0xeb, 0xe0, 0xbf,
	0xbc, 0xfd, 0x8b, 0x37, 0x45, 0x7b, 0xc7, 0x9b, 0xc2, 0xb3, 0xde, 0x14, 0x55, 0xcd, 0xb8, 0x52,
	0x24, 0xeb, 0xfa, 0x15, 0x50, 0xef, 0x62, 0xf7, 0x1f, 0xbb, 0xd8, 0x6b, 0x76, 0xd1, 0x7a, 0x7f,
	0x40, 0xfd, 0xfd, 0x71, 0x06, 0x83, 0xf2, 0x68, 0x58, 0x30, 0xc1, 0xc8, 0x04, 0xf4, 0xd3, 0x49,
	0x35, 0xad, 0x7f, 0xba, 0x6f, 0xba, 0xad, 0x0f, 0x03, 0xf3, 0xaa, 0xfa, 0x06, 0x86, 0xd5, 0x79,
	0xa2, 0x76, 0x9d, 0x80, 0xa7, 0x5c, 0x9c, 0x3a, 0x6a, 0x48, 0xf5, 0x6d, 0xc6, 0x37, 0xb9, 0x87,
	0x81, 0x39, 0x54, 0x78, 0x9a, 0xc4, 0xdc, 0xd6, 0x8d, 0x53, 0xd3, 0x0d, 0x85, 0x4e, 0x84, 0x9c,
	0xb3, 0x75, 0x71, 0x97, 0x15, 0x26, 0x99, 0x82, 0xbb, 0x62, 0x82, 0xa9, 0xb1, 0xf4, 0x4f, 0x0f,
	0x4d, 0x9a, 0xda, 0x4f, 0xf0, 0x55, 0xc4, 0x24, 0x85, 0x03, 0x05, 0xfd, 0x10, 0x72, 0xf1, 0x86,
	0x84, 0x9f, 0xd7, 0x12, 0x7e, 0x68, 0x26, 0xe4, 0x56, 0xc6, 0x47, 0x00, 0x8d, 0x5d, 0xcb, 0x8d,
	0x04, 0xdc, 0x54, 0x7e, 0xcf, 0x51, 0x04, 0x52, 0x6b, 0xa9, 0x74, 0xf9, 0xff, 0xa7, 0xf0, 0x57,
	0x34, 0x07, 0x5e, 0x69, 0xcb, 0x73, 0x49, 0x24, 0x82, 0x6d, 0x0c, 0xe3, 0xb4, 0x61, 0x35, 0xd6,
	0x7d, 0xbe, 0xb1, 0x4b, 0x4f, 0x3d, 0x7a, 0xcf, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x85, 0xa5,
	0x76, 0xf8, 0x33, 0x0b, 0x00, 0x00,
}
