// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/asciiu/gomo/plan-service/proto/order/order.proto

/*
Package order is a generated protocol buffer package.

It is generated from these files:
	github.com/asciiu/gomo/plan-service/proto/order/order.proto

It has these top-level messages:
	TriggerRequest
	NewOrderRequest
	GetUserOrderRequest
	GetUserOrdersRequest
	RemoveOrderRequest
	Order
	Trigger
	UserOrderData
	UserOrdersData
	OrderResponse
	OrderListResponse
	OrdersPage
*/
package order

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Requests
type TriggerRequest struct {
	TriggerID         string   `protobuf:"bytes,1,opt,name=triggerID" json:"triggerID"`
	Code              string   `protobuf:"bytes,2,opt,name=code" json:"code"`
	Index             uint32   `protobuf:"varint,3,opt,name=index" json:"index"`
	Name              string   `protobuf:"bytes,4,opt,name=name" json:"name"`
	Title             string   `protobuf:"bytes,5,opt,name=title" json:"title"`
	TriggerTemplateID string   `protobuf:"bytes,6,opt,name=triggerTemplateID" json:"triggerTemplateID"`
	Actions           []string `protobuf:"bytes,7,rep,name=actions" json:"actions"`
}

func (m *TriggerRequest) Reset()                    { *m = TriggerRequest{} }
func (m *TriggerRequest) String() string            { return proto.CompactTextString(m) }
func (*TriggerRequest) ProtoMessage()               {}
func (*TriggerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TriggerRequest) GetTriggerID() string {
	if m != nil {
		return m.TriggerID
	}
	return ""
}

func (m *TriggerRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *TriggerRequest) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *TriggerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TriggerRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TriggerRequest) GetTriggerTemplateID() string {
	if m != nil {
		return m.TriggerTemplateID
	}
	return ""
}

func (m *TriggerRequest) GetActions() []string {
	if m != nil {
		return m.Actions
	}
	return nil
}

type NewOrderRequest struct {
	OrderID                string            `protobuf:"bytes,1,opt,name=orderID" json:"orderID"`
	OrderPriority          uint32            `protobuf:"varint,2,opt,name=orderPriority" json:"orderPriority"`
	OrderType              string            `protobuf:"bytes,3,opt,name=orderType" json:"orderType"`
	OrderTemplateID        string            `protobuf:"bytes,4,opt,name=orderTemplateID" json:"orderTemplateID"`
	AccountID              string            `protobuf:"bytes,5,opt,name=accountID" json:"accountID"`
	ParentOrderID          string            `protobuf:"bytes,6,opt,name=parentOrderID" json:"parentOrderID"`
	Grupo                  string            `protobuf:"bytes,7,opt,name=grupo" json:"grupo"`
	MarketName             string            `protobuf:"bytes,8,opt,name=marketName" json:"marketName"`
	Side                   string            `protobuf:"bytes,9,opt,name=side" json:"side"`
	LimitPrice             float64           `protobuf:"fixed64,10,opt,name=limitPrice" json:"limitPrice"`
	InitialCurrencyBalance float64           `protobuf:"fixed64,11,opt,name=initialCurrencyBalance" json:"initialCurrencyBalance"`
	Triggers               []*TriggerRequest `protobuf:"bytes,12,rep,name=triggers" json:"triggers"`
}

func (m *NewOrderRequest) Reset()                    { *m = NewOrderRequest{} }
func (m *NewOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*NewOrderRequest) ProtoMessage()               {}
func (*NewOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NewOrderRequest) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *NewOrderRequest) GetOrderPriority() uint32 {
	if m != nil {
		return m.OrderPriority
	}
	return 0
}

func (m *NewOrderRequest) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func (m *NewOrderRequest) GetOrderTemplateID() string {
	if m != nil {
		return m.OrderTemplateID
	}
	return ""
}

func (m *NewOrderRequest) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *NewOrderRequest) GetParentOrderID() string {
	if m != nil {
		return m.ParentOrderID
	}
	return ""
}

func (m *NewOrderRequest) GetGrupo() string {
	if m != nil {
		return m.Grupo
	}
	return ""
}

func (m *NewOrderRequest) GetMarketName() string {
	if m != nil {
		return m.MarketName
	}
	return ""
}

func (m *NewOrderRequest) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *NewOrderRequest) GetLimitPrice() float64 {
	if m != nil {
		return m.LimitPrice
	}
	return 0
}

func (m *NewOrderRequest) GetInitialCurrencyBalance() float64 {
	if m != nil {
		return m.InitialCurrencyBalance
	}
	return 0
}

func (m *NewOrderRequest) GetTriggers() []*TriggerRequest {
	if m != nil {
		return m.Triggers
	}
	return nil
}

type GetUserOrderRequest struct {
	OrderID string `protobuf:"bytes,1,opt,name=orderID" json:"orderID"`
	UserID  string `protobuf:"bytes,2,opt,name=userID" json:"userID"`
}

func (m *GetUserOrderRequest) Reset()                    { *m = GetUserOrderRequest{} }
func (m *GetUserOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserOrderRequest) ProtoMessage()               {}
func (*GetUserOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetUserOrderRequest) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *GetUserOrderRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetUserOrdersRequest struct {
	UserID string `protobuf:"bytes,1,opt,name=userID" json:"userID"`
}

func (m *GetUserOrdersRequest) Reset()                    { *m = GetUserOrdersRequest{} }
func (m *GetUserOrdersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserOrdersRequest) ProtoMessage()               {}
func (*GetUserOrdersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetUserOrdersRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type RemoveOrderRequest struct {
	OrderID string `protobuf:"bytes,1,opt,name=orderID" json:"orderID"`
	UserID  string `protobuf:"bytes,2,opt,name=userID" json:"userID"`
}

func (m *RemoveOrderRequest) Reset()                    { *m = RemoveOrderRequest{} }
func (m *RemoveOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveOrderRequest) ProtoMessage()               {}
func (*RemoveOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RemoveOrderRequest) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *RemoveOrderRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type Order struct {
	OrderID                  string     `protobuf:"bytes,1,opt,name=orderID" json:"orderID"`
	ParentOrderID            string     `protobuf:"bytes,2,opt,name=parentOrderID" json:"parentOrderID"`
	PlanID                   string     `protobuf:"bytes,3,opt,name=planID" json:"planID"`
	PlanDepth                uint32     `protobuf:"varint,4,opt,name=planDepth" json:"planDepth"`
	OrderTemplateID          string     `protobuf:"bytes,5,opt,name=orderTemplateID" json:"orderTemplateID"`
	AccountID                string     `protobuf:"bytes,6,opt,name=accountID" json:"accountID"`
	AccountType              string     `protobuf:"bytes,29,opt,name=accountType" json:"accountType"`
	KeyPublic                string     `protobuf:"bytes,7,opt,name=keyPublic" json:"keyPublic"`
	KeySecret                string     `protobuf:"bytes,8,opt,name=keySecret" json:"keySecret"`
	KeyDescription           string     `protobuf:"bytes,9,opt,name=keyDescription" json:"keyDescription"`
	OrderPriority            uint32     `protobuf:"varint,10,opt,name=orderPriority" json:"orderPriority"`
	OrderType                string     `protobuf:"bytes,11,opt,name=orderType" json:"orderType"`
	Side                     string     `protobuf:"bytes,12,opt,name=side" json:"side"`
	LimitPrice               float64    `protobuf:"fixed64,13,opt,name=limitPrice" json:"limitPrice"`
	Exchange                 string     `protobuf:"bytes,14,opt,name=exchange" json:"exchange"`
	ExchangeOrderID          string     `protobuf:"bytes,15,opt,name=exchangeOrderID" json:"exchangeOrderID"`
	ExchangeMarketName       string     `protobuf:"bytes,16,opt,name=exchangeMarketName" json:"exchangeMarketName"`
	MarketName               string     `protobuf:"bytes,17,opt,name=marketName" json:"marketName"`
	InitialCurrencySymbol    string     `protobuf:"bytes,18,opt,name=initialCurrencySymbol" json:"initialCurrencySymbol"`
	InitialCurrencyBalance   float64    `protobuf:"fixed64,19,opt,name=initialCurrencyBalance" json:"initialCurrencyBalance"`
	InitialCurrencyTraded    float64    `protobuf:"fixed64,20,opt,name=initialCurrencyTraded" json:"initialCurrencyTraded"`
	InitialCurrencyRemainder float64    `protobuf:"fixed64,21,opt,name=initialCurrencyRemainder" json:"initialCurrencyRemainder"`
	FinalCurrencySymbol      string     `protobuf:"bytes,22,opt,name=finalCurrencySymbol" json:"finalCurrencySymbol"`
	FinalCurrencyBalance     float64    `protobuf:"fixed64,23,opt,name=finalCurrencyBalance" json:"finalCurrencyBalance"`
	Status                   string     `protobuf:"bytes,24,opt,name=status" json:"status"`
	Grupo                    string     `protobuf:"bytes,25,opt,name=grupo" json:"grupo"`
	CreatedOn                string     `protobuf:"bytes,26,opt,name=createdOn" json:"createdOn"`
	UpdatedOn                string     `protobuf:"bytes,27,opt,name=updatedOn" json:"updatedOn"`
	Triggers                 []*Trigger `protobuf:"bytes,28,rep,name=triggers" json:"triggers"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Order) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *Order) GetParentOrderID() string {
	if m != nil {
		return m.ParentOrderID
	}
	return ""
}

func (m *Order) GetPlanID() string {
	if m != nil {
		return m.PlanID
	}
	return ""
}

func (m *Order) GetPlanDepth() uint32 {
	if m != nil {
		return m.PlanDepth
	}
	return 0
}

func (m *Order) GetOrderTemplateID() string {
	if m != nil {
		return m.OrderTemplateID
	}
	return ""
}

func (m *Order) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *Order) GetAccountType() string {
	if m != nil {
		return m.AccountType
	}
	return ""
}

func (m *Order) GetKeyPublic() string {
	if m != nil {
		return m.KeyPublic
	}
	return ""
}

func (m *Order) GetKeySecret() string {
	if m != nil {
		return m.KeySecret
	}
	return ""
}

func (m *Order) GetKeyDescription() string {
	if m != nil {
		return m.KeyDescription
	}
	return ""
}

func (m *Order) GetOrderPriority() uint32 {
	if m != nil {
		return m.OrderPriority
	}
	return 0
}

func (m *Order) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func (m *Order) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *Order) GetLimitPrice() float64 {
	if m != nil {
		return m.LimitPrice
	}
	return 0
}

func (m *Order) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *Order) GetExchangeOrderID() string {
	if m != nil {
		return m.ExchangeOrderID
	}
	return ""
}

func (m *Order) GetExchangeMarketName() string {
	if m != nil {
		return m.ExchangeMarketName
	}
	return ""
}

func (m *Order) GetMarketName() string {
	if m != nil {
		return m.MarketName
	}
	return ""
}

func (m *Order) GetInitialCurrencySymbol() string {
	if m != nil {
		return m.InitialCurrencySymbol
	}
	return ""
}

func (m *Order) GetInitialCurrencyBalance() float64 {
	if m != nil {
		return m.InitialCurrencyBalance
	}
	return 0
}

func (m *Order) GetInitialCurrencyTraded() float64 {
	if m != nil {
		return m.InitialCurrencyTraded
	}
	return 0
}

func (m *Order) GetInitialCurrencyRemainder() float64 {
	if m != nil {
		return m.InitialCurrencyRemainder
	}
	return 0
}

func (m *Order) GetFinalCurrencySymbol() string {
	if m != nil {
		return m.FinalCurrencySymbol
	}
	return ""
}

func (m *Order) GetFinalCurrencyBalance() float64 {
	if m != nil {
		return m.FinalCurrencyBalance
	}
	return 0
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Order) GetGrupo() string {
	if m != nil {
		return m.Grupo
	}
	return ""
}

func (m *Order) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *Order) GetUpdatedOn() string {
	if m != nil {
		return m.UpdatedOn
	}
	return ""
}

func (m *Order) GetTriggers() []*Trigger {
	if m != nil {
		return m.Triggers
	}
	return nil
}

type Trigger struct {
	TriggerID          string   `protobuf:"bytes,1,opt,name=triggerID" json:"triggerID"`
	TriggerTemplateID  string   `protobuf:"bytes,2,opt,name=triggerTemplateID" json:"triggerTemplateID"`
	OrderID            string   `protobuf:"bytes,3,opt,name=orderID" json:"orderID"`
	Index              uint32   `protobuf:"varint,4,opt,name=index" json:"index"`
	Title              string   `protobuf:"bytes,5,opt,name=title" json:"title"`
	Name               string   `protobuf:"bytes,6,opt,name=name" json:"name"`
	Code               string   `protobuf:"bytes,7,opt,name=code" json:"code"`
	Triggered          bool     `protobuf:"varint,8,opt,name=triggered" json:"triggered"`
	TriggeredPrice     float64  `protobuf:"fixed64,9,opt,name=triggeredPrice" json:"triggeredPrice"`
	TriggeredCondition string   `protobuf:"bytes,10,opt,name=triggeredCondition" json:"triggeredCondition"`
	TriggeredTimestamp string   `protobuf:"bytes,11,opt,name=triggeredTimestamp" json:"triggeredTimestamp"`
	CreatedOn          string   `protobuf:"bytes,12,opt,name=createdOn" json:"createdOn"`
	UpdatedOn          string   `protobuf:"bytes,13,opt,name=updatedOn" json:"updatedOn"`
	Actions            []string `protobuf:"bytes,14,rep,name=actions" json:"actions"`
}

func (m *Trigger) Reset()                    { *m = Trigger{} }
func (m *Trigger) String() string            { return proto.CompactTextString(m) }
func (*Trigger) ProtoMessage()               {}
func (*Trigger) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Trigger) GetTriggerID() string {
	if m != nil {
		return m.TriggerID
	}
	return ""
}

func (m *Trigger) GetTriggerTemplateID() string {
	if m != nil {
		return m.TriggerTemplateID
	}
	return ""
}

func (m *Trigger) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *Trigger) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Trigger) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Trigger) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Trigger) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Trigger) GetTriggered() bool {
	if m != nil {
		return m.Triggered
	}
	return false
}

func (m *Trigger) GetTriggeredPrice() float64 {
	if m != nil {
		return m.TriggeredPrice
	}
	return 0
}

func (m *Trigger) GetTriggeredCondition() string {
	if m != nil {
		return m.TriggeredCondition
	}
	return ""
}

func (m *Trigger) GetTriggeredTimestamp() string {
	if m != nil {
		return m.TriggeredTimestamp
	}
	return ""
}

func (m *Trigger) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *Trigger) GetUpdatedOn() string {
	if m != nil {
		return m.UpdatedOn
	}
	return ""
}

func (m *Trigger) GetActions() []string {
	if m != nil {
		return m.Actions
	}
	return nil
}

// Responses
type UserOrderData struct {
	Order *Order `protobuf:"bytes,1,opt,name=order" json:"order"`
}

func (m *UserOrderData) Reset()                    { *m = UserOrderData{} }
func (m *UserOrderData) String() string            { return proto.CompactTextString(m) }
func (*UserOrderData) ProtoMessage()               {}
func (*UserOrderData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UserOrderData) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type UserOrdersData struct {
	Orders []*Order `protobuf:"bytes,1,rep,name=orders" json:"orders"`
}

func (m *UserOrdersData) Reset()                    { *m = UserOrdersData{} }
func (m *UserOrdersData) String() string            { return proto.CompactTextString(m) }
func (*UserOrdersData) ProtoMessage()               {}
func (*UserOrdersData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UserOrdersData) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type OrderResponse struct {
	Status  string         `protobuf:"bytes,1,opt,name=status" json:"status"`
	Message string         `protobuf:"bytes,2,opt,name=message" json:"message"`
	Data    *UserOrderData `protobuf:"bytes,3,opt,name=data" json:"data"`
}

func (m *OrderResponse) Reset()                    { *m = OrderResponse{} }
func (m *OrderResponse) String() string            { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()               {}
func (*OrderResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *OrderResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OrderResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *OrderResponse) GetData() *UserOrderData {
	if m != nil {
		return m.Data
	}
	return nil
}

type OrderListResponse struct {
	Status  string          `protobuf:"bytes,1,opt,name=status" json:"status"`
	Message string          `protobuf:"bytes,2,opt,name=message" json:"message"`
	Data    *UserOrdersData `protobuf:"bytes,3,opt,name=data" json:"data"`
}

func (m *OrderListResponse) Reset()                    { *m = OrderListResponse{} }
func (m *OrderListResponse) String() string            { return proto.CompactTextString(m) }
func (*OrderListResponse) ProtoMessage()               {}
func (*OrderListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *OrderListResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OrderListResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *OrderListResponse) GetData() *UserOrdersData {
	if m != nil {
		return m.Data
	}
	return nil
}

type OrdersPage struct {
	Page     uint32   `protobuf:"varint,1,opt,name=page" json:"page"`
	PageSize uint32   `protobuf:"varint,2,opt,name=pageSize" json:"pageSize"`
	Total    uint32   `protobuf:"varint,3,opt,name=total" json:"total"`
	Orders   []*Order `protobuf:"bytes,4,rep,name=orders" json:"orders"`
}

func (m *OrdersPage) Reset()                    { *m = OrdersPage{} }
func (m *OrdersPage) String() string            { return proto.CompactTextString(m) }
func (*OrdersPage) ProtoMessage()               {}
func (*OrdersPage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *OrdersPage) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *OrdersPage) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *OrdersPage) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *OrdersPage) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func init() {
	proto.RegisterType((*TriggerRequest)(nil), "order.TriggerRequest")
	proto.RegisterType((*NewOrderRequest)(nil), "order.NewOrderRequest")
	proto.RegisterType((*GetUserOrderRequest)(nil), "order.GetUserOrderRequest")
	proto.RegisterType((*GetUserOrdersRequest)(nil), "order.GetUserOrdersRequest")
	proto.RegisterType((*RemoveOrderRequest)(nil), "order.RemoveOrderRequest")
	proto.RegisterType((*Order)(nil), "order.Order")
	proto.RegisterType((*Trigger)(nil), "order.Trigger")
	proto.RegisterType((*UserOrderData)(nil), "order.UserOrderData")
	proto.RegisterType((*UserOrdersData)(nil), "order.UserOrdersData")
	proto.RegisterType((*OrderResponse)(nil), "order.OrderResponse")
	proto.RegisterType((*OrderListResponse)(nil), "order.OrderListResponse")
	proto.RegisterType((*OrdersPage)(nil), "order.OrdersPage")
}

func init() {
	proto.RegisterFile("github.com/asciiu/gomo/plan-service/proto/order/order.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 994 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x6d, 0x6f, 0x23, 0x35,
	0x10, 0x56, 0x9a, 0x34, 0x69, 0x26, 0x4d, 0x4a, 0xdd, 0x17, 0xcc, 0x51, 0x50, 0x14, 0x9d, 0x50,
	0x40, 0xd0, 0x42, 0x0f, 0xdd, 0x07, 0xf8, 0xc6, 0x45, 0x9c, 0x2a, 0xc1, 0xb5, 0xda, 0x96, 0x1f,
	0xe0, 0xee, 0x0e, 0xa9, 0xd5, 0xec, 0x0b, 0xb6, 0x73, 0x34, 0xfc, 0x2c, 0x24, 0x3e, 0xf3, 0x9d,
	0x5f, 0x85, 0x3c, 0xf6, 0x66, 0x5f, 0xb2, 0xed, 0x9d, 0x74, 0x5f, 0x5a, 0xcf, 0xf3, 0x8c, 0xd7,
	0x19, 0xcf, 0x33, 0x33, 0x86, 0x1f, 0xe7, 0xd2, 0xdc, 0x2d, 0x6f, 0x4f, 0xc3, 0x34, 0x3e, 0x13,
	0x3a, 0x94, 0x72, 0x79, 0x36, 0x4f, 0xe3, 0xf4, 0x2c, 0x5b, 0x88, 0xe4, 0x1b, 0x8d, 0xea, 0xad,
	0x0c, 0xf1, 0x2c, 0x53, 0xa9, 0x49, 0xcf, 0x52, 0x15, 0xa1, 0x72, 0x7f, 0x4f, 0x09, 0x61, 0xdb,
	0x64, 0x4c, 0xfe, 0x6b, 0xc1, 0xe8, 0x46, 0xc9, 0xf9, 0x1c, 0x55, 0x80, 0x7f, 0x2c, 0x51, 0x1b,
	0x76, 0x02, 0x7d, 0xe3, 0x90, 0x8b, 0x19, 0x6f, 0x8d, 0x5b, 0xd3, 0x7e, 0x50, 0x00, 0x8c, 0x41,
	0x27, 0x4c, 0x23, 0xe4, 0x5b, 0x44, 0xd0, 0x9a, 0x1d, 0xc2, 0xb6, 0x4c, 0x22, 0x7c, 0xe0, 0xed,
	0x71, 0x6b, 0x3a, 0x0c, 0x9c, 0x61, 0x3d, 0x13, 0x11, 0x23, 0xef, 0x38, 0x4f, 0xbb, 0xb6, 0x9e,
	0x46, 0x9a, 0x05, 0xf2, 0x6d, 0x02, 0x9d, 0xc1, 0xbe, 0x86, 0x7d, 0x7f, 0xc0, 0x0d, 0xc6, 0xd9,
	0x42, 0x18, 0xbc, 0x98, 0xf1, 0x2e, 0x79, 0x6c, 0x12, 0x8c, 0x43, 0x4f, 0x84, 0x46, 0xa6, 0x89,
	0xe6, 0xbd, 0x71, 0x7b, 0xda, 0x0f, 0x72, 0x73, 0xf2, 0x77, 0x1b, 0xf6, 0xde, 0xe0, 0x9f, 0x97,
	0x36, 0xb2, 0x3c, 0x1a, 0x0e, 0x3d, 0x8a, 0x74, 0x1d, 0x4b, 0x6e, 0xb2, 0xe7, 0x30, 0xa4, 0xe5,
	0x95, 0x92, 0xa9, 0x92, 0x66, 0x45, 0x21, 0x0d, 0x83, 0x2a, 0x68, 0x6f, 0x83, 0x80, 0x9b, 0x55,
	0x86, 0x14, 0x5f, 0x3f, 0x28, 0x00, 0x36, 0x85, 0x3d, 0x67, 0x14, 0xbf, 0xdb, 0x85, 0x5b, 0x87,
	0xed, 0x77, 0x44, 0x18, 0xa6, 0xcb, 0xc4, 0x5c, 0xcc, 0x7c, 0xf4, 0x05, 0x60, 0x7f, 0x4b, 0x26,
	0x14, 0x26, 0xe6, 0xd2, 0xff, 0x56, 0x17, 0x7d, 0x15, 0xb4, 0xb7, 0x37, 0x57, 0xcb, 0x2c, 0xe5,
	0x3d, 0x77, 0x7b, 0x64, 0xb0, 0xcf, 0x01, 0x62, 0xa1, 0xee, 0xd1, 0xbc, 0xb1, 0xb7, 0xbd, 0x43,
	0x54, 0x09, 0xb1, 0x79, 0xd0, 0x32, 0x42, 0xde, 0x77, 0x79, 0xb0, 0x6b, 0xbb, 0x67, 0x21, 0x63,
	0x69, 0xae, 0x94, 0x0c, 0x91, 0xc3, 0xb8, 0x35, 0x6d, 0x05, 0x25, 0x84, 0xbd, 0x84, 0x63, 0x99,
	0x48, 0x23, 0xc5, 0xe2, 0xd5, 0x52, 0x29, 0x4c, 0xc2, 0xd5, 0x4f, 0x62, 0x21, 0x92, 0x10, 0xf9,
	0x80, 0x7c, 0x1f, 0x61, 0xd9, 0x77, 0xb0, 0xe3, 0x13, 0xa6, 0xf9, 0xee, 0xb8, 0x3d, 0x1d, 0x9c,
	0x1f, 0x9d, 0x3a, 0xd5, 0x55, 0x45, 0x16, 0xac, 0xdd, 0x26, 0xaf, 0xe1, 0xe0, 0x35, 0x9a, 0xdf,
	0x34, 0xaa, 0xf7, 0xcc, 0xdb, 0x31, 0x74, 0x97, 0x9a, 0x08, 0xa7, 0x41, 0x6f, 0x4d, 0x4e, 0xe1,
	0xb0, 0xfc, 0x21, 0x9d, 0x7f, 0xa9, 0xf0, 0x6f, 0x55, 0xfc, 0x7f, 0x06, 0x16, 0x60, 0x9c, 0xbe,
	0xc5, 0x0f, 0x3c, 0xf7, 0x9f, 0x1d, 0xd8, 0xa6, 0x4f, 0x3c, 0xad, 0xb5, 0x6a, 0x7e, 0xb7, 0x9a,
	0xf2, 0x7b, 0x0c, 0x5d, 0x5b, 0xbb, 0x17, 0x33, 0x2f, 0x34, 0x6f, 0x59, 0xed, 0xd8, 0xd5, 0x0c,
	0x33, 0x73, 0x47, 0xfa, 0x1a, 0x06, 0x05, 0xd0, 0xa4, 0xc1, 0xed, 0xf7, 0xd0, 0x60, 0xb7, 0xae,
	0xc1, 0x31, 0x0c, 0xbc, 0x41, 0x5a, 0xff, 0x8c, 0xf8, 0x32, 0x64, 0xf7, 0xdf, 0xe3, 0xea, 0x6a,
	0x79, 0xbb, 0x90, 0xa1, 0xd7, 0x60, 0x01, 0x78, 0xf6, 0x1a, 0x43, 0x85, 0xc6, 0xcb, 0xb0, 0x00,
	0xd8, 0x17, 0x30, 0xba, 0xc7, 0xd5, 0x0c, 0x75, 0xa8, 0x64, 0x66, 0xcb, 0xd5, 0xeb, 0xb1, 0x86,
	0x6e, 0x56, 0x25, 0xbc, 0xb3, 0x2a, 0x07, 0xf5, 0xaa, 0xcc, 0x15, 0xbf, 0xfb, 0xa8, 0xe2, 0x87,
	0x1b, 0x8a, 0x7f, 0x06, 0x3b, 0xf8, 0x10, 0xde, 0x89, 0x64, 0x8e, 0x7c, 0x44, 0xfb, 0xd6, 0xb6,
	0xbd, 0xe1, 0x7c, 0x9d, 0xe7, 0x6f, 0xcf, 0xdd, 0x70, 0x0d, 0x66, 0xa7, 0xc0, 0x72, 0xe8, 0xd7,
	0xa2, 0x26, 0x3f, 0x22, 0xe7, 0x06, 0xa6, 0x56, 0xbb, 0xfb, 0x1b, 0xb5, 0xfb, 0x3d, 0x1c, 0xd5,
	0x2a, 0xed, 0x7a, 0x15, 0xdf, 0xa6, 0x0b, 0xce, 0xc8, 0xb5, 0x99, 0x7c, 0xa2, 0x7a, 0x0f, 0x9e,
	0xac, 0xde, 0xcd, 0xd3, 0x6e, 0x94, 0x88, 0x30, 0xe2, 0x87, 0xb4, 0xad, 0x99, 0x64, 0x3f, 0x00,
	0xaf, 0x11, 0x01, 0xc6, 0xc2, 0xce, 0x00, 0xc5, 0x8f, 0x68, 0xe3, 0xa3, 0x3c, 0xfb, 0x16, 0x0e,
	0x7e, 0x97, 0xc9, 0x46, 0x74, 0xc7, 0x14, 0x5d, 0x13, 0xc5, 0xce, 0xe1, 0xb0, 0x02, 0xe7, 0x91,
	0x7d, 0x4c, 0x27, 0x35, 0x72, 0xb6, 0xae, 0xb4, 0x11, 0x66, 0xa9, 0x39, 0x77, 0x75, 0xe5, 0xac,
	0xa2, 0x9f, 0x7e, 0x52, 0xee, 0xa7, 0x27, 0xd0, 0x0f, 0x15, 0x0a, 0x83, 0xd1, 0x65, 0xc2, 0x9f,
	0x39, 0x6d, 0xad, 0x01, 0xcb, 0x2e, 0xb3, 0xc8, 0xb3, 0x9f, 0x3a, 0x76, 0x0d, 0xb0, 0xaf, 0x4a,
	0xfd, 0xef, 0x84, 0xfa, 0xdf, 0xa8, 0xd6, 0xff, 0x8a, 0xc6, 0xf7, 0x6f, 0x1b, 0x7a, 0x1e, 0x7d,
	0xc7, 0xcc, 0x6d, 0x9c, 0x8f, 0x5b, 0x4f, 0xcc, 0xc7, 0xbc, 0x0b, 0xb5, 0xab, 0x5d, 0x68, 0x3d,
	0xa7, 0x3b, 0xe5, 0x39, 0xdd, 0x3c, 0x93, 0xf3, 0xe9, 0xdd, 0x2d, 0x4d, 0xef, 0x7c, 0xf6, 0xf7,
	0x4a, 0xb3, 0xbf, 0xf8, 0xe5, 0x18, 0x51, 0xd5, 0xef, 0x04, 0x05, 0x60, 0xab, 0x7e, 0x6d, 0xb8,
	0xca, 0xeb, 0x53, 0x9e, 0x6a, 0xa8, 0xad, 0x9b, 0x35, 0xf2, 0x2a, 0x4d, 0x22, 0x49, 0x1d, 0x02,
	0x5c, 0xdd, 0x6c, 0x32, 0x15, 0xff, 0x1b, 0x19, 0xa3, 0x36, 0x22, 0xce, 0x7c, 0x23, 0x68, 0x60,
	0xaa, 0x39, 0xdd, 0x7d, 0x32, 0xa7, 0xc3, 0x7a, 0x4e, 0x4b, 0xef, 0x8d, 0x51, 0xf5, 0xbd, 0xf1,
	0x02, 0x86, 0xeb, 0x71, 0x33, 0x13, 0x46, 0xb0, 0x09, 0xb8, 0x67, 0x15, 0xa5, 0x70, 0x70, 0xbe,
	0xeb, 0x73, 0xef, 0x06, 0x8c, 0x7f, 0x71, 0xbd, 0x84, 0x51, 0x31, 0xa3, 0x68, 0xd7, 0x73, 0xe8,
	0x12, 0xa5, 0x79, 0x8b, 0x24, 0x53, 0xdd, 0xe6, 0xb9, 0xc9, 0x3d, 0x0c, 0xfd, 0xa0, 0xd2, 0x59,
	0x9a, 0xe8, 0xb2, 0xaa, 0x5b, 0x15, 0x55, 0x73, 0xe8, 0xc5, 0xa8, 0xb5, 0x98, 0xe7, 0x8f, 0xb4,
	0xdc, 0x64, 0x53, 0xe8, 0x44, 0xc2, 0x08, 0x92, 0xc5, 0xe0, 0xfc, 0xd0, 0x1f, 0x53, 0x09, 0x21,
	0x20, 0x8f, 0x49, 0x06, 0xfb, 0x04, 0xfd, 0x22, 0xb5, 0xf9, 0x80, 0x03, 0xbf, 0xac, 0x1c, 0x78,
	0x54, 0x3f, 0x50, 0x97, 0x4e, 0x7c, 0x00, 0x70, 0xd8, 0x95, 0xdd, 0xc8, 0xa0, 0x93, 0xd9, 0xef,
	0xb5, 0x48, 0xa8, 0xb4, 0xb6, 0x1d, 0xda, 0xfe, 0xbf, 0x96, 0x7f, 0xa1, 0x7f, 0xaa, 0xad, 0x6d,
	0xd2, 0x70, 0x6a, 0xc4, 0x22, 0x7f, 0x81, 0x92, 0x51, 0xba, 0xd8, 0xce, 0xe3, 0x17, 0x7b, 0xdb,
	0xa5, 0x07, 0xf1, 0x8b, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x48, 0x48, 0x24, 0xf5, 0x4f, 0x0b,
	0x00, 0x00,
}
