// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/asciiu/gomo/plan-service/proto/order/order.proto

/*
Package order is a generated protocol buffer package.

It is generated from these files:
	github.com/asciiu/gomo/plan-service/proto/order/order.proto

It has these top-level messages:
	TriggerRequest
	NewOrderRequest
	GetUserOrderRequest
	GetUserOrdersRequest
	RemoveOrderRequest
	Order
	Trigger
	UserOrderData
	UserOrdersData
	OrderResponse
	OrderListResponse
	OrdersPage
*/
package order

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Requests
type TriggerRequest struct {
	TriggerID         string   `protobuf:"bytes,1,opt,name=triggerID" json:"triggerID,omitempty"`
	Name              string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Code              string   `protobuf:"bytes,3,opt,name=code" json:"code,omitempty"`
	TriggerTemplateID string   `protobuf:"bytes,4,opt,name=triggerTemplateID" json:"triggerTemplateID,omitempty"`
	Actions           []string `protobuf:"bytes,5,rep,name=actions" json:"actions,omitempty"`
}

func (m *TriggerRequest) Reset()                    { *m = TriggerRequest{} }
func (m *TriggerRequest) String() string            { return proto.CompactTextString(m) }
func (*TriggerRequest) ProtoMessage()               {}
func (*TriggerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TriggerRequest) GetTriggerID() string {
	if m != nil {
		return m.TriggerID
	}
	return ""
}

func (m *TriggerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TriggerRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *TriggerRequest) GetTriggerTemplateID() string {
	if m != nil {
		return m.TriggerTemplateID
	}
	return ""
}

func (m *TriggerRequest) GetActions() []string {
	if m != nil {
		return m.Actions
	}
	return nil
}

type NewOrderRequest struct {
	OrderID               string            `protobuf:"bytes,1,opt,name=orderID" json:"orderID,omitempty"`
	OrderPriority         uint32            `protobuf:"varint,2,opt,name=orderPriority" json:"orderPriority,omitempty"`
	OrderType             string            `protobuf:"bytes,3,opt,name=orderType" json:"orderType,omitempty"`
	OrderTemplateID       string            `protobuf:"bytes,4,opt,name=orderTemplateID" json:"orderTemplateID,omitempty"`
	KeyID                 string            `protobuf:"bytes,5,opt,name=keyID" json:"keyID,omitempty"`
	ParentOrderID         string            `protobuf:"bytes,6,opt,name=parentOrderID" json:"parentOrderID,omitempty"`
	MarketName            string            `protobuf:"bytes,7,opt,name=marketName" json:"marketName,omitempty"`
	Side                  string            `protobuf:"bytes,8,opt,name=side" json:"side,omitempty"`
	LimitPrice            float64           `protobuf:"fixed64,9,opt,name=limitPrice" json:"limitPrice,omitempty"`
	ActiveCurrencyBalance float64           `protobuf:"fixed64,10,opt,name=activeCurrencyBalance" json:"activeCurrencyBalance,omitempty"`
	Triggers              []*TriggerRequest `protobuf:"bytes,11,rep,name=triggers" json:"triggers,omitempty"`
}

func (m *NewOrderRequest) Reset()                    { *m = NewOrderRequest{} }
func (m *NewOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*NewOrderRequest) ProtoMessage()               {}
func (*NewOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NewOrderRequest) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *NewOrderRequest) GetOrderPriority() uint32 {
	if m != nil {
		return m.OrderPriority
	}
	return 0
}

func (m *NewOrderRequest) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func (m *NewOrderRequest) GetOrderTemplateID() string {
	if m != nil {
		return m.OrderTemplateID
	}
	return ""
}

func (m *NewOrderRequest) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *NewOrderRequest) GetParentOrderID() string {
	if m != nil {
		return m.ParentOrderID
	}
	return ""
}

func (m *NewOrderRequest) GetMarketName() string {
	if m != nil {
		return m.MarketName
	}
	return ""
}

func (m *NewOrderRequest) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *NewOrderRequest) GetLimitPrice() float64 {
	if m != nil {
		return m.LimitPrice
	}
	return 0
}

func (m *NewOrderRequest) GetActiveCurrencyBalance() float64 {
	if m != nil {
		return m.ActiveCurrencyBalance
	}
	return 0
}

func (m *NewOrderRequest) GetTriggers() []*TriggerRequest {
	if m != nil {
		return m.Triggers
	}
	return nil
}

type GetUserOrderRequest struct {
	OrderID string `protobuf:"bytes,1,opt,name=orderID" json:"orderID,omitempty"`
	UserID  string `protobuf:"bytes,2,opt,name=userID" json:"userID,omitempty"`
}

func (m *GetUserOrderRequest) Reset()                    { *m = GetUserOrderRequest{} }
func (m *GetUserOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserOrderRequest) ProtoMessage()               {}
func (*GetUserOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetUserOrderRequest) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *GetUserOrderRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetUserOrdersRequest struct {
	UserID string `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
}

func (m *GetUserOrdersRequest) Reset()                    { *m = GetUserOrdersRequest{} }
func (m *GetUserOrdersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserOrdersRequest) ProtoMessage()               {}
func (*GetUserOrdersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetUserOrdersRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type RemoveOrderRequest struct {
	OrderID string `protobuf:"bytes,1,opt,name=orderID" json:"orderID,omitempty"`
	UserID  string `protobuf:"bytes,2,opt,name=userID" json:"userID,omitempty"`
}

func (m *RemoveOrderRequest) Reset()                    { *m = RemoveOrderRequest{} }
func (m *RemoveOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveOrderRequest) ProtoMessage()               {}
func (*RemoveOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RemoveOrderRequest) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *RemoveOrderRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type Order struct {
	OrderID               string     `protobuf:"bytes,1,opt,name=orderID" json:"orderID,omitempty"`
	ParentOrderID         string     `protobuf:"bytes,2,opt,name=parentOrderID" json:"parentOrderID,omitempty"`
	PlanID                string     `protobuf:"bytes,3,opt,name=planID" json:"planID,omitempty"`
	PlanDepth             uint32     `protobuf:"varint,4,opt,name=planDepth" json:"planDepth,omitempty"`
	OrderTemplateID       string     `protobuf:"bytes,5,opt,name=orderTemplateID" json:"orderTemplateID,omitempty"`
	KeyID                 string     `protobuf:"bytes,6,opt,name=keyID" json:"keyID,omitempty"`
	KeyPublic             string     `protobuf:"bytes,7,opt,name=keyPublic" json:"keyPublic,omitempty"`
	KeySecret             string     `protobuf:"bytes,8,opt,name=keySecret" json:"keySecret,omitempty"`
	KeyDescription        string     `protobuf:"bytes,9,opt,name=keyDescription" json:"keyDescription,omitempty"`
	OrderPriority         uint32     `protobuf:"varint,10,opt,name=orderPriority" json:"orderPriority,omitempty"`
	OrderType             string     `protobuf:"bytes,11,opt,name=orderType" json:"orderType,omitempty"`
	Side                  string     `protobuf:"bytes,12,opt,name=side" json:"side,omitempty"`
	LimitPrice            float64    `protobuf:"fixed64,13,opt,name=limitPrice" json:"limitPrice,omitempty"`
	Exchange              string     `protobuf:"bytes,14,opt,name=exchange" json:"exchange,omitempty"`
	ExchangeMarketName    string     `protobuf:"bytes,15,opt,name=exchangeMarketName" json:"exchangeMarketName,omitempty"`
	MarketName            string     `protobuf:"bytes,16,opt,name=marketName" json:"marketName,omitempty"`
	ActiveCurrencySymbol  string     `protobuf:"bytes,17,opt,name=activeCurrencySymbol" json:"activeCurrencySymbol,omitempty"`
	ActiveCurrencyBalance float64    `protobuf:"fixed64,18,opt,name=activeCurrencyBalance" json:"activeCurrencyBalance,omitempty"`
	ActiveCurrencyTraded  float64    `protobuf:"fixed64,19,opt,name=activeCurrencyTraded" json:"activeCurrencyTraded,omitempty"`
	Status                string     `protobuf:"bytes,20,opt,name=status" json:"status,omitempty"`
	CreatedOn             string     `protobuf:"bytes,21,opt,name=createdOn" json:"createdOn,omitempty"`
	UpdatedOn             string     `protobuf:"bytes,22,opt,name=updatedOn" json:"updatedOn,omitempty"`
	Triggers              []*Trigger `protobuf:"bytes,23,rep,name=triggers" json:"triggers,omitempty"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Order) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *Order) GetParentOrderID() string {
	if m != nil {
		return m.ParentOrderID
	}
	return ""
}

func (m *Order) GetPlanID() string {
	if m != nil {
		return m.PlanID
	}
	return ""
}

func (m *Order) GetPlanDepth() uint32 {
	if m != nil {
		return m.PlanDepth
	}
	return 0
}

func (m *Order) GetOrderTemplateID() string {
	if m != nil {
		return m.OrderTemplateID
	}
	return ""
}

func (m *Order) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *Order) GetKeyPublic() string {
	if m != nil {
		return m.KeyPublic
	}
	return ""
}

func (m *Order) GetKeySecret() string {
	if m != nil {
		return m.KeySecret
	}
	return ""
}

func (m *Order) GetKeyDescription() string {
	if m != nil {
		return m.KeyDescription
	}
	return ""
}

func (m *Order) GetOrderPriority() uint32 {
	if m != nil {
		return m.OrderPriority
	}
	return 0
}

func (m *Order) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func (m *Order) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *Order) GetLimitPrice() float64 {
	if m != nil {
		return m.LimitPrice
	}
	return 0
}

func (m *Order) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *Order) GetExchangeMarketName() string {
	if m != nil {
		return m.ExchangeMarketName
	}
	return ""
}

func (m *Order) GetMarketName() string {
	if m != nil {
		return m.MarketName
	}
	return ""
}

func (m *Order) GetActiveCurrencySymbol() string {
	if m != nil {
		return m.ActiveCurrencySymbol
	}
	return ""
}

func (m *Order) GetActiveCurrencyBalance() float64 {
	if m != nil {
		return m.ActiveCurrencyBalance
	}
	return 0
}

func (m *Order) GetActiveCurrencyTraded() float64 {
	if m != nil {
		return m.ActiveCurrencyTraded
	}
	return 0
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Order) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *Order) GetUpdatedOn() string {
	if m != nil {
		return m.UpdatedOn
	}
	return ""
}

func (m *Order) GetTriggers() []*Trigger {
	if m != nil {
		return m.Triggers
	}
	return nil
}

type Trigger struct {
	TriggerID         string   `protobuf:"bytes,1,opt,name=triggerID" json:"triggerID,omitempty"`
	OrderID           string   `protobuf:"bytes,2,opt,name=orderID" json:"orderID,omitempty"`
	TriggerNumber     uint32   `protobuf:"varint,3,opt,name=triggerNumber" json:"triggerNumber,omitempty"`
	TriggerTemplateID string   `protobuf:"bytes,4,opt,name=triggerTemplateID" json:"triggerTemplateID,omitempty"`
	Name              string   `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	Code              string   `protobuf:"bytes,6,opt,name=code" json:"code,omitempty"`
	Triggered         bool     `protobuf:"varint,7,opt,name=triggered" json:"triggered,omitempty"`
	CreatedOn         string   `protobuf:"bytes,8,opt,name=createdOn" json:"createdOn,omitempty"`
	UpdatedOn         string   `protobuf:"bytes,9,opt,name=updatedOn" json:"updatedOn,omitempty"`
	Actions           []string `protobuf:"bytes,10,rep,name=actions" json:"actions,omitempty"`
}

func (m *Trigger) Reset()                    { *m = Trigger{} }
func (m *Trigger) String() string            { return proto.CompactTextString(m) }
func (*Trigger) ProtoMessage()               {}
func (*Trigger) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Trigger) GetTriggerID() string {
	if m != nil {
		return m.TriggerID
	}
	return ""
}

func (m *Trigger) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *Trigger) GetTriggerNumber() uint32 {
	if m != nil {
		return m.TriggerNumber
	}
	return 0
}

func (m *Trigger) GetTriggerTemplateID() string {
	if m != nil {
		return m.TriggerTemplateID
	}
	return ""
}

func (m *Trigger) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Trigger) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Trigger) GetTriggered() bool {
	if m != nil {
		return m.Triggered
	}
	return false
}

func (m *Trigger) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *Trigger) GetUpdatedOn() string {
	if m != nil {
		return m.UpdatedOn
	}
	return ""
}

func (m *Trigger) GetActions() []string {
	if m != nil {
		return m.Actions
	}
	return nil
}

// Responses
type UserOrderData struct {
	Order *Order `protobuf:"bytes,1,opt,name=order" json:"order,omitempty"`
}

func (m *UserOrderData) Reset()                    { *m = UserOrderData{} }
func (m *UserOrderData) String() string            { return proto.CompactTextString(m) }
func (*UserOrderData) ProtoMessage()               {}
func (*UserOrderData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UserOrderData) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type UserOrdersData struct {
	Orders []*Order `protobuf:"bytes,1,rep,name=orders" json:"orders,omitempty"`
}

func (m *UserOrdersData) Reset()                    { *m = UserOrdersData{} }
func (m *UserOrdersData) String() string            { return proto.CompactTextString(m) }
func (*UserOrdersData) ProtoMessage()               {}
func (*UserOrdersData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UserOrdersData) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type OrderResponse struct {
	Status  string         `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Message string         `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Data    *UserOrderData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *OrderResponse) Reset()                    { *m = OrderResponse{} }
func (m *OrderResponse) String() string            { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()               {}
func (*OrderResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *OrderResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OrderResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *OrderResponse) GetData() *UserOrderData {
	if m != nil {
		return m.Data
	}
	return nil
}

type OrderListResponse struct {
	Status  string          `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Message string          `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Data    *UserOrdersData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *OrderListResponse) Reset()                    { *m = OrderListResponse{} }
func (m *OrderListResponse) String() string            { return proto.CompactTextString(m) }
func (*OrderListResponse) ProtoMessage()               {}
func (*OrderListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *OrderListResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OrderListResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *OrderListResponse) GetData() *UserOrdersData {
	if m != nil {
		return m.Data
	}
	return nil
}

type OrdersPage struct {
	Page     uint32   `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	PageSize uint32   `protobuf:"varint,2,opt,name=pageSize" json:"pageSize,omitempty"`
	Total    uint32   `protobuf:"varint,3,opt,name=total" json:"total,omitempty"`
	Orders   []*Order `protobuf:"bytes,4,rep,name=orders" json:"orders,omitempty"`
}

func (m *OrdersPage) Reset()                    { *m = OrdersPage{} }
func (m *OrdersPage) String() string            { return proto.CompactTextString(m) }
func (*OrdersPage) ProtoMessage()               {}
func (*OrdersPage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *OrdersPage) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *OrdersPage) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *OrdersPage) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *OrdersPage) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func init() {
	proto.RegisterType((*TriggerRequest)(nil), "order.TriggerRequest")
	proto.RegisterType((*NewOrderRequest)(nil), "order.NewOrderRequest")
	proto.RegisterType((*GetUserOrderRequest)(nil), "order.GetUserOrderRequest")
	proto.RegisterType((*GetUserOrdersRequest)(nil), "order.GetUserOrdersRequest")
	proto.RegisterType((*RemoveOrderRequest)(nil), "order.RemoveOrderRequest")
	proto.RegisterType((*Order)(nil), "order.Order")
	proto.RegisterType((*Trigger)(nil), "order.Trigger")
	proto.RegisterType((*UserOrderData)(nil), "order.UserOrderData")
	proto.RegisterType((*UserOrdersData)(nil), "order.UserOrdersData")
	proto.RegisterType((*OrderResponse)(nil), "order.OrderResponse")
	proto.RegisterType((*OrderListResponse)(nil), "order.OrderListResponse")
	proto.RegisterType((*OrdersPage)(nil), "order.OrdersPage")
}

func init() {
	proto.RegisterFile("github.com/asciiu/gomo/plan-service/proto/order/order.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 846 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x6e, 0x2b, 0x35,
	0x10, 0xd6, 0xb6, 0xf9, 0x9d, 0x9c, 0xa4, 0xd4, 0x27, 0x2d, 0x16, 0x3a, 0x42, 0x55, 0x74, 0x84,
	0x02, 0x82, 0x44, 0xf4, 0x20, 0x6e, 0xb8, 0x83, 0x88, 0xa3, 0x4a, 0xd0, 0x56, 0xdb, 0xf0, 0x00,
	0xce, 0xee, 0x28, 0x5d, 0x25, 0xfb, 0x83, 0xed, 0x2d, 0x27, 0x3c, 0x06, 0x0f, 0xc0, 0x0d, 0x4f,
	0xc0, 0x1b, 0x22, 0x8f, 0xbd, 0xd9, 0xdd, 0x24, 0x6d, 0x39, 0xea, 0x4d, 0xeb, 0xf9, 0x66, 0xec,
	0x99, 0x1d, 0x7f, 0x9f, 0x27, 0xf0, 0xc3, 0x32, 0xd2, 0xf7, 0xf9, 0x62, 0x12, 0xa4, 0xf1, 0x54,
	0xa8, 0x20, 0x8a, 0xf2, 0xe9, 0x32, 0x8d, 0xd3, 0x69, 0xb6, 0x16, 0xc9, 0x37, 0x0a, 0xe5, 0x43,
	0x14, 0xe0, 0x34, 0x93, 0xa9, 0x4e, 0xa7, 0xa9, 0x0c, 0x51, 0xda, 0xbf, 0x13, 0x42, 0x58, 0x93,
	0x8c, 0xd1, 0xdf, 0x1e, 0x0c, 0xe6, 0x32, 0x5a, 0x2e, 0x51, 0xfa, 0xf8, 0x7b, 0x8e, 0x4a, 0xb3,
	0x37, 0xd0, 0xd5, 0x16, 0xb9, 0x9a, 0x71, 0xef, 0xc2, 0x1b, 0x77, 0xfd, 0x12, 0x60, 0x0c, 0x1a,
	0x89, 0x88, 0x91, 0x1f, 0x91, 0x83, 0xd6, 0x06, 0x0b, 0xd2, 0x10, 0xf9, 0xb1, 0xc5, 0xcc, 0x9a,
	0x7d, 0x0d, 0xa7, 0x6e, 0xd3, 0x1c, 0xe3, 0x6c, 0x2d, 0x34, 0x5e, 0xcd, 0x78, 0x83, 0x02, 0xf6,
	0x1d, 0x8c, 0x43, 0x5b, 0x04, 0x3a, 0x4a, 0x13, 0xc5, 0x9b, 0x17, 0xc7, 0xe3, 0xae, 0x5f, 0x98,
	0xa3, 0xbf, 0x8e, 0xe1, 0xe4, 0x1a, 0xff, 0xb8, 0x31, 0xd5, 0x16, 0x15, 0x72, 0x68, 0x53, 0xf5,
	0xdb, 0xfa, 0x0a, 0x93, 0xbd, 0x85, 0x3e, 0x2d, 0x6f, 0x65, 0x94, 0xca, 0x48, 0x6f, 0xa8, 0xcc,
	0xbe, 0x5f, 0x07, 0xcd, 0x17, 0x12, 0x30, 0xdf, 0x64, 0x45, 0xd1, 0x25, 0xc0, 0xc6, 0x70, 0x62,
	0x8d, 0xdd, 0xba, 0x77, 0x61, 0x36, 0x84, 0xe6, 0x0a, 0x37, 0x57, 0x33, 0xde, 0x24, 0xbf, 0x35,
	0x4c, 0x0d, 0x99, 0x90, 0x98, 0xe8, 0x1b, 0x57, 0x63, 0x8b, 0xbc, 0x75, 0x90, 0x7d, 0x0e, 0x10,
	0x0b, 0xb9, 0x42, 0x7d, 0x6d, 0xba, 0xd9, 0xa6, 0x90, 0x0a, 0x62, 0x7a, 0xaa, 0xa2, 0x10, 0x79,
	0xc7, 0xf6, 0xd4, 0xac, 0xcd, 0x9e, 0x75, 0x14, 0x47, 0xfa, 0x56, 0x46, 0x01, 0xf2, 0xee, 0x85,
	0x37, 0xf6, 0xfc, 0x0a, 0xc2, 0xbe, 0x83, 0x33, 0xd3, 0xb6, 0x07, 0xfc, 0x29, 0x97, 0x12, 0x93,
	0x60, 0xf3, 0xa3, 0x58, 0x8b, 0x24, 0x40, 0x0e, 0x14, 0x7a, 0xd8, 0xc9, 0xbe, 0x85, 0x8e, 0xbb,
	0x10, 0xc5, 0x7b, 0x17, 0xc7, 0xe3, 0xde, 0xe5, 0xd9, 0xc4, 0x32, 0xa5, 0x4e, 0x0c, 0x7f, 0x1b,
	0x36, 0x7a, 0x0f, 0xaf, 0xdf, 0xa3, 0xfe, 0x4d, 0xa1, 0xfc, 0x9f, 0xf7, 0x72, 0x0e, 0xad, 0x5c,
	0x91, 0xc3, 0xf2, 0xc6, 0x59, 0xa3, 0x09, 0x0c, 0xab, 0x07, 0xa9, 0xe2, 0xa4, 0x32, 0xde, 0xab,
	0xc5, 0xff, 0x0c, 0xcc, 0xc7, 0x38, 0x7d, 0xc0, 0x17, 0xe6, 0xfd, 0xa7, 0x05, 0x4d, 0x3a, 0xe2,
	0x69, 0x2e, 0xd5, 0xef, 0xf1, 0xe8, 0xd0, 0x3d, 0x9e, 0x43, 0xcb, 0xe8, 0xed, 0x6a, 0xe6, 0x88,
	0xe4, 0x2c, 0xc3, 0x31, 0xb3, 0x9a, 0x61, 0xa6, 0xef, 0x89, 0x3f, 0x7d, 0xbf, 0x04, 0x0e, 0x71,
	0xac, 0xf9, 0x0c, 0xc7, 0x5a, 0x55, 0x8e, 0xbd, 0x81, 0xee, 0x0a, 0x37, 0xb7, 0xf9, 0x62, 0x1d,
	0x05, 0x8e, 0x3c, 0x25, 0xe0, 0xbc, 0x77, 0x18, 0x48, 0xd4, 0x8e, 0x40, 0x25, 0xc0, 0xbe, 0x80,
	0xc1, 0x0a, 0x37, 0x33, 0x54, 0x81, 0x8c, 0x32, 0x23, 0x32, 0x62, 0x52, 0xd7, 0xdf, 0x41, 0xf7,
	0xb5, 0x04, 0xcf, 0x6a, 0xa9, 0xb7, 0xab, 0xa5, 0x82, 0xc5, 0xaf, 0x1e, 0x65, 0x71, 0x7f, 0x8f,
	0xc5, 0x9f, 0x41, 0x07, 0x3f, 0x04, 0xf7, 0x22, 0x59, 0x22, 0x1f, 0xd0, 0xbe, 0xad, 0xcd, 0x26,
	0xc0, 0x8a, 0xf5, 0xaf, 0xa5, 0x7a, 0x4e, 0x28, 0xea, 0x80, 0x67, 0x47, 0x65, 0x9f, 0xec, 0xa9,
	0xec, 0x12, 0x86, 0x75, 0x51, 0xdc, 0x6d, 0xe2, 0x45, 0xba, 0xe6, 0xa7, 0x14, 0x79, 0xd0, 0xf7,
	0xb8, 0xca, 0xd8, 0x53, 0x2a, 0xdb, 0xcb, 0x34, 0x97, 0x22, 0xc4, 0x90, 0xbf, 0xa6, 0x4d, 0x07,
	0x7d, 0x86, 0x5b, 0x4a, 0x0b, 0x9d, 0x2b, 0x3e, 0xb4, 0xdc, 0xb2, 0x96, 0xe9, 0x79, 0x20, 0x51,
	0x68, 0x0c, 0x6f, 0x12, 0x7e, 0x66, 0x7b, 0xbe, 0x05, 0x8c, 0x37, 0xcf, 0x42, 0xe7, 0x3d, 0xb7,
	0xde, 0x2d, 0xc0, 0xbe, 0xaa, 0xa8, 0xfd, 0x53, 0x52, 0xfb, 0x60, 0x47, 0xed, 0xa5, 0xcc, 0xff,
	0x3d, 0x82, 0xb6, 0x43, 0x9f, 0x99, 0x0a, 0x15, 0x15, 0x1d, 0xed, 0xa9, 0xc8, 0x85, 0x5d, 0xe7,
	0xf1, 0x02, 0x25, 0xc9, 0xa4, 0xef, 0xd7, 0xc1, 0x8f, 0x9c, 0x16, 0xc5, 0x0c, 0x6a, 0x1e, 0x98,
	0x41, 0xad, 0xca, 0x0c, 0x2a, 0x6b, 0xc6, 0x90, 0x54, 0xd2, 0xf1, 0x4b, 0xa0, 0xde, 0xc5, 0xce,
	0x93, 0x5d, 0xec, 0xee, 0x76, 0xb1, 0x32, 0xaf, 0xa0, 0x3e, 0xaf, 0xde, 0x41, 0x7f, 0xfb, 0x9c,
	0xcd, 0x84, 0x16, 0x6c, 0x04, 0x76, 0xd4, 0x52, 0xd3, 0x7a, 0x97, 0xaf, 0x5c, 0xb7, 0xed, 0x03,
	0xe6, 0xa6, 0xf0, 0xf7, 0x30, 0x28, 0xdf, 0x40, 0xda, 0xf5, 0x16, 0x5a, 0xe4, 0x52, 0xdc, 0xa3,
	0x4b, 0xaa, 0x6f, 0x73, 0xbe, 0xd1, 0x0a, 0xfa, 0xee, 0x21, 0x54, 0x59, 0x9a, 0x28, 0xac, 0x30,
	0xc6, 0xab, 0x31, 0x86, 0x43, 0x3b, 0x46, 0xa5, 0xc4, 0xb2, 0x18, 0xdc, 0x85, 0xc9, 0xc6, 0xd0,
	0x08, 0x85, 0x16, 0x74, 0x2d, 0xbd, 0xcb, 0xa1, 0x4b, 0x53, 0xfb, 0x04, 0x9f, 0x22, 0x46, 0x19,
	0x9c, 0x12, 0xf4, 0x4b, 0xa4, 0xf4, 0x0b, 0x12, 0x7e, 0x59, 0x4b, 0x78, 0xb6, 0x9b, 0x50, 0x55,
	0x32, 0x7e, 0x00, 0xb0, 0xd8, 0xad, 0xd9, 0xc8, 0xa0, 0x91, 0x99, 0xf3, 0x3c, 0x22, 0x10, 0xad,
	0xcd, 0x5b, 0x61, 0xfe, 0xdf, 0x45, 0x7f, 0xa2, 0x1b, 0xf5, 0x5b, 0xdb, 0xbc, 0x9c, 0x3a, 0xd5,
	0x62, 0xed, 0x18, 0x67, 0x8d, 0x4a, 0x63, 0x1b, 0x8f, 0x37, 0x76, 0xd1, 0xa2, 0x1f, 0x49, 0xef,
	0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x57, 0x0b, 0xda, 0x63, 0x09, 0x00, 0x00,
}
