apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: accounts 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts 
  template:
    metadata:
      labels:
        app: accounts 
    spec:
        containers:
        - name: account-service 
          image: us.gcr.io/fomo-204904/account-service:dev
          imagePullPolicy: Always 
          command: [
            "./account-service",
            "--selector=static",
            "--server_address=:8080"
          ]
          envFrom:
          - configMapRef:
              name: fomo-config
          env:
          - name: UPDATED_AT
            value: "Tue Oct 16 17:30:56 MDT 2018" 
          ports:
          - containerPort: 8080
            name: accounts-port
