// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/asciiu/gomo/account-service/proto/balance/balance.proto

/*
Package bal is a generated protocol buffer package.

It is generated from these files:
	github.com/asciiu/gomo/account-service/proto/balance/balance.proto

It has these top-level messages:
	NewBalanceRequest
	BalanceRequest
	UpdateBalanceRequest
	ValidateBalanceRequest
	Balance
	BalanceData
	BalanceResponse
	ValidateBalanceResponse
*/
package bal

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Requests
type NewBalanceRequest struct {
	AccountID      string  `protobuf:"bytes,1,opt,name=accountID" json:"accountID,omitempty"`
	CurrencySymbol string  `protobuf:"bytes,2,opt,name=currencySymbol" json:"currencySymbol,omitempty"`
	Available      float64 `protobuf:"fixed64,3,opt,name=available" json:"available,omitempty"`
}

func (m *NewBalanceRequest) Reset()                    { *m = NewBalanceRequest{} }
func (m *NewBalanceRequest) String() string            { return proto.CompactTextString(m) }
func (*NewBalanceRequest) ProtoMessage()               {}
func (*NewBalanceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NewBalanceRequest) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *NewBalanceRequest) GetCurrencySymbol() string {
	if m != nil {
		return m.CurrencySymbol
	}
	return ""
}

func (m *NewBalanceRequest) GetAvailable() float64 {
	if m != nil {
		return m.Available
	}
	return 0
}

type BalanceRequest struct {
	AccountID      string `protobuf:"bytes,1,opt,name=accountID" json:"accountID,omitempty"`
	CurrencySymbol string `protobuf:"bytes,2,opt,name=currencySymbol" json:"currencySymbol,omitempty"`
}

func (m *BalanceRequest) Reset()                    { *m = BalanceRequest{} }
func (m *BalanceRequest) String() string            { return proto.CompactTextString(m) }
func (*BalanceRequest) ProtoMessage()               {}
func (*BalanceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BalanceRequest) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *BalanceRequest) GetCurrencySymbol() string {
	if m != nil {
		return m.CurrencySymbol
	}
	return ""
}

type UpdateBalanceRequest struct {
	AccountID         string  `protobuf:"bytes,1,opt,name=accountID" json:"accountID,omitempty"`
	CurrencySymbol    string  `protobuf:"bytes,2,opt,name=currencySymbol" json:"currencySymbol,omitempty"`
	Available         float64 `protobuf:"fixed64,3,opt,name=available" json:"available,omitempty"`
	Locked            float64 `protobuf:"fixed64,4,opt,name=locked" json:"locked,omitempty"`
	ExchangeTotal     float64 `protobuf:"fixed64,5,opt,name=exchangeTotal" json:"exchangeTotal,omitempty"`
	ExchangeAvailable float64 `protobuf:"fixed64,6,opt,name=exchangeAvailable" json:"exchangeAvailable,omitempty"`
	ExchangeLocked    float64 `protobuf:"fixed64,7,opt,name=exchangeLocked" json:"exchangeLocked,omitempty"`
}

func (m *UpdateBalanceRequest) Reset()                    { *m = UpdateBalanceRequest{} }
func (m *UpdateBalanceRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateBalanceRequest) ProtoMessage()               {}
func (*UpdateBalanceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpdateBalanceRequest) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *UpdateBalanceRequest) GetCurrencySymbol() string {
	if m != nil {
		return m.CurrencySymbol
	}
	return ""
}

func (m *UpdateBalanceRequest) GetAvailable() float64 {
	if m != nil {
		return m.Available
	}
	return 0
}

func (m *UpdateBalanceRequest) GetLocked() float64 {
	if m != nil {
		return m.Locked
	}
	return 0
}

func (m *UpdateBalanceRequest) GetExchangeTotal() float64 {
	if m != nil {
		return m.ExchangeTotal
	}
	return 0
}

func (m *UpdateBalanceRequest) GetExchangeAvailable() float64 {
	if m != nil {
		return m.ExchangeAvailable
	}
	return 0
}

func (m *UpdateBalanceRequest) GetExchangeLocked() float64 {
	if m != nil {
		return m.ExchangeLocked
	}
	return 0
}

type ValidateBalanceRequest struct {
	AccountID      string  `protobuf:"bytes,1,opt,name=accountID" json:"accountID,omitempty"`
	CurrencySymbol string  `protobuf:"bytes,2,opt,name=currencySymbol" json:"currencySymbol,omitempty"`
	Available      float64 `protobuf:"fixed64,3,opt,name=available" json:"available,omitempty"`
}

func (m *ValidateBalanceRequest) Reset()                    { *m = ValidateBalanceRequest{} }
func (m *ValidateBalanceRequest) String() string            { return proto.CompactTextString(m) }
func (*ValidateBalanceRequest) ProtoMessage()               {}
func (*ValidateBalanceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ValidateBalanceRequest) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *ValidateBalanceRequest) GetCurrencySymbol() string {
	if m != nil {
		return m.CurrencySymbol
	}
	return ""
}

func (m *ValidateBalanceRequest) GetAvailable() float64 {
	if m != nil {
		return m.Available
	}
	return 0
}

// Responses
type Balance struct {
	UserID            string  `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	AccountID         string  `protobuf:"bytes,2,opt,name=accountID" json:"accountID,omitempty"`
	CurrencySymbol    string  `protobuf:"bytes,3,opt,name=currencySymbol" json:"currencySymbol,omitempty"`
	Available         float64 `protobuf:"fixed64,4,opt,name=available" json:"available,omitempty"`
	Locked            float64 `protobuf:"fixed64,5,opt,name=locked" json:"locked,omitempty"`
	ExchangeTotal     float64 `protobuf:"fixed64,6,opt,name=exchangeTotal" json:"exchangeTotal,omitempty"`
	ExchangeAvailable float64 `protobuf:"fixed64,7,opt,name=exchangeAvailable" json:"exchangeAvailable,omitempty"`
	ExchangeLocked    float64 `protobuf:"fixed64,8,opt,name=exchangeLocked" json:"exchangeLocked,omitempty"`
	CreatedOn         string  `protobuf:"bytes,9,opt,name=created_on,json=createdOn" json:"created_on,omitempty"`
	UpdatedOn         string  `protobuf:"bytes,10,opt,name=updated_on,json=updatedOn" json:"updated_on,omitempty"`
}

func (m *Balance) Reset()                    { *m = Balance{} }
func (m *Balance) String() string            { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()               {}
func (*Balance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Balance) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Balance) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *Balance) GetCurrencySymbol() string {
	if m != nil {
		return m.CurrencySymbol
	}
	return ""
}

func (m *Balance) GetAvailable() float64 {
	if m != nil {
		return m.Available
	}
	return 0
}

func (m *Balance) GetLocked() float64 {
	if m != nil {
		return m.Locked
	}
	return 0
}

func (m *Balance) GetExchangeTotal() float64 {
	if m != nil {
		return m.ExchangeTotal
	}
	return 0
}

func (m *Balance) GetExchangeAvailable() float64 {
	if m != nil {
		return m.ExchangeAvailable
	}
	return 0
}

func (m *Balance) GetExchangeLocked() float64 {
	if m != nil {
		return m.ExchangeLocked
	}
	return 0
}

func (m *Balance) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *Balance) GetUpdatedOn() string {
	if m != nil {
		return m.UpdatedOn
	}
	return ""
}

type BalanceData struct {
	Balance *Balance `protobuf:"bytes,1,opt,name=balance" json:"balance,omitempty"`
}

func (m *BalanceData) Reset()                    { *m = BalanceData{} }
func (m *BalanceData) String() string            { return proto.CompactTextString(m) }
func (*BalanceData) ProtoMessage()               {}
func (*BalanceData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *BalanceData) GetBalance() *Balance {
	if m != nil {
		return m.Balance
	}
	return nil
}

type BalanceResponse struct {
	Status  string       `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Message string       `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Data    *BalanceData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *BalanceResponse) Reset()                    { *m = BalanceResponse{} }
func (m *BalanceResponse) String() string            { return proto.CompactTextString(m) }
func (*BalanceResponse) ProtoMessage()               {}
func (*BalanceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *BalanceResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *BalanceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BalanceResponse) GetData() *BalanceData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ValidateBalanceResponse struct {
	Status  string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *ValidateBalanceResponse) Reset()                    { *m = ValidateBalanceResponse{} }
func (m *ValidateBalanceResponse) String() string            { return proto.CompactTextString(m) }
func (*ValidateBalanceResponse) ProtoMessage()               {}
func (*ValidateBalanceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ValidateBalanceResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ValidateBalanceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*NewBalanceRequest)(nil), "bal.NewBalanceRequest")
	proto.RegisterType((*BalanceRequest)(nil), "bal.BalanceRequest")
	proto.RegisterType((*UpdateBalanceRequest)(nil), "bal.UpdateBalanceRequest")
	proto.RegisterType((*ValidateBalanceRequest)(nil), "bal.ValidateBalanceRequest")
	proto.RegisterType((*Balance)(nil), "bal.Balance")
	proto.RegisterType((*BalanceData)(nil), "bal.BalanceData")
	proto.RegisterType((*BalanceResponse)(nil), "bal.BalanceResponse")
	proto.RegisterType((*ValidateBalanceResponse)(nil), "bal.ValidateBalanceResponse")
}

func init() {
	proto.RegisterFile("github.com/asciiu/gomo/account-service/proto/balance/balance.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0xd1, 0x6a, 0xd4, 0x40,
	0x14, 0x65, 0xb3, 0xdb, 0xc4, 0xbd, 0xab, 0xd5, 0x0e, 0x52, 0xf3, 0xa0, 0x50, 0x86, 0x52, 0xfa,
	0xa0, 0x09, 0x54, 0xfc, 0x00, 0x4b, 0x5f, 0x44, 0xb1, 0x10, 0xb5, 0xaf, 0x72, 0x33, 0xb9, 0xa4,
	0xc1, 0xc9, 0xcc, 0x9a, 0x99, 0x69, 0x2d, 0xf8, 0x0d, 0xfe, 0x9e, 0xbf, 0x23, 0x99, 0x4c, 0xb6,
	0xb6, 0x55, 0x5b, 0x04, 0xed, 0x53, 0xb8, 0xe7, 0x5c, 0xe6, 0xdc, 0x39, 0xe7, 0x66, 0x60, 0xbf,
	0x6e, 0xec, 0xb1, 0x2b, 0x33, 0xa1, 0xdb, 0x1c, 0x8d, 0x68, 0x1a, 0x97, 0xd7, 0xba, 0xd5, 0x39,
	0x0a, 0xa1, 0x9d, 0xb2, 0xcf, 0x0c, 0x75, 0x27, 0x8d, 0xa0, 0x7c, 0xd9, 0x69, 0xab, 0xf3, 0x12,
	0x25, 0x2a, 0x41, 0xe3, 0x37, 0xf3, 0x28, 0x9b, 0x96, 0x28, 0xf9, 0x29, 0x6c, 0xbc, 0xa5, 0xd3,
	0xfd, 0x81, 0x28, 0xe8, 0xb3, 0x23, 0x63, 0xd9, 0x63, 0x98, 0x87, 0x83, 0x5e, 0x1d, 0xa4, 0x93,
	0xad, 0xc9, 0xee, 0xbc, 0x38, 0x07, 0xd8, 0x0e, 0xac, 0x0b, 0xd7, 0x75, 0xa4, 0xc4, 0xd9, 0xbb,
	0xb3, 0xb6, 0xd4, 0x32, 0x8d, 0x7c, 0xcb, 0x25, 0xd4, 0x9f, 0x72, 0x82, 0x8d, 0xc4, 0x52, 0x52,
	0x3a, 0xdd, 0x9a, 0xec, 0x4e, 0x8a, 0x73, 0x80, 0x1f, 0xc1, 0xfa, 0xbf, 0x50, 0xe5, 0xdf, 0x22,
	0x78, 0xf8, 0x61, 0x59, 0xa1, 0xa5, 0xff, 0x7f, 0x29, 0xb6, 0x09, 0xb1, 0xd4, 0xe2, 0x13, 0x55,
	0xe9, 0xcc, 0x53, 0xa1, 0x62, 0xdb, 0x70, 0x8f, 0xbe, 0x88, 0x63, 0x54, 0x35, 0xbd, 0xd7, 0x16,
	0x65, 0xba, 0xe6, 0xe9, 0x8b, 0x20, 0x7b, 0x0a, 0x1b, 0x23, 0xf0, 0x72, 0xa5, 0x11, 0xfb, 0xce,
	0xab, 0x44, 0x3f, 0xf1, 0x08, 0xbe, 0x19, 0x34, 0x13, 0xdf, 0x7a, 0x09, 0xe5, 0x5f, 0x61, 0xf3,
	0x08, 0x65, 0x73, 0x3b, 0x8e, 0xf0, 0xef, 0x11, 0x24, 0x41, 0xb6, 0x77, 0xc7, 0x19, 0xea, 0x56,
	0x62, 0xa1, 0xba, 0x38, 0x47, 0x74, 0xfd, 0x1c, 0xd3, 0xeb, 0xe7, 0x98, 0xfd, 0x3e, 0x99, 0xb5,
	0x3f, 0x27, 0x13, 0xdf, 0x38, 0x99, 0xe4, 0xe6, 0xc9, 0xdc, 0xf9, 0x55, 0x32, 0xec, 0x09, 0x80,
	0xe8, 0x08, 0x2d, 0x55, 0x1f, 0xb5, 0x4a, 0xe7, 0xc3, 0xc5, 0x03, 0x72, 0xa8, 0x7a, 0xda, 0xf9,
	0x45, 0xf6, 0x34, 0x0c, 0x74, 0x40, 0x0e, 0x15, 0x7f, 0x01, 0x8b, 0x60, 0xec, 0x01, 0x5a, 0x64,
	0x3b, 0x90, 0x84, 0xdf, 0xdb, 0xbb, 0xbb, 0xd8, 0xbb, 0x9b, 0x95, 0x28, 0xb3, 0x31, 0xf2, 0x91,
	0xe4, 0x0d, 0xdc, 0x5f, 0xad, 0x81, 0x59, 0x6a, 0x65, 0xbc, 0x37, 0xc6, 0xa2, 0x75, 0x66, 0xcc,
	0x65, 0xa8, 0x58, 0x0a, 0x49, 0x4b, 0xc6, 0x60, 0x4d, 0x21, 0x95, 0xb1, 0x64, 0xdb, 0x30, 0xab,
	0xd0, 0xa2, 0x4f, 0x62, 0xb1, 0xf7, 0xe0, 0x67, 0xa5, 0x7e, 0x98, 0xc2, 0xb3, 0xfc, 0x35, 0x3c,
	0xba, 0xb2, 0x79, 0x7f, 0x2b, 0x59, 0xc6, 0xfe, 0xd1, 0x7a, 0xfe, 0x23, 0x00, 0x00, 0xff, 0xff,
	0x2a, 0xe6, 0x83, 0xe8, 0xfa, 0x04, 0x00, 0x00,
}
