// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/asciiu/gomo/plan-service/proto/trade/trade.proto

/*
Package trade is a generated protocol buffer package.

It is generated from these files:
	github.com/asciiu/gomo/plan-service/proto/trade/trade.proto

It has these top-level messages:
	Trade
*/
package trade

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Trade struct {
	TradeID                  string  `protobuf:"bytes,1,opt,name=tradeID" json:"tradeID,omitempty"`
	OrderID                  string  `protobuf:"bytes,2,opt,name=orderID" json:"orderID,omitempty"`
	InitialCurrencySymbol    string  `protobuf:"bytes,3,opt,name=initialCurrencySymbol" json:"initialCurrencySymbol,omitempty"`
	InitialCurrencyBalance   float64 `protobuf:"fixed64,4,opt,name=initialCurrencyBalance" json:"initialCurrencyBalance,omitempty"`
	InitialCurrencyTraded    float64 `protobuf:"fixed64,5,opt,name=initialCurrencyTraded" json:"initialCurrencyTraded,omitempty"`
	InitialCurrencyRemainder float64 `protobuf:"fixed64,6,opt,name=initialCurrencyRemainder" json:"initialCurrencyRemainder,omitempty"`
	InitialCurrencyPrice     float64 `protobuf:"fixed64,7,opt,name=initialCurrencyPrice" json:"initialCurrencyPrice,omitempty"`
	FinalCurrencySymbol      string  `protobuf:"bytes,8,opt,name=finalCurrencySymbol" json:"finalCurrencySymbol,omitempty"`
	FinalCurrencyBalance     float64 `protobuf:"fixed64,9,opt,name=finalCurrencyBalance" json:"finalCurrencyBalance,omitempty"`
	FeeCurrencySymbol        string  `protobuf:"bytes,10,opt,name=feeCurrencySymbol" json:"feeCurrencySymbol,omitempty"`
	FeeCurrencyAmount        float64 `protobuf:"fixed64,11,opt,name=feeCurrencyAmount" json:"feeCurrencyAmount,omitempty"`
	ExchangeTime             string  `protobuf:"bytes,12,opt,name=exchangeTime" json:"exchangeTime,omitempty"`
	Side                     string  `protobuf:"bytes,13,opt,name=side" json:"side,omitempty"`
	CreatedOn                string  `protobuf:"bytes,14,opt,name=createdOn" json:"createdOn,omitempty"`
	UpdatedOn                string  `protobuf:"bytes,15,opt,name=updatedOn" json:"updatedOn,omitempty"`
}

func (m *Trade) Reset()                    { *m = Trade{} }
func (m *Trade) String() string            { return proto.CompactTextString(m) }
func (*Trade) ProtoMessage()               {}
func (*Trade) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Trade) GetTradeID() string {
	if m != nil {
		return m.TradeID
	}
	return ""
}

func (m *Trade) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *Trade) GetInitialCurrencySymbol() string {
	if m != nil {
		return m.InitialCurrencySymbol
	}
	return ""
}

func (m *Trade) GetInitialCurrencyBalance() float64 {
	if m != nil {
		return m.InitialCurrencyBalance
	}
	return 0
}

func (m *Trade) GetInitialCurrencyTraded() float64 {
	if m != nil {
		return m.InitialCurrencyTraded
	}
	return 0
}

func (m *Trade) GetInitialCurrencyRemainder() float64 {
	if m != nil {
		return m.InitialCurrencyRemainder
	}
	return 0
}

func (m *Trade) GetInitialCurrencyPrice() float64 {
	if m != nil {
		return m.InitialCurrencyPrice
	}
	return 0
}

func (m *Trade) GetFinalCurrencySymbol() string {
	if m != nil {
		return m.FinalCurrencySymbol
	}
	return ""
}

func (m *Trade) GetFinalCurrencyBalance() float64 {
	if m != nil {
		return m.FinalCurrencyBalance
	}
	return 0
}

func (m *Trade) GetFeeCurrencySymbol() string {
	if m != nil {
		return m.FeeCurrencySymbol
	}
	return ""
}

func (m *Trade) GetFeeCurrencyAmount() float64 {
	if m != nil {
		return m.FeeCurrencyAmount
	}
	return 0
}

func (m *Trade) GetExchangeTime() string {
	if m != nil {
		return m.ExchangeTime
	}
	return ""
}

func (m *Trade) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *Trade) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *Trade) GetUpdatedOn() string {
	if m != nil {
		return m.UpdatedOn
	}
	return ""
}

func init() {
	proto.RegisterType((*Trade)(nil), "trade.Trade")
}

func init() {
	proto.RegisterFile("github.com/asciiu/gomo/plan-service/proto/trade/trade.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0xd2, 0xcd, 0x4e, 0xc2, 0x40,
	0x10, 0x07, 0xf0, 0x54, 0x29, 0xc8, 0x88, 0x1a, 0xd7, 0x8f, 0xcc, 0xc1, 0x03, 0xe1, 0xc4, 0x41,
	0xa9, 0x51, 0xe3, 0x41, 0x4f, 0x2a, 0x17, 0x4e, 0x1a, 0xe4, 0x05, 0x96, 0xdd, 0x01, 0x36, 0x69,
	0x77, 0xc9, 0xd2, 0x1a, 0x79, 0x00, 0xdf, 0xdb, 0x74, 0x0a, 0x1a, 0x4a, 0xb9, 0x90, 0x9d, 0xff,
	0x6f, 0x67, 0x87, 0x4c, 0x0a, 0xcf, 0x53, 0x93, 0xce, 0xb2, 0x71, 0x4f, 0xb9, 0x24, 0x92, 0x0b,
	0x65, 0x4c, 0x16, 0x4d, 0x5d, 0xe2, 0xa2, 0x79, 0x2c, 0xed, 0xcd, 0x82, 0xfc, 0x97, 0x51, 0x14,
	0xcd, 0xbd, 0x4b, 0x5d, 0x94, 0x7a, 0xa9, 0xa9, 0xf8, 0xed, 0x71, 0x22, 0x42, 0x2e, 0x3a, 0x3f,
	0x21, 0x84, 0xa3, 0xfc, 0x24, 0x10, 0x1a, 0x1c, 0x0d, 0xfa, 0x18, 0xb4, 0x83, 0x6e, 0x73, 0xb8,
	0x2e, 0x73, 0x71, 0x5e, 0x93, 0x1f, 0xf4, 0x71, 0xaf, 0x90, 0x55, 0x29, 0x1e, 0xe0, 0xc2, 0x58,
	0x93, 0x1a, 0x19, 0xbf, 0x65, 0xde, 0x93, 0x55, 0xcb, 0xcf, 0x65, 0x32, 0x76, 0x31, 0xee, 0xf3,
	0xbd, 0x6a, 0x14, 0x8f, 0x70, 0x59, 0x82, 0x57, 0x19, 0x4b, 0xab, 0x08, 0x6b, 0xed, 0xa0, 0x1b,
	0x0c, 0x77, 0x68, 0xc5, 0x34, 0xfe, 0xe7, 0x1a, 0x43, 0x6e, 0xab, 0x46, 0xf1, 0x04, 0x58, 0x82,
	0x21, 0x25, 0xd2, 0x58, 0x4d, 0x1e, 0xeb, 0xdc, 0xb8, 0xd3, 0xc5, 0x1d, 0x9c, 0x97, 0xec, 0xc3,
	0x1b, 0x45, 0xd8, 0xe0, 0xbe, 0x4a, 0x13, 0xb7, 0x70, 0x36, 0x31, 0x76, 0x6b, 0x23, 0x07, 0xbc,
	0x91, 0x2a, 0xca, 0xa7, 0x6c, 0xc4, 0xeb, 0x6d, 0x34, 0x8b, 0x29, 0x55, 0x26, 0xae, 0xe1, 0x74,
	0x42, 0x54, 0x9a, 0x01, 0x3c, 0x63, 0x1b, 0x4a, 0xb7, 0x5f, 0x12, 0x97, 0xd9, 0x14, 0x0f, 0xf9,
	0xf9, 0x6d, 0x10, 0x1d, 0x68, 0xd1, 0xb7, 0x9a, 0x49, 0x3b, 0xa5, 0x91, 0x49, 0x08, 0x5b, 0xfc,
	0xec, 0x46, 0x26, 0x04, 0xd4, 0x16, 0x46, 0x13, 0x1e, 0xb1, 0xf1, 0x59, 0x5c, 0x41, 0x53, 0x79,
	0x92, 0x29, 0xe9, 0x77, 0x8b, 0xc7, 0x0c, 0xff, 0x41, 0xae, 0xd9, 0x5c, 0xaf, 0xf4, 0xa4, 0xd0,
	0xbf, 0x60, 0x5c, 0xe7, 0xaf, 0xf2, 0xfe, 0x37, 0x00, 0x00, 0xff, 0xff, 0xce, 0x64, 0xf3, 0xa2,
	0xd4, 0x02, 0x00, 0x00,
}
