// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/order/order.proto

/*
Package order is a generated protocol buffer package.

It is generated from these files:
	proto/order/order.proto

It has these top-level messages:
	OrdersRequest
	TriggerRequest
	UpdateOrderRequest
	OrderRequest
	GetUserOrderRequest
	GetUserOrdersRequest
	RemoveOrderRequest
	Order
	Trigger
	UserOrderData
	UserOrdersData
	OrderResponse
	OrderListResponse
	OrdersPage
*/
package order

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Requests
type OrdersRequest struct {
	Orders []*OrderRequest `protobuf:"bytes,1,rep,name=orders" json:"orders"`
}

func (m *OrdersRequest) Reset()                    { *m = OrdersRequest{} }
func (m *OrdersRequest) String() string            { return proto.CompactTextString(m) }
func (*OrdersRequest) ProtoMessage()               {}
func (*OrdersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *OrdersRequest) GetOrders() []*OrderRequest {
	if m != nil {
		return m.Orders
	}
	return nil
}

type TriggerRequest struct {
	TriggerID         string   `protobuf:"bytes,1,opt,name=triggerID" json:"triggerID"`
	Name              string   `protobuf:"bytes,2,opt,name=name" json:"name"`
	Code              string   `protobuf:"bytes,3,opt,name=code" json:"code"`
	TriggerTemplateID string   `protobuf:"bytes,4,opt,name=triggerTemplateID" json:"triggerTemplateID"`
	Actions           []string `protobuf:"bytes,5,rep,name=actions" json:"actions"`
}

func (m *TriggerRequest) Reset()                    { *m = TriggerRequest{} }
func (m *TriggerRequest) String() string            { return proto.CompactTextString(m) }
func (*TriggerRequest) ProtoMessage()               {}
func (*TriggerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TriggerRequest) GetTriggerID() string {
	if m != nil {
		return m.TriggerID
	}
	return ""
}

func (m *TriggerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TriggerRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *TriggerRequest) GetTriggerTemplateID() string {
	if m != nil {
		return m.TriggerTemplateID
	}
	return ""
}

func (m *TriggerRequest) GetActions() []string {
	if m != nil {
		return m.Actions
	}
	return nil
}

type UpdateOrderRequest struct {
	OrderID         string            `protobuf:"bytes,1,opt,name=orderID" json:"orderID"`
	UserID          string            `protobuf:"bytes,2,opt,name=userID" json:"userID"`
	BasePercent     float64           `protobuf:"fixed64,3,opt,name=basePercent" json:"basePercent"`
	CurrencyPercent float64           `protobuf:"fixed64,4,opt,name=currencyPercent" json:"currencyPercent"`
	LimitPrice      float64           `protobuf:"fixed64,5,opt,name=limitPrice" json:"limitPrice"`
	Triggers        []*TriggerRequest `protobuf:"bytes,6,rep,name=triggers" json:"triggers"`
}

func (m *UpdateOrderRequest) Reset()                    { *m = UpdateOrderRequest{} }
func (m *UpdateOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateOrderRequest) ProtoMessage()               {}
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpdateOrderRequest) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *UpdateOrderRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdateOrderRequest) GetBasePercent() float64 {
	if m != nil {
		return m.BasePercent
	}
	return 0
}

func (m *UpdateOrderRequest) GetCurrencyPercent() float64 {
	if m != nil {
		return m.CurrencyPercent
	}
	return 0
}

func (m *UpdateOrderRequest) GetLimitPrice() float64 {
	if m != nil {
		return m.LimitPrice
	}
	return 0
}

func (m *UpdateOrderRequest) GetTriggers() []*TriggerRequest {
	if m != nil {
		return m.Triggers
	}
	return nil
}

type OrderRequest struct {
	PlanID          string            `protobuf:"bytes,1,opt,name=planID" json:"planID"`
	Side            string            `protobuf:"bytes,2,opt,name=side" json:"side"`
	OrderType       string            `protobuf:"bytes,3,opt,name=orderType" json:"orderType"`
	OrderTemplateID string            `protobuf:"bytes,4,opt,name=orderTemplateID" json:"orderTemplateID"`
	BasePercent     float64           `protobuf:"fixed64,5,opt,name=basePercent" json:"basePercent"`
	CurrencyPercent float64           `protobuf:"fixed64,6,opt,name=currencyPercent" json:"currencyPercent"`
	LimitPrice      float64           `protobuf:"fixed64,7,opt,name=limitPrice" json:"limitPrice"`
	Triggers        []*TriggerRequest `protobuf:"bytes,8,rep,name=triggers" json:"triggers"`
}

func (m *OrderRequest) Reset()                    { *m = OrderRequest{} }
func (m *OrderRequest) String() string            { return proto.CompactTextString(m) }
func (*OrderRequest) ProtoMessage()               {}
func (*OrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *OrderRequest) GetPlanID() string {
	if m != nil {
		return m.PlanID
	}
	return ""
}

func (m *OrderRequest) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *OrderRequest) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func (m *OrderRequest) GetOrderTemplateID() string {
	if m != nil {
		return m.OrderTemplateID
	}
	return ""
}

func (m *OrderRequest) GetBasePercent() float64 {
	if m != nil {
		return m.BasePercent
	}
	return 0
}

func (m *OrderRequest) GetCurrencyPercent() float64 {
	if m != nil {
		return m.CurrencyPercent
	}
	return 0
}

func (m *OrderRequest) GetLimitPrice() float64 {
	if m != nil {
		return m.LimitPrice
	}
	return 0
}

func (m *OrderRequest) GetTriggers() []*TriggerRequest {
	if m != nil {
		return m.Triggers
	}
	return nil
}

type GetUserOrderRequest struct {
	OrderID string `protobuf:"bytes,1,opt,name=orderID" json:"orderID"`
	UserID  string `protobuf:"bytes,2,opt,name=userID" json:"userID"`
}

func (m *GetUserOrderRequest) Reset()                    { *m = GetUserOrderRequest{} }
func (m *GetUserOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserOrderRequest) ProtoMessage()               {}
func (*GetUserOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetUserOrderRequest) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *GetUserOrderRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetUserOrdersRequest struct {
	UserID string `protobuf:"bytes,1,opt,name=userID" json:"userID"`
}

func (m *GetUserOrdersRequest) Reset()                    { *m = GetUserOrdersRequest{} }
func (m *GetUserOrdersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserOrdersRequest) ProtoMessage()               {}
func (*GetUserOrdersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetUserOrdersRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type RemoveOrderRequest struct {
	OrderID string `protobuf:"bytes,1,opt,name=orderID" json:"orderID"`
	UserID  string `protobuf:"bytes,2,opt,name=userID" json:"userID"`
}

func (m *RemoveOrderRequest) Reset()                    { *m = RemoveOrderRequest{} }
func (m *RemoveOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveOrderRequest) ProtoMessage()               {}
func (*RemoveOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RemoveOrderRequest) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *RemoveOrderRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type Order struct {
	OrderID         string     `protobuf:"bytes,1,opt,name=orderID" json:"orderID"`
	Side            string     `protobuf:"bytes,2,opt,name=side" json:"side"`
	OrderTemplateID string     `protobuf:"bytes,3,opt,name=orderTemplateID" json:"orderTemplateID"`
	OrderNumber     uint32     `protobuf:"varint,4,opt,name=orderNumber" json:"orderNumber"`
	OrderType       string     `protobuf:"bytes,5,opt,name=orderType" json:"orderType"`
	LimitPrice      float64    `protobuf:"fixed64,6,opt,name=limitPrice" json:"limitPrice"`
	BasePercent     float64    `protobuf:"fixed64,7,opt,name=basePercent" json:"basePercent"`
	CurrencyPercent float64    `protobuf:"fixed64,8,opt,name=currencyPercent" json:"currencyPercent"`
	Status          string     `protobuf:"bytes,9,opt,name=status" json:"status"`
	NextOrderID     string     `protobuf:"bytes,10,opt,name=nextOrderID" json:"nextOrderID"`
	Triggers        []*Trigger `protobuf:"bytes,11,rep,name=triggers" json:"triggers"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Order) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *Order) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *Order) GetOrderTemplateID() string {
	if m != nil {
		return m.OrderTemplateID
	}
	return ""
}

func (m *Order) GetOrderNumber() uint32 {
	if m != nil {
		return m.OrderNumber
	}
	return 0
}

func (m *Order) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func (m *Order) GetLimitPrice() float64 {
	if m != nil {
		return m.LimitPrice
	}
	return 0
}

func (m *Order) GetBasePercent() float64 {
	if m != nil {
		return m.BasePercent
	}
	return 0
}

func (m *Order) GetCurrencyPercent() float64 {
	if m != nil {
		return m.CurrencyPercent
	}
	return 0
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Order) GetNextOrderID() string {
	if m != nil {
		return m.NextOrderID
	}
	return ""
}

func (m *Order) GetTriggers() []*Trigger {
	if m != nil {
		return m.Triggers
	}
	return nil
}

type Trigger struct {
	TriggerID         string   `protobuf:"bytes,1,opt,name=triggerID" json:"triggerID"`
	OrderID           string   `protobuf:"bytes,2,opt,name=orderID" json:"orderID"`
	TriggerNumber     uint32   `protobuf:"varint,3,opt,name=triggerNumber" json:"triggerNumber"`
	TriggerTemplateID string   `protobuf:"bytes,4,opt,name=triggerTemplateID" json:"triggerTemplateID"`
	Name              string   `protobuf:"bytes,5,opt,name=name" json:"name"`
	Code              string   `protobuf:"bytes,6,opt,name=code" json:"code"`
	Triggered         bool     `protobuf:"varint,7,opt,name=triggered" json:"triggered"`
	Actions           []string `protobuf:"bytes,8,rep,name=actions" json:"actions"`
}

func (m *Trigger) Reset()                    { *m = Trigger{} }
func (m *Trigger) String() string            { return proto.CompactTextString(m) }
func (*Trigger) ProtoMessage()               {}
func (*Trigger) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Trigger) GetTriggerID() string {
	if m != nil {
		return m.TriggerID
	}
	return ""
}

func (m *Trigger) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *Trigger) GetTriggerNumber() uint32 {
	if m != nil {
		return m.TriggerNumber
	}
	return 0
}

func (m *Trigger) GetTriggerTemplateID() string {
	if m != nil {
		return m.TriggerTemplateID
	}
	return ""
}

func (m *Trigger) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Trigger) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Trigger) GetTriggered() bool {
	if m != nil {
		return m.Triggered
	}
	return false
}

func (m *Trigger) GetActions() []string {
	if m != nil {
		return m.Actions
	}
	return nil
}

type UserOrderData struct {
	Order *Order `protobuf:"bytes,1,opt,name=order" json:"order"`
}

func (m *UserOrderData) Reset()                    { *m = UserOrderData{} }
func (m *UserOrderData) String() string            { return proto.CompactTextString(m) }
func (*UserOrderData) ProtoMessage()               {}
func (*UserOrderData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UserOrderData) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type UserOrdersData struct {
	Orders []*Order `protobuf:"bytes,1,rep,name=orders" json:"orders"`
}

func (m *UserOrdersData) Reset()                    { *m = UserOrdersData{} }
func (m *UserOrdersData) String() string            { return proto.CompactTextString(m) }
func (*UserOrdersData) ProtoMessage()               {}
func (*UserOrdersData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *UserOrdersData) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type OrderResponse struct {
	Status  string         `protobuf:"bytes,1,opt,name=status" json:"status"`
	Message string         `protobuf:"bytes,2,opt,name=message" json:"message"`
	Data    *UserOrderData `protobuf:"bytes,3,opt,name=data" json:"data"`
}

func (m *OrderResponse) Reset()                    { *m = OrderResponse{} }
func (m *OrderResponse) String() string            { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()               {}
func (*OrderResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *OrderResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OrderResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *OrderResponse) GetData() *UserOrderData {
	if m != nil {
		return m.Data
	}
	return nil
}

type OrderListResponse struct {
	Status  string          `protobuf:"bytes,1,opt,name=status" json:"status"`
	Message string          `protobuf:"bytes,2,opt,name=message" json:"message"`
	Data    *UserOrdersData `protobuf:"bytes,3,opt,name=data" json:"data"`
}

func (m *OrderListResponse) Reset()                    { *m = OrderListResponse{} }
func (m *OrderListResponse) String() string            { return proto.CompactTextString(m) }
func (*OrderListResponse) ProtoMessage()               {}
func (*OrderListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *OrderListResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OrderListResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *OrderListResponse) GetData() *UserOrdersData {
	if m != nil {
		return m.Data
	}
	return nil
}

type OrdersPage struct {
	Page     uint32   `protobuf:"varint,1,opt,name=page" json:"page"`
	PageSize uint32   `protobuf:"varint,2,opt,name=pageSize" json:"pageSize"`
	Total    uint32   `protobuf:"varint,3,opt,name=total" json:"total"`
	Orders   []*Order `protobuf:"bytes,4,rep,name=orders" json:"orders"`
}

func (m *OrdersPage) Reset()                    { *m = OrdersPage{} }
func (m *OrdersPage) String() string            { return proto.CompactTextString(m) }
func (*OrdersPage) ProtoMessage()               {}
func (*OrdersPage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *OrdersPage) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *OrdersPage) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *OrdersPage) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *OrdersPage) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func init() {
	proto.RegisterType((*OrdersRequest)(nil), "OrdersRequest")
	proto.RegisterType((*TriggerRequest)(nil), "TriggerRequest")
	proto.RegisterType((*UpdateOrderRequest)(nil), "UpdateOrderRequest")
	proto.RegisterType((*OrderRequest)(nil), "OrderRequest")
	proto.RegisterType((*GetUserOrderRequest)(nil), "GetUserOrderRequest")
	proto.RegisterType((*GetUserOrdersRequest)(nil), "GetUserOrdersRequest")
	proto.RegisterType((*RemoveOrderRequest)(nil), "RemoveOrderRequest")
	proto.RegisterType((*Order)(nil), "Order")
	proto.RegisterType((*Trigger)(nil), "Trigger")
	proto.RegisterType((*UserOrderData)(nil), "UserOrderData")
	proto.RegisterType((*UserOrdersData)(nil), "UserOrdersData")
	proto.RegisterType((*OrderResponse)(nil), "OrderResponse")
	proto.RegisterType((*OrderListResponse)(nil), "OrderListResponse")
	proto.RegisterType((*OrdersPage)(nil), "OrdersPage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for OrderService service

type OrderServiceClient interface {
	AddOrders(ctx context.Context, in *OrdersRequest, opts ...client.CallOption) (*OrderListResponse, error)
	GetUserOrder(ctx context.Context, in *GetUserOrderRequest, opts ...client.CallOption) (*OrderResponse, error)
	GetUserOrders(ctx context.Context, in *GetUserOrdersRequest, opts ...client.CallOption) (*OrderListResponse, error)
	RemoveOrder(ctx context.Context, in *RemoveOrderRequest, opts ...client.CallOption) (*OrderResponse, error)
	UpdateOrder(ctx context.Context, in *UpdateOrderRequest, opts ...client.CallOption) (*OrderResponse, error)
}

type orderServiceClient struct {
	c           client.Client
	serviceName string
}

func NewOrderServiceClient(serviceName string, c client.Client) OrderServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "orderservice"
	}
	return &orderServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *orderServiceClient) AddOrders(ctx context.Context, in *OrdersRequest, opts ...client.CallOption) (*OrderListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "OrderService.AddOrders", in)
	out := new(OrderListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetUserOrder(ctx context.Context, in *GetUserOrderRequest, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.serviceName, "OrderService.GetUserOrder", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetUserOrders(ctx context.Context, in *GetUserOrdersRequest, opts ...client.CallOption) (*OrderListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "OrderService.GetUserOrders", in)
	out := new(OrderListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) RemoveOrder(ctx context.Context, in *RemoveOrderRequest, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.serviceName, "OrderService.RemoveOrder", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) UpdateOrder(ctx context.Context, in *UpdateOrderRequest, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.serviceName, "OrderService.UpdateOrder", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OrderService service

type OrderServiceHandler interface {
	AddOrders(context.Context, *OrdersRequest, *OrderListResponse) error
	GetUserOrder(context.Context, *GetUserOrderRequest, *OrderResponse) error
	GetUserOrders(context.Context, *GetUserOrdersRequest, *OrderListResponse) error
	RemoveOrder(context.Context, *RemoveOrderRequest, *OrderResponse) error
	UpdateOrder(context.Context, *UpdateOrderRequest, *OrderResponse) error
}

func RegisterOrderServiceHandler(s server.Server, hdlr OrderServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&OrderService{hdlr}, opts...))
}

type OrderService struct {
	OrderServiceHandler
}

func (h *OrderService) AddOrders(ctx context.Context, in *OrdersRequest, out *OrderListResponse) error {
	return h.OrderServiceHandler.AddOrders(ctx, in, out)
}

func (h *OrderService) GetUserOrder(ctx context.Context, in *GetUserOrderRequest, out *OrderResponse) error {
	return h.OrderServiceHandler.GetUserOrder(ctx, in, out)
}

func (h *OrderService) GetUserOrders(ctx context.Context, in *GetUserOrdersRequest, out *OrderListResponse) error {
	return h.OrderServiceHandler.GetUserOrders(ctx, in, out)
}

func (h *OrderService) RemoveOrder(ctx context.Context, in *RemoveOrderRequest, out *OrderResponse) error {
	return h.OrderServiceHandler.RemoveOrder(ctx, in, out)
}

func (h *OrderService) UpdateOrder(ctx context.Context, in *UpdateOrderRequest, out *OrderResponse) error {
	return h.OrderServiceHandler.UpdateOrder(ctx, in, out)
}

func init() { proto.RegisterFile("proto/order/order.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 746 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcd, 0x4e, 0xdb, 0x40,
	0x10, 0xc6, 0x49, 0xec, 0x24, 0x13, 0x12, 0xc4, 0x40, 0xa9, 0x85, 0x10, 0x8a, 0x5c, 0x2a, 0x45,
	0x6a, 0xeb, 0xb6, 0x29, 0xe2, 0xd4, 0x4b, 0x25, 0x54, 0x84, 0x54, 0x15, 0x64, 0xe0, 0x01, 0x4c,
	0xbc, 0x42, 0xae, 0x12, 0xdb, 0xf5, 0x6e, 0x50, 0xe9, 0xab, 0x54, 0xea, 0xa5, 0x0f, 0xd6, 0x07,
	0xe8, 0xb9, 0xf7, 0xca, 0xe3, 0xb5, 0xb3, 0xeb, 0x98, 0x9f, 0x8a, 0x0b, 0x78, 0xbe, 0x99, 0xf5,
	0xee, 0x7c, 0xdf, 0xf8, 0xdb, 0xc0, 0xd3, 0x24, 0x8d, 0x45, 0xfc, 0x3a, 0x4e, 0x03, 0x96, 0xe6,
	0x7f, 0x5d, 0x42, 0x9c, 0x03, 0xe8, 0x9f, 0x64, 0x21, 0xf7, 0xd8, 0xd7, 0x39, 0xe3, 0x02, 0x9f,
	0x83, 0x45, 0x79, 0x6e, 0x1b, 0xc3, 0xe6, 0xa8, 0x37, 0xee, 0xbb, 0x94, 0x97, 0x69, 0x4f, 0x26,
	0x9d, 0x9f, 0x06, 0x0c, 0xce, 0xd3, 0xf0, 0xea, 0xaa, 0x4c, 0xe1, 0x0e, 0x74, 0x45, 0x8e, 0x1c,
	0x1f, 0xda, 0xc6, 0xd0, 0x18, 0x75, 0xbd, 0x05, 0x80, 0x08, 0xad, 0xc8, 0x9f, 0x31, 0xbb, 0x41,
	0x09, 0x7a, 0xce, 0xb0, 0x49, 0x1c, 0x30, 0xbb, 0x99, 0x63, 0xd9, 0x33, 0xbe, 0x84, 0x75, 0xb9,
	0xe8, 0x9c, 0xcd, 0x92, 0xa9, 0x2f, 0xd8, 0xf1, 0xa1, 0xdd, 0xa2, 0x82, 0xe5, 0x04, 0xda, 0xd0,
	0xf6, 0x27, 0x22, 0x8c, 0x23, 0x6e, 0x9b, 0xc3, 0xe6, 0xa8, 0xeb, 0x15, 0xa1, 0xf3, 0xdb, 0x00,
	0xbc, 0x48, 0x02, 0x5f, 0x30, 0xf5, 0xfc, 0xd9, 0x02, 0xea, 0xa0, 0x3c, 0x62, 0x11, 0xe2, 0x16,
	0x58, 0x73, 0x4e, 0x89, 0xfc, 0x88, 0x32, 0xc2, 0x21, 0xf4, 0x2e, 0x7d, 0xce, 0x4e, 0x59, 0x3a,
	0x61, 0x91, 0xa0, 0xb3, 0x1a, 0x9e, 0x0a, 0xe1, 0x08, 0xd6, 0x26, 0xf3, 0x34, 0x65, 0xd1, 0xe4,
	0xa6, 0xa8, 0x6a, 0x51, 0x55, 0x15, 0xc6, 0x5d, 0x80, 0x69, 0x38, 0x0b, 0xc5, 0x69, 0x1a, 0x4e,
	0x98, 0x6d, 0x52, 0x91, 0x82, 0xe0, 0x0b, 0xe8, 0xc8, 0x1e, 0xb9, 0x6d, 0x11, 0xfd, 0x6b, 0xae,
	0xce, 0xb2, 0x57, 0x16, 0x38, 0x3f, 0x1a, 0xb0, 0xaa, 0xf5, 0xb6, 0x05, 0x56, 0x32, 0xf5, 0xa3,
	0xb2, 0x35, 0x19, 0x65, 0x34, 0xf3, 0x30, 0x28, 0xa9, 0xcf, 0x9e, 0x33, 0xb1, 0xa8, 0xf1, 0xf3,
	0x9b, 0xa4, 0xe0, 0x7f, 0x01, 0x64, 0x1d, 0xe5, 0x41, 0x55, 0x82, 0x2a, 0x5c, 0x65, 0xc7, 0x7c,
	0x10, 0x3b, 0xd6, 0x43, 0xd8, 0x69, 0xdf, 0xc9, 0x4e, 0xe7, 0x3e, 0x76, 0x8e, 0x60, 0xe3, 0x88,
	0x89, 0x0b, 0xce, 0xd2, 0xc7, 0xe9, 0xef, 0xb8, 0xb0, 0xa9, 0xbe, 0x88, 0x2b, 0x6c, 0xcb, 0x7a,
	0x43, 0xab, 0xff, 0x08, 0xe8, 0xb1, 0x59, 0x7c, 0xfd, 0xc8, 0xb9, 0x73, 0xfe, 0x34, 0xc0, 0xa4,
	0x57, 0xdc, 0xb1, 0xb6, 0x4e, 0xd9, 0x1a, 0xed, 0x9a, 0xb7, 0x6a, 0x47, 0xd0, 0xe7, 0xf9, 0xec,
	0x92, 0xa5, 0xa4, 0x70, 0xdf, 0x53, 0x21, 0x7d, 0x4a, 0xcc, 0xea, 0x94, 0xe8, 0x7a, 0x59, 0x4b,
	0x7a, 0x55, 0x66, 0xa3, 0xfd, 0xa0, 0xd9, 0xe8, 0xd4, 0xcf, 0xc6, 0x16, 0x58, 0x5c, 0xf8, 0x62,
	0xce, 0xed, 0x6e, 0xce, 0x52, 0x1e, 0x65, 0x7b, 0x44, 0xec, 0x9b, 0x38, 0x91, 0xfc, 0x00, 0x25,
	0x55, 0x08, 0xf7, 0x94, 0xa9, 0xe9, 0xd1, 0xd4, 0x74, 0xca, 0xa9, 0x59, 0x8c, 0xcb, 0x5f, 0x03,
	0xda, 0x12, 0xbd, 0xc7, 0xc8, 0x14, 0x35, 0x1a, 0xba, 0x1a, 0x7b, 0xd0, 0x97, 0x65, 0x92, 0xd1,
	0x26, 0x31, 0xaa, 0x83, 0xff, 0x69, 0x70, 0x85, 0x6d, 0x9a, 0x35, 0xb6, 0x69, 0x29, 0xb6, 0xb9,
	0x38, 0x33, 0x0b, 0x88, 0xe9, 0x8e, 0xb7, 0x00, 0x54, 0x9b, 0xec, 0xe8, 0x36, 0xf9, 0x0a, 0xfa,
	0xe5, 0x68, 0x1f, 0xfa, 0xc2, 0xc7, 0x1d, 0x30, 0xa9, 0x1f, 0x6a, 0xbc, 0x37, 0xb6, 0xa4, 0xfd,
	0xe7, 0xa0, 0xf3, 0x06, 0x06, 0x8b, 0x2f, 0x81, 0xea, 0x77, 0x2b, 0xf7, 0x45, 0xb1, 0xa0, 0xb8,
	0x28, 0x98, 0xbc, 0x60, 0x3c, 0xc6, 0x93, 0x38, 0xe2, 0x4c, 0x51, 0xd2, 0xd0, 0x94, 0xb4, 0xa1,
	0x3d, 0x63, 0x9c, 0xfb, 0x57, 0xc5, 0x38, 0x17, 0x21, 0x3a, 0xd0, 0x0a, 0x7c, 0xe1, 0x13, 0x9d,
	0xbd, 0xf1, 0xc0, 0xd5, 0x0e, 0xec, 0x51, 0xce, 0xf9, 0x02, 0xeb, 0x04, 0x7d, 0x0a, 0xb9, 0x78,
	0xc4, 0x56, 0xcf, 0xb4, 0xad, 0xd6, 0x5c, 0xbd, 0x59, 0xb9, 0x57, 0x0a, 0x90, 0x63, 0xa7, 0xd9,
	0x12, 0x84, 0x56, 0x92, 0xbd, 0xc9, 0x20, 0xb1, 0xe9, 0x19, 0xb7, 0xa1, 0x93, 0xfd, 0x3f, 0x0b,
	0xbf, 0xe7, 0x3b, 0xf4, 0xbd, 0x32, 0xc6, 0x4d, 0x30, 0x45, 0x2c, 0xfc, 0xa9, 0x9c, 0x8e, 0x3c,
	0x50, 0x68, 0x6c, 0xd5, 0xd1, 0x38, 0xfe, 0x55, 0x98, 0xfd, 0x19, 0x4b, 0xaf, 0xb3, 0x8f, 0xeb,
	0x2d, 0x74, 0x3f, 0x04, 0x41, 0x7e, 0x0e, 0x1c, 0xb8, 0x9a, 0x37, 0x6d, 0xa3, 0xbb, 0x44, 0x86,
	0xb3, 0x82, 0x07, 0xb0, 0xaa, 0x3a, 0x19, 0x6e, 0xba, 0x35, 0x0e, 0xb9, 0x3d, 0x70, 0x35, 0xbd,
	0x9c, 0x15, 0x7c, 0x0f, 0x7d, 0xcd, 0x01, 0xf1, 0x89, 0x5b, 0xe7, 0x88, 0xb7, 0xec, 0xba, 0x0f,
	0x3d, 0xc5, 0x0f, 0x71, 0xc3, 0x5d, 0x76, 0xc7, 0x9a, 0x3d, 0xf7, 0xa1, 0xa7, 0xdc, 0xde, 0xb8,
	0xe1, 0x2e, 0xdf, 0xe5, 0xcb, 0xab, 0x2e, 0x2d, 0xfa, 0x51, 0xf3, 0xee, 0x5f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xa8, 0x13, 0x0e, 0xf9, 0xef, 0x08, 0x00, 0x00,
}
