// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/order/order.proto

/*
Package go_micro_srv_order is a generated protocol buffer package.

It is generated from these files:
	proto/order/order.proto

It has these top-level messages:
	OrderRequest
	GetUserOrderRequest
	GetUserOrdersRequest
	RemoveOrderRequest
	OrderStatusRequest
	Order
	UserOrderData
	UserOrdersData
	OrderResponse
	OrderListResponse
*/
package go_micro_srv_order

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Requests
type OrderRequest struct {
	OrderId          string  `protobuf:"bytes,1,opt,name=orderId" json:"orderId,omitempty"`
	UserId           string  `protobuf:"bytes,2,opt,name=userId" json:"userId,omitempty"`
	ApiKeyId         string  `protobuf:"bytes,3,opt,name=apiKeyId" json:"apiKeyId,omitempty"`
	Exchange         string  `protobuf:"bytes,4,opt,name=exchange" json:"exchange,omitempty"`
	MarketName       string  `protobuf:"bytes,5,opt,name=marketName" json:"marketName,omitempty"`
	Side             string  `protobuf:"bytes,6,opt,name=side" json:"side,omitempty"`
	OrderType        string  `protobuf:"bytes,7,opt,name=orderType" json:"orderType,omitempty"`
	BaseQuantity     float64 `protobuf:"fixed64,8,opt,name=baseQuantity" json:"baseQuantity,omitempty"`
	CurrencyQuantity float64 `protobuf:"fixed64,9,opt,name=currencyQuantity" json:"currencyQuantity,omitempty"`
	Conditions       string  `protobuf:"bytes,10,opt,name=conditions" json:"conditions,omitempty"`
}

func (m *OrderRequest) Reset()                    { *m = OrderRequest{} }
func (m *OrderRequest) String() string            { return proto.CompactTextString(m) }
func (*OrderRequest) ProtoMessage()               {}
func (*OrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *OrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *OrderRequest) GetApiKeyId() string {
	if m != nil {
		return m.ApiKeyId
	}
	return ""
}

func (m *OrderRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *OrderRequest) GetMarketName() string {
	if m != nil {
		return m.MarketName
	}
	return ""
}

func (m *OrderRequest) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *OrderRequest) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func (m *OrderRequest) GetBaseQuantity() float64 {
	if m != nil {
		return m.BaseQuantity
	}
	return 0
}

func (m *OrderRequest) GetCurrencyQuantity() float64 {
	if m != nil {
		return m.CurrencyQuantity
	}
	return 0
}

func (m *OrderRequest) GetConditions() string {
	if m != nil {
		return m.Conditions
	}
	return ""
}

type GetUserOrderRequest struct {
	OrderId string `protobuf:"bytes,1,opt,name=orderId" json:"orderId,omitempty"`
	UserId  string `protobuf:"bytes,2,opt,name=userId" json:"userId,omitempty"`
}

func (m *GetUserOrderRequest) Reset()                    { *m = GetUserOrderRequest{} }
func (m *GetUserOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserOrderRequest) ProtoMessage()               {}
func (*GetUserOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetUserOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *GetUserOrderRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetUserOrdersRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
}

func (m *GetUserOrdersRequest) Reset()                    { *m = GetUserOrdersRequest{} }
func (m *GetUserOrdersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserOrdersRequest) ProtoMessage()               {}
func (*GetUserOrdersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetUserOrdersRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type RemoveOrderRequest struct {
	OrderId string `protobuf:"bytes,1,opt,name=orderId" json:"orderId,omitempty"`
	UserId  string `protobuf:"bytes,2,opt,name=userId" json:"userId,omitempty"`
}

func (m *RemoveOrderRequest) Reset()                    { *m = RemoveOrderRequest{} }
func (m *RemoveOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveOrderRequest) ProtoMessage()               {}
func (*RemoveOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RemoveOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *RemoveOrderRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type OrderStatusRequest struct {
	OrderId string `protobuf:"bytes,1,opt,name=orderId" json:"orderId,omitempty"`
	Status  string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *OrderStatusRequest) Reset()                    { *m = OrderStatusRequest{} }
func (m *OrderStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*OrderStatusRequest) ProtoMessage()               {}
func (*OrderStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *OrderStatusRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderStatusRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// Responses
type Order struct {
	OrderId               string  `protobuf:"bytes,1,opt,name=orderId" json:"orderId,omitempty"`
	UserId                string  `protobuf:"bytes,2,opt,name=userId" json:"userId,omitempty"`
	ApiKeyId              string  `protobuf:"bytes,3,opt,name=apiKeyId" json:"apiKeyId,omitempty"`
	Exchange              string  `protobuf:"bytes,4,opt,name=exchange" json:"exchange,omitempty"`
	ExchangeOrderId       string  `protobuf:"bytes,5,opt,name=exchangeOrderId" json:"exchangeOrderId,omitempty"`
	ExchangeMarketName    string  `protobuf:"bytes,6,opt,name=exchangeMarketName" json:"exchangeMarketName,omitempty"`
	MarketName            string  `protobuf:"bytes,7,opt,name=marketName" json:"marketName,omitempty"`
	Side                  string  `protobuf:"bytes,8,opt,name=side" json:"side,omitempty"`
	OrderType             string  `protobuf:"bytes,9,opt,name=orderType" json:"orderType,omitempty"`
	BaseQuantity          float64 `protobuf:"fixed64,10,opt,name=baseQuantity" json:"baseQuantity,omitempty"`
	BaseQuantityRemainder float64 `protobuf:"fixed64,11,opt,name=baseQuantityRemainder" json:"baseQuantityRemainder,omitempty"`
	Status                string  `protobuf:"bytes,12,opt,name=status" json:"status,omitempty"`
	Conditions            string  `protobuf:"bytes,13,opt,name=conditions" json:"conditions,omitempty"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Order) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *Order) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Order) GetApiKeyId() string {
	if m != nil {
		return m.ApiKeyId
	}
	return ""
}

func (m *Order) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *Order) GetExchangeOrderId() string {
	if m != nil {
		return m.ExchangeOrderId
	}
	return ""
}

func (m *Order) GetExchangeMarketName() string {
	if m != nil {
		return m.ExchangeMarketName
	}
	return ""
}

func (m *Order) GetMarketName() string {
	if m != nil {
		return m.MarketName
	}
	return ""
}

func (m *Order) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *Order) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func (m *Order) GetBaseQuantity() float64 {
	if m != nil {
		return m.BaseQuantity
	}
	return 0
}

func (m *Order) GetBaseQuantityRemainder() float64 {
	if m != nil {
		return m.BaseQuantityRemainder
	}
	return 0
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Order) GetConditions() string {
	if m != nil {
		return m.Conditions
	}
	return ""
}

type UserOrderData struct {
	Order *Order `protobuf:"bytes,1,opt,name=order" json:"order,omitempty"`
}

func (m *UserOrderData) Reset()                    { *m = UserOrderData{} }
func (m *UserOrderData) String() string            { return proto.CompactTextString(m) }
func (*UserOrderData) ProtoMessage()               {}
func (*UserOrderData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UserOrderData) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type UserOrdersData struct {
	Orders []*Order `protobuf:"bytes,1,rep,name=orders" json:"orders,omitempty"`
}

func (m *UserOrdersData) Reset()                    { *m = UserOrdersData{} }
func (m *UserOrdersData) String() string            { return proto.CompactTextString(m) }
func (*UserOrdersData) ProtoMessage()               {}
func (*UserOrdersData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UserOrdersData) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type OrderResponse struct {
	Status  string         `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Message string         `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Data    *UserOrderData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *OrderResponse) Reset()                    { *m = OrderResponse{} }
func (m *OrderResponse) String() string            { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()               {}
func (*OrderResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *OrderResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OrderResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *OrderResponse) GetData() *UserOrderData {
	if m != nil {
		return m.Data
	}
	return nil
}

type OrderListResponse struct {
	Status  string          `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Message string          `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Data    *UserOrdersData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *OrderListResponse) Reset()                    { *m = OrderListResponse{} }
func (m *OrderListResponse) String() string            { return proto.CompactTextString(m) }
func (*OrderListResponse) ProtoMessage()               {}
func (*OrderListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *OrderListResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OrderListResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *OrderListResponse) GetData() *UserOrdersData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*OrderRequest)(nil), "go.micro.srv.order.OrderRequest")
	proto.RegisterType((*GetUserOrderRequest)(nil), "go.micro.srv.order.GetUserOrderRequest")
	proto.RegisterType((*GetUserOrdersRequest)(nil), "go.micro.srv.order.GetUserOrdersRequest")
	proto.RegisterType((*RemoveOrderRequest)(nil), "go.micro.srv.order.RemoveOrderRequest")
	proto.RegisterType((*OrderStatusRequest)(nil), "go.micro.srv.order.OrderStatusRequest")
	proto.RegisterType((*Order)(nil), "go.micro.srv.order.Order")
	proto.RegisterType((*UserOrderData)(nil), "go.micro.srv.order.UserOrderData")
	proto.RegisterType((*UserOrdersData)(nil), "go.micro.srv.order.UserOrdersData")
	proto.RegisterType((*OrderResponse)(nil), "go.micro.srv.order.OrderResponse")
	proto.RegisterType((*OrderListResponse)(nil), "go.micro.srv.order.OrderListResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for OrderService service

type OrderServiceClient interface {
	AddOrder(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*OrderResponse, error)
	GetUserOrder(ctx context.Context, in *GetUserOrderRequest, opts ...client.CallOption) (*OrderResponse, error)
	GetUserOrders(ctx context.Context, in *GetUserOrdersRequest, opts ...client.CallOption) (*OrderListResponse, error)
	RemoveOrder(ctx context.Context, in *RemoveOrderRequest, opts ...client.CallOption) (*OrderResponse, error)
	UpdateOrder(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*OrderResponse, error)
	UpdateOrderStatus(ctx context.Context, in *OrderStatusRequest, opts ...client.CallOption) (*OrderResponse, error)
}

type orderServiceClient struct {
	c           client.Client
	serviceName string
}

func NewOrderServiceClient(serviceName string, c client.Client) OrderServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.order"
	}
	return &orderServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *orderServiceClient) AddOrder(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.serviceName, "OrderService.AddOrder", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetUserOrder(ctx context.Context, in *GetUserOrderRequest, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.serviceName, "OrderService.GetUserOrder", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetUserOrders(ctx context.Context, in *GetUserOrdersRequest, opts ...client.CallOption) (*OrderListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "OrderService.GetUserOrders", in)
	out := new(OrderListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) RemoveOrder(ctx context.Context, in *RemoveOrderRequest, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.serviceName, "OrderService.RemoveOrder", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) UpdateOrder(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.serviceName, "OrderService.UpdateOrder", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) UpdateOrderStatus(ctx context.Context, in *OrderStatusRequest, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.serviceName, "OrderService.UpdateOrderStatus", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OrderService service

type OrderServiceHandler interface {
	AddOrder(context.Context, *OrderRequest, *OrderResponse) error
	GetUserOrder(context.Context, *GetUserOrderRequest, *OrderResponse) error
	GetUserOrders(context.Context, *GetUserOrdersRequest, *OrderListResponse) error
	RemoveOrder(context.Context, *RemoveOrderRequest, *OrderResponse) error
	UpdateOrder(context.Context, *OrderRequest, *OrderResponse) error
	UpdateOrderStatus(context.Context, *OrderStatusRequest, *OrderResponse) error
}

func RegisterOrderServiceHandler(s server.Server, hdlr OrderServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&OrderService{hdlr}, opts...))
}

type OrderService struct {
	OrderServiceHandler
}

func (h *OrderService) AddOrder(ctx context.Context, in *OrderRequest, out *OrderResponse) error {
	return h.OrderServiceHandler.AddOrder(ctx, in, out)
}

func (h *OrderService) GetUserOrder(ctx context.Context, in *GetUserOrderRequest, out *OrderResponse) error {
	return h.OrderServiceHandler.GetUserOrder(ctx, in, out)
}

func (h *OrderService) GetUserOrders(ctx context.Context, in *GetUserOrdersRequest, out *OrderListResponse) error {
	return h.OrderServiceHandler.GetUserOrders(ctx, in, out)
}

func (h *OrderService) RemoveOrder(ctx context.Context, in *RemoveOrderRequest, out *OrderResponse) error {
	return h.OrderServiceHandler.RemoveOrder(ctx, in, out)
}

func (h *OrderService) UpdateOrder(ctx context.Context, in *OrderRequest, out *OrderResponse) error {
	return h.OrderServiceHandler.UpdateOrder(ctx, in, out)
}

func (h *OrderService) UpdateOrderStatus(ctx context.Context, in *OrderStatusRequest, out *OrderResponse) error {
	return h.OrderServiceHandler.UpdateOrderStatus(ctx, in, out)
}

func init() { proto.RegisterFile("proto/order/order.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 598 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0x4b, 0x6f, 0xd3, 0x40,
	0x10, 0xae, 0x9b, 0xf7, 0x24, 0x01, 0xba, 0xbc, 0x96, 0x08, 0xa1, 0xd4, 0x12, 0x10, 0x71, 0x70,
	0x45, 0x78, 0x9c, 0x41, 0xa0, 0x56, 0x15, 0x8f, 0xaa, 0x6e, 0x7b, 0x41, 0x1c, 0xd8, 0xd8, 0xa3,
	0x60, 0x21, 0xdb, 0xc1, 0xbb, 0x89, 0x9a, 0x03, 0xbf, 0x89, 0x23, 0x12, 0xbf, 0x0e, 0x65, 0xd6,
	0x8e, 0xed, 0xc4, 0x49, 0x23, 0x05, 0xf5, 0x12, 0xed, 0xcc, 0x37, 0xfe, 0x66, 0x76, 0xf7, 0xdb,
	0x2f, 0x70, 0x7f, 0x14, 0x85, 0x2a, 0x3c, 0x08, 0x23, 0x17, 0x23, 0xfd, 0x6b, 0x51, 0x86, 0xb1,
	0x61, 0x68, 0xf9, 0x9e, 0x13, 0x85, 0x96, 0x8c, 0x26, 0x16, 0x21, 0xe6, 0xdf, 0x5d, 0x68, 0x9d,
	0xcc, 0x56, 0x36, 0xfe, 0x1c, 0xa3, 0x54, 0x8c, 0x43, 0x8d, 0x90, 0x63, 0x97, 0x1b, 0x5d, 0xa3,
	0xd7, 0xb0, 0x93, 0x90, 0xdd, 0x83, 0xea, 0x58, 0x12, 0xb0, 0x4b, 0x40, 0x1c, 0xb1, 0x0e, 0xd4,
	0xc5, 0xc8, 0xfb, 0x80, 0xd3, 0x63, 0x97, 0x97, 0x08, 0x99, 0xc7, 0x33, 0x0c, 0x2f, 0x9d, 0xef,
	0x22, 0x18, 0x22, 0x2f, 0x6b, 0x2c, 0x89, 0xd9, 0x23, 0x00, 0x5f, 0x44, 0x3f, 0x50, 0x7d, 0x16,
	0x3e, 0xf2, 0x0a, 0xa1, 0x99, 0x0c, 0x63, 0x50, 0x96, 0x9e, 0x8b, 0xbc, 0x4a, 0x08, 0xad, 0xd9,
	0x43, 0x68, 0xd0, 0x38, 0xe7, 0xd3, 0x11, 0xf2, 0x1a, 0x01, 0x69, 0x82, 0x99, 0xd0, 0x1a, 0x08,
	0x89, 0xa7, 0x63, 0x11, 0x28, 0x4f, 0x4d, 0x79, 0xbd, 0x6b, 0xf4, 0x0c, 0x3b, 0x97, 0x63, 0xcf,
	0xe0, 0x96, 0x33, 0x8e, 0x22, 0x0c, 0x9c, 0xe9, 0xbc, 0xae, 0x41, 0x75, 0x4b, 0xf9, 0xd9, 0x84,
	0x4e, 0x18, 0xb8, 0x9e, 0xf2, 0xc2, 0x40, 0x72, 0xd0, 0x13, 0xa6, 0x19, 0xf3, 0x08, 0x6e, 0x1f,
	0xa1, 0xba, 0x90, 0x18, 0x6d, 0x77, 0x84, 0xa6, 0x05, 0x77, 0xb2, 0x44, 0x32, 0x61, 0x4a, 0xeb,
	0x8d, 0x5c, 0xfd, 0x21, 0x30, 0x1b, 0xfd, 0x70, 0x82, 0x5b, 0xf6, 0x3d, 0x04, 0x46, 0x0c, 0x67,
	0x4a, 0xa8, 0xb1, 0xdc, 0x88, 0x47, 0x52, 0x69, 0xc2, 0xa3, 0x23, 0xf3, 0x77, 0x09, 0x2a, 0x44,
	0x74, 0x8d, 0xf2, 0xe9, 0xc1, 0xcd, 0x64, 0x7d, 0x12, 0x77, 0xd4, 0x1a, 0x5a, 0x4c, 0x33, 0x0b,
	0x58, 0x92, 0xfa, 0x94, 0x0a, 0x4e, 0xcb, 0xaa, 0x00, 0x59, 0x10, 0x66, 0x6d, 0xa5, 0x30, 0xeb,
	0xab, 0x84, 0xd9, 0xb8, 0x4a, 0x98, 0x50, 0x20, 0xcc, 0x97, 0x70, 0x37, 0x1b, 0xdb, 0xe8, 0x0b,
	0x2f, 0x70, 0x31, 0xe2, 0x4d, 0x2a, 0x2e, 0x06, 0x33, 0x37, 0xd2, 0xca, 0xde, 0xc8, 0x82, 0x74,
	0xdb, 0x4b, 0xd2, 0x7d, 0x03, 0xed, 0xb9, 0xdc, 0xde, 0x0b, 0x25, 0xd8, 0x01, 0x54, 0x68, 0x5e,
	0xba, 0xb6, 0x66, 0xff, 0x81, 0xb5, 0x6c, 0x16, 0x96, 0x56, 0x9b, 0xae, 0x33, 0xdf, 0xc1, 0x8d,
	0x54, 0xb0, 0x44, 0xf1, 0x1c, 0xaa, 0x04, 0x49, 0x6e, 0x74, 0x4b, 0xeb, 0x39, 0xe2, 0x42, 0xf3,
	0x12, 0xda, 0xb1, 0x84, 0xe5, 0x28, 0x0c, 0x24, 0x66, 0xf6, 0x63, 0xe4, 0xf6, 0xc3, 0xa1, 0xe6,
	0xa3, 0x94, 0x62, 0x88, 0xb1, 0x7c, 0x92, 0x90, 0xbd, 0x82, 0xb2, 0x2b, 0x94, 0x20, 0xed, 0x34,
	0xfb, 0xfb, 0x45, 0x3d, 0x73, 0x3b, 0xb5, 0xa9, 0xdc, 0xfc, 0x05, 0x7b, 0x94, 0xfa, 0xe8, 0x49,
	0xb5, 0x45, 0xf7, 0xd7, 0xb9, 0xee, 0xe6, 0xda, 0xee, 0x32, 0x6d, 0xdf, 0xff, 0x53, 0x8e, 0x7d,
	0xf7, 0x0c, 0xa3, 0x89, 0xe7, 0x20, 0x3b, 0x85, 0xfa, 0x5b, 0xd7, 0xd5, 0x8f, 0xa8, 0xbb, 0xfa,
	0xe0, 0xf4, 0x13, 0xed, 0xec, 0xaf, 0xa9, 0xd0, 0x7b, 0x31, 0x77, 0xd8, 0x57, 0x68, 0x65, 0x5d,
	0x85, 0x3d, 0x2d, 0xfa, 0xa8, 0xc0, 0xc0, 0x36, 0x63, 0x1f, 0x40, 0x3b, 0xe7, 0x59, 0xac, 0x77,
	0x15, 0x7d, 0x62, 0x30, 0x9d, 0xc7, 0x2b, 0xf9, 0xb3, 0xb7, 0x61, 0xee, 0xb0, 0x2f, 0xd0, 0xcc,
	0xf8, 0x1c, 0x7b, 0x52, 0xf4, 0xdd, 0xb2, 0x11, 0x6e, 0x36, 0xff, 0x39, 0x34, 0x2f, 0x46, 0xae,
	0x50, 0xf8, 0x5f, 0xcf, 0xfc, 0x1b, 0xec, 0x65, 0x58, 0xb5, 0xaf, 0x16, 0xcf, 0xbd, 0x6c, 0xbc,
	0x1b, 0x75, 0x18, 0x54, 0xe9, 0xcf, 0xfc, 0xc5, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xf8,
	0x39, 0x9f, 0xe7, 0x07, 0x00, 0x00,
}
