// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/asciiu/gomo/plan-service/proto/plan/plan.proto

/*
Package plan is a generated protocol buffer package.

It is generated from these files:
	github.com/asciiu/gomo/plan-service/proto/plan/plan.proto

It has these top-level messages:
	PlanRequest
	GetUserPlanRequest
	GetUserPlansRequest
	DeletePlanRequest
	UpdatePlanRequest
	Plan
	PlanWithPagedOrders
	PlanData
	PlanResponse
	PlanWithPagedOrdersResponse
	PlansPageResponse
	PlansPage
*/
package plan

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import order "github.com/asciiu/gomo/order-service/proto/order"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Requests
type PlanRequest struct {
	PlanID          string                `protobuf:"bytes,1,opt,name=planID" json:"planID"`
	UserID          string                `protobuf:"bytes,2,opt,name=userID" json:"userID"`
	KeyID           string                `protobuf:"bytes,3,opt,name=keyID" json:"keyID"`
	PlanTemplateID  string                `protobuf:"bytes,4,opt,name=planTemplateID" json:"planTemplateID"`
	Exchange        string                `protobuf:"bytes,5,opt,name=exchange" json:"exchange"`
	MarketName      string                `protobuf:"bytes,6,opt,name=marketName" json:"marketName"`
	BaseBalance     float64               `protobuf:"fixed64,7,opt,name=baseBalance" json:"baseBalance"`
	CurrencyBalance float64               `protobuf:"fixed64,8,opt,name=currencyBalance" json:"currencyBalance"`
	Status          string                `protobuf:"bytes,9,opt,name=status" json:"status"`
	Orders          []*order.OrderRequest `protobuf:"bytes,10,rep,name=orders" json:"orders"`
}

func (m *PlanRequest) Reset()                    { *m = PlanRequest{} }
func (m *PlanRequest) String() string            { return proto.CompactTextString(m) }
func (*PlanRequest) ProtoMessage()               {}
func (*PlanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PlanRequest) GetPlanID() string {
	if m != nil {
		return m.PlanID
	}
	return ""
}

func (m *PlanRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *PlanRequest) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *PlanRequest) GetPlanTemplateID() string {
	if m != nil {
		return m.PlanTemplateID
	}
	return ""
}

func (m *PlanRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *PlanRequest) GetMarketName() string {
	if m != nil {
		return m.MarketName
	}
	return ""
}

func (m *PlanRequest) GetBaseBalance() float64 {
	if m != nil {
		return m.BaseBalance
	}
	return 0
}

func (m *PlanRequest) GetCurrencyBalance() float64 {
	if m != nil {
		return m.CurrencyBalance
	}
	return 0
}

func (m *PlanRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PlanRequest) GetOrders() []*order.OrderRequest {
	if m != nil {
		return m.Orders
	}
	return nil
}

type GetUserPlanRequest struct {
	PlanID   string `protobuf:"bytes,1,opt,name=planID" json:"planID"`
	UserID   string `protobuf:"bytes,2,opt,name=userID" json:"userID"`
	Page     uint32 `protobuf:"varint,3,opt,name=page" json:"page"`
	PageSize uint32 `protobuf:"varint,4,opt,name=pageSize" json:"pageSize"`
}

func (m *GetUserPlanRequest) Reset()                    { *m = GetUserPlanRequest{} }
func (m *GetUserPlanRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserPlanRequest) ProtoMessage()               {}
func (*GetUserPlanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetUserPlanRequest) GetPlanID() string {
	if m != nil {
		return m.PlanID
	}
	return ""
}

func (m *GetUserPlanRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetUserPlanRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetUserPlanRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type GetUserPlansRequest struct {
	UserID     string `protobuf:"bytes,1,opt,name=userID" json:"userID"`
	Exchange   string `protobuf:"bytes,2,opt,name=exchange" json:"exchange"`
	MarketName string `protobuf:"bytes,3,opt,name=marketName" json:"marketName"`
	Status     string `protobuf:"bytes,4,opt,name=status" json:"status"`
	Page       uint32 `protobuf:"varint,5,opt,name=page" json:"page"`
	PageSize   uint32 `protobuf:"varint,6,opt,name=pageSize" json:"pageSize"`
}

func (m *GetUserPlansRequest) Reset()                    { *m = GetUserPlansRequest{} }
func (m *GetUserPlansRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserPlansRequest) ProtoMessage()               {}
func (*GetUserPlansRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetUserPlansRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetUserPlansRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *GetUserPlansRequest) GetMarketName() string {
	if m != nil {
		return m.MarketName
	}
	return ""
}

func (m *GetUserPlansRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetUserPlansRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetUserPlansRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type DeletePlanRequest struct {
	PlanID string `protobuf:"bytes,1,opt,name=planID" json:"planID"`
	UserID string `protobuf:"bytes,2,opt,name=userID" json:"userID"`
}

func (m *DeletePlanRequest) Reset()                    { *m = DeletePlanRequest{} }
func (m *DeletePlanRequest) String() string            { return proto.CompactTextString(m) }
func (*DeletePlanRequest) ProtoMessage()               {}
func (*DeletePlanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeletePlanRequest) GetPlanID() string {
	if m != nil {
		return m.PlanID
	}
	return ""
}

func (m *DeletePlanRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type UpdatePlanRequest struct {
	PlanID          string  `protobuf:"bytes,1,opt,name=planID" json:"planID"`
	UserID          string  `protobuf:"bytes,2,opt,name=userID" json:"userID"`
	Status          string  `protobuf:"bytes,3,opt,name=status" json:"status"`
	BaseBalance     float64 `protobuf:"fixed64,4,opt,name=baseBalance" json:"baseBalance"`
	CurrencyBalance float64 `protobuf:"fixed64,5,opt,name=currencyBalance" json:"currencyBalance"`
}

func (m *UpdatePlanRequest) Reset()                    { *m = UpdatePlanRequest{} }
func (m *UpdatePlanRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdatePlanRequest) ProtoMessage()               {}
func (*UpdatePlanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdatePlanRequest) GetPlanID() string {
	if m != nil {
		return m.PlanID
	}
	return ""
}

func (m *UpdatePlanRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdatePlanRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UpdatePlanRequest) GetBaseBalance() float64 {
	if m != nil {
		return m.BaseBalance
	}
	return 0
}

func (m *UpdatePlanRequest) GetCurrencyBalance() float64 {
	if m != nil {
		return m.CurrencyBalance
	}
	return 0
}

// Responses
type Plan struct {
	PlanID             string         `protobuf:"bytes,1,opt,name=planID" json:"planID"`
	PlanTemplateID     string         `protobuf:"bytes,2,opt,name=planTemplateID" json:"planTemplateID"`
	UserID             string         `protobuf:"bytes,3,opt,name=userID" json:"userID"`
	KeyID              string         `protobuf:"bytes,4,opt,name=keyID" json:"keyID"`
	Key                string         `protobuf:"bytes,5,opt,name=key" json:"key"`
	KeySecret          string         `protobuf:"bytes,6,opt,name=keySecret" json:"keySecret"`
	KeyDescription     string         `protobuf:"bytes,7,opt,name=keyDescription" json:"keyDescription"`
	ActiveOrderNumber  uint32         `protobuf:"varint,8,opt,name=activeOrderNumber" json:"activeOrderNumber"`
	Exchange           string         `protobuf:"bytes,9,opt,name=exchange" json:"exchange"`
	ExchangeMarketName string         `protobuf:"bytes,10,opt,name=exchangeMarketName" json:"exchangeMarketName"`
	MarketName         string         `protobuf:"bytes,11,opt,name=marketName" json:"marketName"`
	BaseBalance        float64        `protobuf:"fixed64,12,opt,name=baseBalance" json:"baseBalance"`
	CurrencyBalance    float64        `protobuf:"fixed64,13,opt,name=currencyBalance" json:"currencyBalance"`
	Status             string         `protobuf:"bytes,14,opt,name=status" json:"status"`
	Orders             []*order.Order `protobuf:"bytes,15,rep,name=orders" json:"orders"`
}

func (m *Plan) Reset()                    { *m = Plan{} }
func (m *Plan) String() string            { return proto.CompactTextString(m) }
func (*Plan) ProtoMessage()               {}
func (*Plan) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Plan) GetPlanID() string {
	if m != nil {
		return m.PlanID
	}
	return ""
}

func (m *Plan) GetPlanTemplateID() string {
	if m != nil {
		return m.PlanTemplateID
	}
	return ""
}

func (m *Plan) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Plan) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *Plan) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Plan) GetKeySecret() string {
	if m != nil {
		return m.KeySecret
	}
	return ""
}

func (m *Plan) GetKeyDescription() string {
	if m != nil {
		return m.KeyDescription
	}
	return ""
}

func (m *Plan) GetActiveOrderNumber() uint32 {
	if m != nil {
		return m.ActiveOrderNumber
	}
	return 0
}

func (m *Plan) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *Plan) GetExchangeMarketName() string {
	if m != nil {
		return m.ExchangeMarketName
	}
	return ""
}

func (m *Plan) GetMarketName() string {
	if m != nil {
		return m.MarketName
	}
	return ""
}

func (m *Plan) GetBaseBalance() float64 {
	if m != nil {
		return m.BaseBalance
	}
	return 0
}

func (m *Plan) GetCurrencyBalance() float64 {
	if m != nil {
		return m.CurrencyBalance
	}
	return 0
}

func (m *Plan) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Plan) GetOrders() []*order.Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type PlanWithPagedOrders struct {
	PlanID             string            `protobuf:"bytes,1,opt,name=planID" json:"planID"`
	PlanTemplateID     string            `protobuf:"bytes,2,opt,name=planTemplateID" json:"planTemplateID"`
	UserID             string            `protobuf:"bytes,3,opt,name=userID" json:"userID"`
	KeyID              string            `protobuf:"bytes,4,opt,name=keyID" json:"keyID"`
	Key                string            `protobuf:"bytes,5,opt,name=key" json:"key"`
	KeySecret          string            `protobuf:"bytes,6,opt,name=keySecret" json:"keySecret"`
	KeyDescription     string            `protobuf:"bytes,7,opt,name=keyDescription" json:"keyDescription"`
	Exchange           string            `protobuf:"bytes,8,opt,name=exchange" json:"exchange"`
	ExchangeMarketName string            `protobuf:"bytes,9,opt,name=exchangeMarketName" json:"exchangeMarketName"`
	MarketName         string            `protobuf:"bytes,10,opt,name=marketName" json:"marketName"`
	BaseBalance        float64           `protobuf:"fixed64,11,opt,name=baseBalance" json:"baseBalance"`
	CurrencyBalance    float64           `protobuf:"fixed64,12,opt,name=currencyBalance" json:"currencyBalance"`
	Status             string            `protobuf:"bytes,13,opt,name=status" json:"status"`
	OrdersPage         *order.OrdersPage `protobuf:"bytes,14,opt,name=ordersPage" json:"ordersPage"`
}

func (m *PlanWithPagedOrders) Reset()                    { *m = PlanWithPagedOrders{} }
func (m *PlanWithPagedOrders) String() string            { return proto.CompactTextString(m) }
func (*PlanWithPagedOrders) ProtoMessage()               {}
func (*PlanWithPagedOrders) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PlanWithPagedOrders) GetPlanID() string {
	if m != nil {
		return m.PlanID
	}
	return ""
}

func (m *PlanWithPagedOrders) GetPlanTemplateID() string {
	if m != nil {
		return m.PlanTemplateID
	}
	return ""
}

func (m *PlanWithPagedOrders) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *PlanWithPagedOrders) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *PlanWithPagedOrders) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PlanWithPagedOrders) GetKeySecret() string {
	if m != nil {
		return m.KeySecret
	}
	return ""
}

func (m *PlanWithPagedOrders) GetKeyDescription() string {
	if m != nil {
		return m.KeyDescription
	}
	return ""
}

func (m *PlanWithPagedOrders) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *PlanWithPagedOrders) GetExchangeMarketName() string {
	if m != nil {
		return m.ExchangeMarketName
	}
	return ""
}

func (m *PlanWithPagedOrders) GetMarketName() string {
	if m != nil {
		return m.MarketName
	}
	return ""
}

func (m *PlanWithPagedOrders) GetBaseBalance() float64 {
	if m != nil {
		return m.BaseBalance
	}
	return 0
}

func (m *PlanWithPagedOrders) GetCurrencyBalance() float64 {
	if m != nil {
		return m.CurrencyBalance
	}
	return 0
}

func (m *PlanWithPagedOrders) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PlanWithPagedOrders) GetOrdersPage() *order.OrdersPage {
	if m != nil {
		return m.OrdersPage
	}
	return nil
}

type PlanData struct {
	Plan *Plan `protobuf:"bytes,1,opt,name=plan" json:"plan"`
}

func (m *PlanData) Reset()                    { *m = PlanData{} }
func (m *PlanData) String() string            { return proto.CompactTextString(m) }
func (*PlanData) ProtoMessage()               {}
func (*PlanData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PlanData) GetPlan() *Plan {
	if m != nil {
		return m.Plan
	}
	return nil
}

type PlanResponse struct {
	Status  string    `protobuf:"bytes,1,opt,name=status" json:"status"`
	Message string    `protobuf:"bytes,2,opt,name=message" json:"message"`
	Data    *PlanData `protobuf:"bytes,3,opt,name=data" json:"data"`
}

func (m *PlanResponse) Reset()                    { *m = PlanResponse{} }
func (m *PlanResponse) String() string            { return proto.CompactTextString(m) }
func (*PlanResponse) ProtoMessage()               {}
func (*PlanResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PlanResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PlanResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PlanResponse) GetData() *PlanData {
	if m != nil {
		return m.Data
	}
	return nil
}

type PlanWithPagedOrdersResponse struct {
	Status  string               `protobuf:"bytes,1,opt,name=status" json:"status"`
	Message string               `protobuf:"bytes,2,opt,name=message" json:"message"`
	Data    *PlanWithPagedOrders `protobuf:"bytes,3,opt,name=data" json:"data"`
}

func (m *PlanWithPagedOrdersResponse) Reset()                    { *m = PlanWithPagedOrdersResponse{} }
func (m *PlanWithPagedOrdersResponse) String() string            { return proto.CompactTextString(m) }
func (*PlanWithPagedOrdersResponse) ProtoMessage()               {}
func (*PlanWithPagedOrdersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PlanWithPagedOrdersResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PlanWithPagedOrdersResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PlanWithPagedOrdersResponse) GetData() *PlanWithPagedOrders {
	if m != nil {
		return m.Data
	}
	return nil
}

type PlansPageResponse struct {
	Status  string     `protobuf:"bytes,1,opt,name=status" json:"status"`
	Message string     `protobuf:"bytes,2,opt,name=message" json:"message"`
	Data    *PlansPage `protobuf:"bytes,3,opt,name=data" json:"data"`
}

func (m *PlansPageResponse) Reset()                    { *m = PlansPageResponse{} }
func (m *PlansPageResponse) String() string            { return proto.CompactTextString(m) }
func (*PlansPageResponse) ProtoMessage()               {}
func (*PlansPageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *PlansPageResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PlansPageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PlansPageResponse) GetData() *PlansPage {
	if m != nil {
		return m.Data
	}
	return nil
}

type PlansPage struct {
	Page     uint32  `protobuf:"varint,1,opt,name=page" json:"page"`
	PageSize uint32  `protobuf:"varint,2,opt,name=pageSize" json:"pageSize"`
	Total    uint32  `protobuf:"varint,3,opt,name=total" json:"total"`
	Plans    []*Plan `protobuf:"bytes,4,rep,name=plans" json:"plans"`
}

func (m *PlansPage) Reset()                    { *m = PlansPage{} }
func (m *PlansPage) String() string            { return proto.CompactTextString(m) }
func (*PlansPage) ProtoMessage()               {}
func (*PlansPage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *PlansPage) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PlansPage) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PlansPage) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PlansPage) GetPlans() []*Plan {
	if m != nil {
		return m.Plans
	}
	return nil
}

func init() {
	proto.RegisterType((*PlanRequest)(nil), "PlanRequest")
	proto.RegisterType((*GetUserPlanRequest)(nil), "GetUserPlanRequest")
	proto.RegisterType((*GetUserPlansRequest)(nil), "GetUserPlansRequest")
	proto.RegisterType((*DeletePlanRequest)(nil), "DeletePlanRequest")
	proto.RegisterType((*UpdatePlanRequest)(nil), "UpdatePlanRequest")
	proto.RegisterType((*Plan)(nil), "Plan")
	proto.RegisterType((*PlanWithPagedOrders)(nil), "PlanWithPagedOrders")
	proto.RegisterType((*PlanData)(nil), "PlanData")
	proto.RegisterType((*PlanResponse)(nil), "PlanResponse")
	proto.RegisterType((*PlanWithPagedOrdersResponse)(nil), "PlanWithPagedOrdersResponse")
	proto.RegisterType((*PlansPageResponse)(nil), "PlansPageResponse")
	proto.RegisterType((*PlansPage)(nil), "PlansPage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PlanService service

type PlanServiceClient interface {
	AddPlan(ctx context.Context, in *PlanRequest, opts ...client.CallOption) (*PlanResponse, error)
	GetUserPlan(ctx context.Context, in *GetUserPlanRequest, opts ...client.CallOption) (*PlanWithPagedOrdersResponse, error)
	GetUserPlans(ctx context.Context, in *GetUserPlansRequest, opts ...client.CallOption) (*PlansPageResponse, error)
	DeletePlan(ctx context.Context, in *DeletePlanRequest, opts ...client.CallOption) (*PlanResponse, error)
	UpdatePlan(ctx context.Context, in *UpdatePlanRequest, opts ...client.CallOption) (*PlanResponse, error)
}

type planServiceClient struct {
	c           client.Client
	serviceName string
}

func NewPlanServiceClient(serviceName string, c client.Client) PlanServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "planservice"
	}
	return &planServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *planServiceClient) AddPlan(ctx context.Context, in *PlanRequest, opts ...client.CallOption) (*PlanResponse, error) {
	req := c.c.NewRequest(c.serviceName, "PlanService.AddPlan", in)
	out := new(PlanResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) GetUserPlan(ctx context.Context, in *GetUserPlanRequest, opts ...client.CallOption) (*PlanWithPagedOrdersResponse, error) {
	req := c.c.NewRequest(c.serviceName, "PlanService.GetUserPlan", in)
	out := new(PlanWithPagedOrdersResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) GetUserPlans(ctx context.Context, in *GetUserPlansRequest, opts ...client.CallOption) (*PlansPageResponse, error) {
	req := c.c.NewRequest(c.serviceName, "PlanService.GetUserPlans", in)
	out := new(PlansPageResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) DeletePlan(ctx context.Context, in *DeletePlanRequest, opts ...client.CallOption) (*PlanResponse, error) {
	req := c.c.NewRequest(c.serviceName, "PlanService.DeletePlan", in)
	out := new(PlanResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) UpdatePlan(ctx context.Context, in *UpdatePlanRequest, opts ...client.CallOption) (*PlanResponse, error) {
	req := c.c.NewRequest(c.serviceName, "PlanService.UpdatePlan", in)
	out := new(PlanResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PlanService service

type PlanServiceHandler interface {
	AddPlan(context.Context, *PlanRequest, *PlanResponse) error
	GetUserPlan(context.Context, *GetUserPlanRequest, *PlanWithPagedOrdersResponse) error
	GetUserPlans(context.Context, *GetUserPlansRequest, *PlansPageResponse) error
	DeletePlan(context.Context, *DeletePlanRequest, *PlanResponse) error
	UpdatePlan(context.Context, *UpdatePlanRequest, *PlanResponse) error
}

func RegisterPlanServiceHandler(s server.Server, hdlr PlanServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&PlanService{hdlr}, opts...))
}

type PlanService struct {
	PlanServiceHandler
}

func (h *PlanService) AddPlan(ctx context.Context, in *PlanRequest, out *PlanResponse) error {
	return h.PlanServiceHandler.AddPlan(ctx, in, out)
}

func (h *PlanService) GetUserPlan(ctx context.Context, in *GetUserPlanRequest, out *PlanWithPagedOrdersResponse) error {
	return h.PlanServiceHandler.GetUserPlan(ctx, in, out)
}

func (h *PlanService) GetUserPlans(ctx context.Context, in *GetUserPlansRequest, out *PlansPageResponse) error {
	return h.PlanServiceHandler.GetUserPlans(ctx, in, out)
}

func (h *PlanService) DeletePlan(ctx context.Context, in *DeletePlanRequest, out *PlanResponse) error {
	return h.PlanServiceHandler.DeletePlan(ctx, in, out)
}

func (h *PlanService) UpdatePlan(ctx context.Context, in *UpdatePlanRequest, out *PlanResponse) error {
	return h.PlanServiceHandler.UpdatePlan(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/asciiu/gomo/plan-service/proto/plan/plan.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 817 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x56, 0xcd, 0x8e, 0x2a, 0x45,
	0x14, 0x9e, 0xa6, 0x1b, 0x86, 0x3e, 0x0d, 0xf7, 0x4a, 0xcd, 0xc4, 0xb4, 0xdc, 0xeb, 0x84, 0x74,
	0x72, 0x0d, 0x89, 0x5a, 0xe4, 0xe2, 0x4a, 0xe3, 0xc6, 0x91, 0xc4, 0xb0, 0x70, 0x9c, 0xf4, 0x38,
	0x71, 0x69, 0x8a, 0xe6, 0x84, 0xe9, 0x00, 0xdd, 0xd8, 0x55, 0x4c, 0xc4, 0x77, 0x71, 0xed, 0xda,
	0x57, 0xf0, 0x29, 0x7c, 0x06, 0x9f, 0xc2, 0x54, 0x55, 0x43, 0xff, 0xc1, 0x40, 0x64, 0xe7, 0x06,
	0xfa, 0x7c, 0xf5, 0x73, 0xaa, 0xce, 0x77, 0xce, 0xf9, 0x0a, 0xbe, 0x9c, 0x85, 0xe2, 0x69, 0x3d,
	0xa1, 0x41, 0xbc, 0x1c, 0x30, 0x1e, 0x84, 0xe1, 0x7a, 0x30, 0x8b, 0x97, 0xf1, 0x60, 0xb5, 0x60,
	0xd1, 0xe7, 0x1c, 0x93, 0xe7, 0x30, 0xc0, 0xc1, 0x2a, 0x89, 0x85, 0x86, 0xd4, 0x0f, 0x55, 0x76,
	0xf7, 0xeb, 0x03, 0x4b, 0xe3, 0x64, 0x8a, 0x49, 0x69, 0xad, 0xc2, 0xf4, 0xaf, 0x5e, 0xed, 0xfd,
	0x55, 0x03, 0xe7, 0x7e, 0xc1, 0x22, 0x1f, 0x7f, 0x59, 0x23, 0x17, 0xe4, 0x43, 0x68, 0xc8, 0xbd,
	0xc7, 0x23, 0xd7, 0xe8, 0x19, 0x7d, 0xdb, 0x4f, 0x2d, 0x89, 0xaf, 0x39, 0x26, 0xe3, 0x91, 0x5b,
	0xd3, 0xb8, 0xb6, 0xc8, 0x35, 0xd4, 0xe7, 0xb8, 0x19, 0x8f, 0x5c, 0x53, 0xc1, 0xda, 0x20, 0x9f,
	0xc0, 0x2b, 0xb9, 0xee, 0x47, 0x5c, 0xae, 0x16, 0x4c, 0xe0, 0x78, 0xe4, 0x5a, 0x6a, 0xb8, 0x84,
	0x92, 0x2e, 0x34, 0xf1, 0xd7, 0xe0, 0x89, 0x45, 0x33, 0x74, 0xeb, 0x6a, 0xc6, 0xce, 0x26, 0x37,
	0x00, 0x4b, 0x96, 0xcc, 0x51, 0xdc, 0xb1, 0x25, 0xba, 0x0d, 0x35, 0x9a, 0x43, 0x48, 0x0f, 0x9c,
	0x09, 0xe3, 0x78, 0xcb, 0x16, 0x2c, 0x0a, 0xd0, 0xbd, 0xec, 0x19, 0x7d, 0xc3, 0xcf, 0x43, 0xa4,
	0x0f, 0xaf, 0x83, 0x75, 0x92, 0x60, 0x14, 0x6c, 0xb6, 0xb3, 0x9a, 0x6a, 0x56, 0x19, 0x96, 0xb7,
	0xe3, 0x82, 0x89, 0x35, 0x77, 0x6d, 0x7d, 0x3b, 0x6d, 0x91, 0x77, 0xd0, 0x50, 0xc1, 0xe2, 0x2e,
	0xf4, 0xcc, 0xbe, 0x33, 0x6c, 0xd3, 0x1f, 0xa4, 0x99, 0x06, 0xcb, 0x4f, 0x07, 0x3d, 0x01, 0xe4,
	0x3b, 0x14, 0x8f, 0x1c, 0x93, 0x73, 0x42, 0x49, 0xc0, 0x5a, 0xb1, 0x19, 0xaa, 0x48, 0xb6, 0x7d,
	0xf5, 0x2d, 0x03, 0x24, 0xff, 0x1f, 0xc2, 0xdf, 0x50, 0x85, 0xb0, 0xed, 0xef, 0x6c, 0xef, 0x4f,
	0x03, 0xae, 0x72, 0x6e, 0x79, 0xce, 0x6f, 0xba, 0xbf, 0x51, 0xd8, 0x3f, 0x1f, 0xec, 0xda, 0x8b,
	0xc1, 0x36, 0x2b, 0xc1, 0xce, 0x02, 0x64, 0x15, 0x02, 0xb4, 0x3d, 0x73, 0xfd, 0xc0, 0x99, 0x1b,
	0xa5, 0x33, 0x7f, 0x0b, 0x9d, 0x11, 0x2e, 0x50, 0xe0, 0x19, 0x81, 0xf2, 0xfe, 0x30, 0xa0, 0xf3,
	0xb8, 0x9a, 0xb2, 0xb3, 0x76, 0xc9, 0x5d, 0xc9, 0x2c, 0x5c, 0xa9, 0x94, 0x57, 0xd6, 0x49, 0x79,
	0x55, 0xdf, 0x9b, 0x57, 0xde, 0x3f, 0x26, 0x58, 0xf2, 0x8c, 0x07, 0x0f, 0x57, 0x2d, 0x94, 0xda,
	0xde, 0x42, 0xc9, 0x2e, 0x61, 0xee, 0x2f, 0x3f, 0x2b, 0x5f, 0x7e, 0x1f, 0x80, 0x39, 0xc7, 0x4d,
	0x5a, 0x51, 0xf2, 0x93, 0xbc, 0x05, 0x7b, 0x8e, 0x9b, 0x07, 0x0c, 0x12, 0x14, 0x69, 0x2d, 0x65,
	0x80, 0x3c, 0xc5, 0x1c, 0x37, 0x23, 0xe4, 0x41, 0x12, 0xae, 0x44, 0x18, 0x47, 0xaa, 0x9a, 0x6c,
	0xbf, 0x84, 0x92, 0xcf, 0xa0, 0xc3, 0x02, 0x11, 0x3e, 0xa3, 0xaa, 0x82, 0xbb, 0xf5, 0x72, 0x82,
	0x89, 0x2a, 0xa9, 0xb6, 0x5f, 0x1d, 0x28, 0xe4, 0x9b, 0x5d, 0xca, 0x37, 0x0a, 0x64, 0xfb, 0xfd,
	0x7d, 0x96, 0x77, 0xa0, 0x66, 0xed, 0x19, 0x29, 0xe5, 0xa7, 0x73, 0xac, 0x19, 0xb4, 0x4e, 0x22,
	0xad, 0x7d, 0xac, 0x19, 0xbc, 0x2a, 0x24, 0xc6, 0xcd, 0xae, 0x19, 0xbc, 0x56, 0xcd, 0xa0, 0x91,
	0x36, 0x83, 0x6d, 0x17, 0xf8, 0xdb, 0x84, 0x2b, 0x49, 0xf6, 0x4f, 0xa1, 0x78, 0xba, 0x67, 0x33,
	0x9c, 0xaa, 0x61, 0xfe, 0x3f, 0xe1, 0x3e, 0xcf, 0x66, 0xf3, 0x24, 0x36, 0xed, 0x13, 0xd9, 0x84,
	0x63, 0x6c, 0x3a, 0x27, 0xb1, 0xd9, 0x3a, 0xc6, 0x66, 0xbb, 0xc0, 0xe6, 0xa7, 0x00, 0x9a, 0x37,
	0x49, 0x95, 0x62, 0xda, 0x19, 0x3a, 0x9a, 0x51, 0x05, 0xf9, 0xb9, 0x61, 0xef, 0x1d, 0x34, 0x25,
	0xb3, 0x23, 0x26, 0x18, 0xf9, 0x08, 0x2c, 0x49, 0x90, 0x22, 0xd3, 0x19, 0xd6, 0xa9, 0xea, 0x41,
	0x0a, 0xf2, 0x7e, 0x86, 0x96, 0xee, 0x48, 0x7c, 0x15, 0x47, 0x3c, 0xef, 0xdb, 0x28, 0xf8, 0x76,
	0xe1, 0x72, 0x89, 0x9c, 0xb3, 0x5d, 0x23, 0xde, 0x9a, 0xe4, 0x63, 0xb0, 0xa6, 0x4c, 0x30, 0xc5,
	0xb4, 0x33, 0xb4, 0xe9, 0xd6, 0xab, 0xaf, 0x60, 0x6f, 0x03, 0x6f, 0xf6, 0x64, 0xd8, 0x19, 0xfe,
	0xfa, 0x05, 0x7f, 0xd7, 0x74, 0xdf, 0xee, 0xda, 0x35, 0x42, 0x47, 0xa9, 0x8c, 0x8a, 0xcd, 0x7f,
	0x77, 0x78, 0x53, 0x70, 0x08, 0x34, 0xdb, 0x53, 0xbb, 0x89, 0xc0, 0xde, 0x41, 0x3b, 0x75, 0x31,
	0x0e, 0xa8, 0x4b, 0xad, 0xa8, 0x2e, 0xb2, 0x22, 0x44, 0x2c, 0xd8, 0x22, 0x95, 0x50, 0x6d, 0x90,
	0x37, 0x50, 0x97, 0xec, 0x48, 0xe9, 0x32, 0x33, 0xc6, 0x34, 0x36, 0xfc, 0x3d, 0x7d, 0xff, 0x3c,
	0xe8, 0x77, 0x12, 0xe9, 0xc3, 0xe5, 0x37, 0xd3, 0xa9, 0xea, 0xd9, 0x2d, 0x9a, 0x93, 0x97, 0x6e,
	0x9b, 0xe6, 0xa9, 0xf5, 0x2e, 0xc8, 0x2d, 0x38, 0x39, 0xf5, 0x25, 0x57, 0xb4, 0xfa, 0x04, 0xe8,
	0xbe, 0xa5, 0x2f, 0xd0, 0xe5, 0x5d, 0x90, 0xaf, 0xa0, 0x95, 0x57, 0x70, 0x72, 0x4d, 0xf7, 0x08,
	0x7a, 0x97, 0xd0, 0x4a, 0xe4, 0xbd, 0x0b, 0xf2, 0x1e, 0x20, 0x93, 0x52, 0x42, 0x68, 0x45, 0x57,
	0xab, 0x47, 0x7e, 0x0f, 0x90, 0xe9, 0x26, 0x21, 0xb4, 0x22, 0xa2, 0x95, 0x25, 0x93, 0x86, 0x7a,
	0x26, 0x7e, 0xf1, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xd5, 0xbd, 0x10, 0xa1, 0x0a, 0x00,
	0x00,
}
