// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/asciiu/gomo/plan-service/proto/plan/plan.proto

/*
Package plan is a generated protocol buffer package.

It is generated from these files:
	github.com/asciiu/gomo/plan-service/proto/plan/plan.proto

It has these top-level messages:
	NewPlanRequest
	UpdatePlanRequest
	GetUserPlanRequest
	GetUserPlansRequest
	DeletePlanRequest
	Plan
	PlanData
	PlanResponse
	PlansPageResponse
	PlansPage
*/
package plan

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import order "github.com/asciiu/gomo/plan-service/proto/order"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Requests
type NewPlanRequest struct {
	UserID          string                   `protobuf:"bytes,1,opt,name=userID" json:"userID"`
	Title           string                   `protobuf:"bytes,2,opt,name=title" json:"title"`
	PlanTemplateID  string                   `protobuf:"bytes,3,opt,name=planTemplateID" json:"planTemplateID"`
	Status          string                   `protobuf:"bytes,4,opt,name=status" json:"status"`
	CloseOnComplete bool                     `protobuf:"varint,5,opt,name=closeOnComplete" json:"closeOnComplete"`
	Orders          []*order.NewOrderRequest `protobuf:"bytes,6,rep,name=orders" json:"orders"`
}

func (m *NewPlanRequest) Reset()                    { *m = NewPlanRequest{} }
func (m *NewPlanRequest) String() string            { return proto.CompactTextString(m) }
func (*NewPlanRequest) ProtoMessage()               {}
func (*NewPlanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NewPlanRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *NewPlanRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NewPlanRequest) GetPlanTemplateID() string {
	if m != nil {
		return m.PlanTemplateID
	}
	return ""
}

func (m *NewPlanRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *NewPlanRequest) GetCloseOnComplete() bool {
	if m != nil {
		return m.CloseOnComplete
	}
	return false
}

func (m *NewPlanRequest) GetOrders() []*order.NewOrderRequest {
	if m != nil {
		return m.Orders
	}
	return nil
}

type UpdatePlanRequest struct {
	PlanID          string                   `protobuf:"bytes,1,opt,name=planID" json:"planID"`
	UserID          string                   `protobuf:"bytes,2,opt,name=userID" json:"userID"`
	Title           string                   `protobuf:"bytes,3,opt,name=title" json:"title"`
	PlanTemplateID  string                   `protobuf:"bytes,4,opt,name=planTemplateID" json:"planTemplateID"`
	Status          string                   `protobuf:"bytes,5,opt,name=status" json:"status"`
	CloseOnComplete bool                     `protobuf:"varint,6,opt,name=closeOnComplete" json:"closeOnComplete"`
	Orders          []*order.NewOrderRequest `protobuf:"bytes,7,rep,name=orders" json:"orders"`
}

func (m *UpdatePlanRequest) Reset()                    { *m = UpdatePlanRequest{} }
func (m *UpdatePlanRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdatePlanRequest) ProtoMessage()               {}
func (*UpdatePlanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpdatePlanRequest) GetPlanID() string {
	if m != nil {
		return m.PlanID
	}
	return ""
}

func (m *UpdatePlanRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdatePlanRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdatePlanRequest) GetPlanTemplateID() string {
	if m != nil {
		return m.PlanTemplateID
	}
	return ""
}

func (m *UpdatePlanRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UpdatePlanRequest) GetCloseOnComplete() bool {
	if m != nil {
		return m.CloseOnComplete
	}
	return false
}

func (m *UpdatePlanRequest) GetOrders() []*order.NewOrderRequest {
	if m != nil {
		return m.Orders
	}
	return nil
}

type GetUserPlanRequest struct {
	PlanID     string `protobuf:"bytes,1,opt,name=planID" json:"planID"`
	UserID     string `protobuf:"bytes,2,opt,name=userID" json:"userID"`
	PlanDepth  uint32 `protobuf:"varint,3,opt,name=planDepth" json:"planDepth"`
	PlanLength uint32 `protobuf:"varint,4,opt,name=planLength" json:"planLength"`
}

func (m *GetUserPlanRequest) Reset()                    { *m = GetUserPlanRequest{} }
func (m *GetUserPlanRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserPlanRequest) ProtoMessage()               {}
func (*GetUserPlanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetUserPlanRequest) GetPlanID() string {
	if m != nil {
		return m.PlanID
	}
	return ""
}

func (m *GetUserPlanRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetUserPlanRequest) GetPlanDepth() uint32 {
	if m != nil {
		return m.PlanDepth
	}
	return 0
}

func (m *GetUserPlanRequest) GetPlanLength() uint32 {
	if m != nil {
		return m.PlanLength
	}
	return 0
}

type GetUserPlansRequest struct {
	UserID     string `protobuf:"bytes,1,opt,name=userID" json:"userID"`
	Exchange   string `protobuf:"bytes,2,opt,name=exchange" json:"exchange"`
	MarketName string `protobuf:"bytes,3,opt,name=marketName" json:"marketName"`
	Status     string `protobuf:"bytes,4,opt,name=status" json:"status"`
	Page       uint32 `protobuf:"varint,5,opt,name=page" json:"page"`
	PageSize   uint32 `protobuf:"varint,6,opt,name=pageSize" json:"pageSize"`
}

func (m *GetUserPlansRequest) Reset()                    { *m = GetUserPlansRequest{} }
func (m *GetUserPlansRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserPlansRequest) ProtoMessage()               {}
func (*GetUserPlansRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetUserPlansRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetUserPlansRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *GetUserPlansRequest) GetMarketName() string {
	if m != nil {
		return m.MarketName
	}
	return ""
}

func (m *GetUserPlansRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetUserPlansRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetUserPlansRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type DeletePlanRequest struct {
	PlanID string `protobuf:"bytes,1,opt,name=planID" json:"planID"`
	UserID string `protobuf:"bytes,2,opt,name=userID" json:"userID"`
}

func (m *DeletePlanRequest) Reset()                    { *m = DeletePlanRequest{} }
func (m *DeletePlanRequest) String() string            { return proto.CompactTextString(m) }
func (*DeletePlanRequest) ProtoMessage()               {}
func (*DeletePlanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeletePlanRequest) GetPlanID() string {
	if m != nil {
		return m.PlanID
	}
	return ""
}

func (m *DeletePlanRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

// Responses
type Plan struct {
	PlanID                string         `protobuf:"bytes,1,opt,name=planID" json:"planID"`
	PlanTemplateID        string         `protobuf:"bytes,2,opt,name=planTemplateID" json:"planTemplateID"`
	UserID                string         `protobuf:"bytes,3,opt,name=userID" json:"userID"`
	LastExecutedPlanDepth uint32         `protobuf:"varint,8,opt,name=lastExecutedPlanDepth" json:"lastExecutedPlanDepth"`
	LastExecutedOrderID   string         `protobuf:"bytes,9,opt,name=lastExecutedOrderID" json:"lastExecutedOrderID"`
	Exchange              string         `protobuf:"bytes,10,opt,name=exchange" json:"exchange"`
	MarketName            string         `protobuf:"bytes,11,opt,name=marketName" json:"marketName"`
	ActiveCurrencySymbol  string         `protobuf:"bytes,12,opt,name=activeCurrencySymbol" json:"activeCurrencySymbol"`
	ActiveCurrencyBalance float64        `protobuf:"fixed64,13,opt,name=activeCurrencyBalance" json:"activeCurrencyBalance"`
	UserPlanNumber        uint64         `protobuf:"varint,14,opt,name=userPlanNumber" json:"userPlanNumber"`
	Status                string         `protobuf:"bytes,15,opt,name=status" json:"status"`
	CloseOnComplete       bool           `protobuf:"varint,16,opt,name=closeOnComplete" json:"closeOnComplete"`
	CreatedOn             string         `protobuf:"bytes,17,opt,name=createdOn" json:"createdOn"`
	UpdatedOn             string         `protobuf:"bytes,18,opt,name=updatedOn" json:"updatedOn"`
	Title                 string         `protobuf:"bytes,19,opt,name=title" json:"title"`
	Orders                []*order.Order `protobuf:"bytes,20,rep,name=orders" json:"orders"`
}

func (m *Plan) Reset()                    { *m = Plan{} }
func (m *Plan) String() string            { return proto.CompactTextString(m) }
func (*Plan) ProtoMessage()               {}
func (*Plan) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Plan) GetPlanID() string {
	if m != nil {
		return m.PlanID
	}
	return ""
}

func (m *Plan) GetPlanTemplateID() string {
	if m != nil {
		return m.PlanTemplateID
	}
	return ""
}

func (m *Plan) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Plan) GetLastExecutedPlanDepth() uint32 {
	if m != nil {
		return m.LastExecutedPlanDepth
	}
	return 0
}

func (m *Plan) GetLastExecutedOrderID() string {
	if m != nil {
		return m.LastExecutedOrderID
	}
	return ""
}

func (m *Plan) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *Plan) GetMarketName() string {
	if m != nil {
		return m.MarketName
	}
	return ""
}

func (m *Plan) GetActiveCurrencySymbol() string {
	if m != nil {
		return m.ActiveCurrencySymbol
	}
	return ""
}

func (m *Plan) GetActiveCurrencyBalance() float64 {
	if m != nil {
		return m.ActiveCurrencyBalance
	}
	return 0
}

func (m *Plan) GetUserPlanNumber() uint64 {
	if m != nil {
		return m.UserPlanNumber
	}
	return 0
}

func (m *Plan) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Plan) GetCloseOnComplete() bool {
	if m != nil {
		return m.CloseOnComplete
	}
	return false
}

func (m *Plan) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *Plan) GetUpdatedOn() string {
	if m != nil {
		return m.UpdatedOn
	}
	return ""
}

func (m *Plan) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Plan) GetOrders() []*order.Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type PlanData struct {
	Plan *Plan `protobuf:"bytes,1,opt,name=plan" json:"plan"`
}

func (m *PlanData) Reset()                    { *m = PlanData{} }
func (m *PlanData) String() string            { return proto.CompactTextString(m) }
func (*PlanData) ProtoMessage()               {}
func (*PlanData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PlanData) GetPlan() *Plan {
	if m != nil {
		return m.Plan
	}
	return nil
}

type PlanResponse struct {
	Status  string    `protobuf:"bytes,1,opt,name=status" json:"status"`
	Message string    `protobuf:"bytes,2,opt,name=message" json:"message"`
	Data    *PlanData `protobuf:"bytes,3,opt,name=data" json:"data"`
}

func (m *PlanResponse) Reset()                    { *m = PlanResponse{} }
func (m *PlanResponse) String() string            { return proto.CompactTextString(m) }
func (*PlanResponse) ProtoMessage()               {}
func (*PlanResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PlanResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PlanResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PlanResponse) GetData() *PlanData {
	if m != nil {
		return m.Data
	}
	return nil
}

type PlansPageResponse struct {
	Status  string     `protobuf:"bytes,1,opt,name=status" json:"status"`
	Message string     `protobuf:"bytes,2,opt,name=message" json:"message"`
	Data    *PlansPage `protobuf:"bytes,3,opt,name=data" json:"data"`
}

func (m *PlansPageResponse) Reset()                    { *m = PlansPageResponse{} }
func (m *PlansPageResponse) String() string            { return proto.CompactTextString(m) }
func (*PlansPageResponse) ProtoMessage()               {}
func (*PlansPageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PlansPageResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PlansPageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PlansPageResponse) GetData() *PlansPage {
	if m != nil {
		return m.Data
	}
	return nil
}

type PlansPage struct {
	Page     uint32  `protobuf:"varint,1,opt,name=page" json:"page"`
	PageSize uint32  `protobuf:"varint,2,opt,name=pageSize" json:"pageSize"`
	Total    uint32  `protobuf:"varint,3,opt,name=total" json:"total"`
	Plans    []*Plan `protobuf:"bytes,4,rep,name=plans" json:"plans"`
}

func (m *PlansPage) Reset()                    { *m = PlansPage{} }
func (m *PlansPage) String() string            { return proto.CompactTextString(m) }
func (*PlansPage) ProtoMessage()               {}
func (*PlansPage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PlansPage) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PlansPage) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PlansPage) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PlansPage) GetPlans() []*Plan {
	if m != nil {
		return m.Plans
	}
	return nil
}

func init() {
	proto.RegisterType((*NewPlanRequest)(nil), "plan.NewPlanRequest")
	proto.RegisterType((*UpdatePlanRequest)(nil), "plan.UpdatePlanRequest")
	proto.RegisterType((*GetUserPlanRequest)(nil), "plan.GetUserPlanRequest")
	proto.RegisterType((*GetUserPlansRequest)(nil), "plan.GetUserPlansRequest")
	proto.RegisterType((*DeletePlanRequest)(nil), "plan.DeletePlanRequest")
	proto.RegisterType((*Plan)(nil), "plan.Plan")
	proto.RegisterType((*PlanData)(nil), "plan.PlanData")
	proto.RegisterType((*PlanResponse)(nil), "plan.PlanResponse")
	proto.RegisterType((*PlansPageResponse)(nil), "plan.PlansPageResponse")
	proto.RegisterType((*PlansPage)(nil), "plan.PlansPage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PlanService service

type PlanServiceClient interface {
	NewPlan(ctx context.Context, in *NewPlanRequest, opts ...client.CallOption) (*PlanResponse, error)
	GetUserPlan(ctx context.Context, in *GetUserPlanRequest, opts ...client.CallOption) (*PlanResponse, error)
	GetUserPlans(ctx context.Context, in *GetUserPlansRequest, opts ...client.CallOption) (*PlansPageResponse, error)
	DeletePlan(ctx context.Context, in *DeletePlanRequest, opts ...client.CallOption) (*PlanResponse, error)
	UpdatePlan(ctx context.Context, in *UpdatePlanRequest, opts ...client.CallOption) (*PlanResponse, error)
}

type planServiceClient struct {
	c           client.Client
	serviceName string
}

func NewPlanServiceClient(serviceName string, c client.Client) PlanServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "plan"
	}
	return &planServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *planServiceClient) NewPlan(ctx context.Context, in *NewPlanRequest, opts ...client.CallOption) (*PlanResponse, error) {
	req := c.c.NewRequest(c.serviceName, "PlanService.NewPlan", in)
	out := new(PlanResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) GetUserPlan(ctx context.Context, in *GetUserPlanRequest, opts ...client.CallOption) (*PlanResponse, error) {
	req := c.c.NewRequest(c.serviceName, "PlanService.GetUserPlan", in)
	out := new(PlanResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) GetUserPlans(ctx context.Context, in *GetUserPlansRequest, opts ...client.CallOption) (*PlansPageResponse, error) {
	req := c.c.NewRequest(c.serviceName, "PlanService.GetUserPlans", in)
	out := new(PlansPageResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) DeletePlan(ctx context.Context, in *DeletePlanRequest, opts ...client.CallOption) (*PlanResponse, error) {
	req := c.c.NewRequest(c.serviceName, "PlanService.DeletePlan", in)
	out := new(PlanResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) UpdatePlan(ctx context.Context, in *UpdatePlanRequest, opts ...client.CallOption) (*PlanResponse, error) {
	req := c.c.NewRequest(c.serviceName, "PlanService.UpdatePlan", in)
	out := new(PlanResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PlanService service

type PlanServiceHandler interface {
	NewPlan(context.Context, *NewPlanRequest, *PlanResponse) error
	GetUserPlan(context.Context, *GetUserPlanRequest, *PlanResponse) error
	GetUserPlans(context.Context, *GetUserPlansRequest, *PlansPageResponse) error
	DeletePlan(context.Context, *DeletePlanRequest, *PlanResponse) error
	UpdatePlan(context.Context, *UpdatePlanRequest, *PlanResponse) error
}

func RegisterPlanServiceHandler(s server.Server, hdlr PlanServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&PlanService{hdlr}, opts...))
}

type PlanService struct {
	PlanServiceHandler
}

func (h *PlanService) NewPlan(ctx context.Context, in *NewPlanRequest, out *PlanResponse) error {
	return h.PlanServiceHandler.NewPlan(ctx, in, out)
}

func (h *PlanService) GetUserPlan(ctx context.Context, in *GetUserPlanRequest, out *PlanResponse) error {
	return h.PlanServiceHandler.GetUserPlan(ctx, in, out)
}

func (h *PlanService) GetUserPlans(ctx context.Context, in *GetUserPlansRequest, out *PlansPageResponse) error {
	return h.PlanServiceHandler.GetUserPlans(ctx, in, out)
}

func (h *PlanService) DeletePlan(ctx context.Context, in *DeletePlanRequest, out *PlanResponse) error {
	return h.PlanServiceHandler.DeletePlan(ctx, in, out)
}

func (h *PlanService) UpdatePlan(ctx context.Context, in *UpdatePlanRequest, out *PlanResponse) error {
	return h.PlanServiceHandler.UpdatePlan(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/asciiu/gomo/plan-service/proto/plan/plan.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 776 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0x89, 0x93, 0x26, 0x93, 0x4b, 0xc9, 0x36, 0x14, 0x13, 0x55, 0x55, 0x64, 0x10, 0x8a,
	0x90, 0x48, 0x50, 0x80, 0x07, 0x54, 0xf1, 0x42, 0x83, 0x50, 0x25, 0x94, 0x56, 0x2e, 0xfd, 0x80,
	0x8d, 0x33, 0x4a, 0x02, 0xbe, 0xe1, 0x5d, 0xf7, 0xc2, 0x23, 0x7f, 0xc4, 0x37, 0xf0, 0xce, 0x33,
	0xff, 0xc1, 0x0f, 0xa0, 0xdd, 0x75, 0x6c, 0xe7, 0xd6, 0x54, 0xea, 0x4b, 0xea, 0x99, 0xd9, 0x9d,
	0xd9, 0x33, 0x7b, 0xce, 0x6c, 0xe1, 0xdd, 0x64, 0xc6, 0xa7, 0xd1, 0xa8, 0x6b, 0xfb, 0x6e, 0x8f,
	0x32, 0x7b, 0x36, 0x8b, 0x7a, 0x13, 0xdf, 0xf5, 0x7b, 0x81, 0x43, 0xbd, 0x97, 0x0c, 0xc3, 0xcb,
	0x99, 0x8d, 0xbd, 0x20, 0xf4, 0xb9, 0x72, 0xc9, 0x9f, 0xae, 0xb4, 0x89, 0x2e, 0xbe, 0x5b, 0x47,
	0x77, 0x4f, 0xe0, 0x87, 0x63, 0x0c, 0xd5, 0xaf, 0x4a, 0x61, 0xfe, 0xd5, 0xa0, 0x3e, 0xc4, 0xab,
	0x33, 0x87, 0x7a, 0x16, 0x7e, 0x8f, 0x90, 0x71, 0xb2, 0x0f, 0xc5, 0x88, 0x61, 0x78, 0x32, 0x30,
	0xb4, 0xb6, 0xd6, 0x29, 0x5b, 0xb1, 0x45, 0x9a, 0x50, 0xe0, 0x33, 0xee, 0xa0, 0x91, 0x93, 0x6e,
	0x65, 0x90, 0xe7, 0x50, 0x17, 0x85, 0xbe, 0xa0, 0x1b, 0x38, 0x94, 0xe3, 0xc9, 0xc0, 0xc8, 0xcb,
	0xf0, 0x92, 0x57, 0x64, 0x65, 0x9c, 0xf2, 0x88, 0x19, 0xba, 0xca, 0xaa, 0x2c, 0xd2, 0x81, 0x5d,
	0xdb, 0xf1, 0x19, 0x9e, 0x7a, 0xc7, 0xbe, 0x1b, 0x38, 0xc8, 0xd1, 0x28, 0xb4, 0xb5, 0x4e, 0xc9,
	0x5a, 0x76, 0x93, 0x2e, 0x14, 0xe5, 0xc9, 0x99, 0x51, 0x6c, 0xe7, 0x3b, 0x95, 0xfe, 0x7e, 0x57,
	0x01, 0x19, 0xe2, 0xd5, 0xa9, 0xf8, 0x88, 0xcf, 0x6f, 0xc5, 0xab, 0xcc, 0x7f, 0x1a, 0x34, 0x2e,
	0x82, 0x31, 0xe5, 0xb8, 0x84, 0x4e, 0x9c, 0x2c, 0x45, 0xa7, 0xac, 0x0c, 0xea, 0xdc, 0x7a, 0xd4,
	0xf9, 0xdb, 0x51, 0xeb, 0x5b, 0x50, 0x17, 0xb6, 0xa1, 0x2e, 0x6e, 0x43, 0xbd, 0x73, 0x27, 0xd4,
	0x3f, 0x35, 0x20, 0x9f, 0x90, 0x5f, 0x30, 0x0c, 0xef, 0x03, 0xfb, 0x00, 0xca, 0x62, 0xc5, 0x00,
	0x03, 0x3e, 0x95, 0xd0, 0x6b, 0x56, 0xea, 0x20, 0x87, 0x00, 0xc2, 0xf8, 0x8c, 0xde, 0x84, 0x4f,
	0x25, 0xf4, 0x9a, 0x95, 0xf1, 0x98, 0xbf, 0x34, 0xd8, 0xcb, 0x1c, 0x82, 0x6d, 0xa3, 0x56, 0x0b,
	0x4a, 0x78, 0x6d, 0x4f, 0xa9, 0x37, 0x99, 0xb3, 0x2b, 0xb1, 0x45, 0x2d, 0x97, 0x86, 0xdf, 0x90,
	0x0f, 0xa9, 0x3b, 0xbf, 0x85, 0x8c, 0x67, 0x23, 0xb1, 0x08, 0xe8, 0x01, 0x9d, 0x28, 0x36, 0xd5,
	0x2c, 0xf9, 0x2d, 0xea, 0x88, 0xbf, 0xe7, 0xb3, 0x1f, 0xaa, 0xdf, 0x35, 0x2b, 0xb1, 0xcd, 0x63,
	0x68, 0x0c, 0x50, 0xb4, 0xfc, 0x1e, 0x6d, 0x33, 0xff, 0xe8, 0xa0, 0x8b, 0xfd, 0x1b, 0x37, 0xae,
	0x12, 0x27, 0xb7, 0x89, 0x38, 0x71, 0x81, 0xfc, 0x42, 0xa7, 0xde, 0xc0, 0x23, 0x87, 0x32, 0xfe,
	0xf1, 0x1a, 0xed, 0x88, 0xe3, 0xf8, 0x2c, 0xb9, 0xa3, 0x92, 0x84, 0xb3, 0x3e, 0x48, 0x5e, 0xc1,
	0x5e, 0x36, 0x20, 0x89, 0x73, 0x32, 0x30, 0xca, 0x32, 0xf5, 0xba, 0xd0, 0xc2, 0x8d, 0xc0, 0xad,
	0x37, 0x52, 0x59, 0xb9, 0x91, 0x3e, 0x34, 0xa9, 0xcd, 0x67, 0x97, 0x78, 0x1c, 0x85, 0x21, 0x7a,
	0xf6, 0xcd, 0xf9, 0x8d, 0x3b, 0xf2, 0x1d, 0xa3, 0x2a, 0x57, 0xae, 0x8d, 0x09, 0x5c, 0x8b, 0xfe,
	0x0f, 0xd4, 0xa1, 0x9e, 0x8d, 0x46, 0xad, 0xad, 0x75, 0x34, 0x6b, 0x7d, 0x50, 0x74, 0x33, 0x8a,
	0x39, 0x36, 0x8c, 0xdc, 0x11, 0x86, 0x46, 0xbd, 0xad, 0x75, 0x74, 0x6b, 0xc9, 0x9b, 0xe1, 0xc8,
	0xee, 0x36, 0x19, 0x3e, 0x5c, 0x2f, 0xc3, 0x03, 0x28, 0xdb, 0x21, 0x52, 0xd1, 0x21, 0xcf, 0x68,
	0xc8, 0x24, 0xa9, 0x43, 0x44, 0x23, 0x39, 0x69, 0x44, 0x94, 0xa8, 0x68, 0xe2, 0x48, 0x47, 0xc8,
	0x5e, 0x76, 0x84, 0x3c, 0x4b, 0x84, 0xdd, 0x94, 0xc2, 0xae, 0xc6, 0xc2, 0x56, 0xaa, 0x9e, 0xcb,
	0xf9, 0x05, 0x94, 0xe4, 0x35, 0x52, 0x4e, 0xc9, 0x21, 0xc8, 0x81, 0x2f, 0x19, 0x55, 0xe9, 0x43,
	0x57, 0xbe, 0x04, 0x92, 0xad, 0xd2, 0x6f, 0x8e, 0xa1, 0xaa, 0xb8, 0xcb, 0x02, 0xdf, 0x63, 0x59,
	0x65, 0x68, 0x0b, 0xa8, 0x0d, 0xd8, 0x71, 0x91, 0x31, 0x9a, 0x88, 0x6d, 0x6e, 0x12, 0x13, 0xf4,
	0x31, 0xe5, 0x54, 0x72, 0xae, 0xd2, 0xaf, 0xa7, 0x15, 0x44, 0x7d, 0x4b, 0xc6, 0xcc, 0xaf, 0xd0,
	0x90, 0x9a, 0x3e, 0xa3, 0x13, 0xbc, 0x47, 0xa9, 0xa7, 0x0b, 0xa5, 0x76, 0xd3, 0x52, 0x2a, 0xb1,
	0xaa, 0xc5, 0xa0, 0x9c, 0xb8, 0x12, 0x41, 0x6b, 0x1b, 0x04, 0x9d, 0x5b, 0x14, 0xb4, 0x6c, 0xbb,
	0xcf, 0xa9, 0x13, 0x8f, 0x2f, 0x65, 0x90, 0x36, 0x14, 0x44, 0x29, 0x31, 0x2d, 0xf2, 0x4b, 0x5d,
	0x54, 0x81, 0xfe, 0xef, 0x1c, 0x54, 0x84, 0x7d, 0xae, 0x9e, 0x4e, 0xf2, 0x16, 0x76, 0xe2, 0x17,
	0x92, 0x34, 0xd5, 0xea, 0xc5, 0x07, 0xb3, 0x45, 0x32, 0x39, 0xe2, 0x86, 0x98, 0x0f, 0xc8, 0x7b,
	0xa8, 0x64, 0x46, 0x20, 0x31, 0xd4, 0xa2, 0xd5, 0xd1, 0xbc, 0x61, 0xfb, 0x00, 0xaa, 0xd9, 0x09,
	0x4a, 0x9e, 0xac, 0xec, 0x9f, 0x4f, 0xd5, 0xd6, 0xe3, 0xe5, 0xe6, 0xa5, 0x59, 0x8e, 0x00, 0xd2,
	0xa1, 0x46, 0xe2, 0x85, 0x2b, 0x63, 0x6e, 0xc3, 0x11, 0x8e, 0x00, 0xd2, 0xf7, 0x73, 0xbe, 0x79,
	0xe5, 0x45, 0x5d, 0xbf, 0x79, 0x54, 0x94, 0xff, 0x5f, 0xbc, 0xfe, 0x1f, 0x00, 0x00, 0xff, 0xff,
	0x16, 0xb6, 0x33, 0x07, 0xdf, 0x08, 0x00, 0x00,
}
