// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/events/events.proto

/*
Package common_events is a generated protocol buffer package.

It is generated from these files:
	proto/events/events.proto

It has these top-level messages:
	TradeEvent
	Auth
	OrderEvent
*/
package common_events

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Events
type TradeEvent struct {
	Exchange   string  `protobuf:"bytes,1,opt,name=exchange" json:"exchange,omitempty"`
	Type       string  `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	EventTime  string  `protobuf:"bytes,3,opt,name=eventTime" json:"eventTime,omitempty"`
	MarketName string  `protobuf:"bytes,4,opt,name=marketName" json:"marketName,omitempty"`
	TradeID    string  `protobuf:"bytes,5,opt,name=tradeID" json:"tradeID,omitempty"`
	Price      float64 `protobuf:"fixed64,6,opt,name=price" json:"price,omitempty"`
	Quantity   float64 `protobuf:"fixed64,7,opt,name=quantity" json:"quantity,omitempty"`
	Total      float64 `protobuf:"fixed64,8,opt,name=total" json:"total,omitempty"`
}

func (m *TradeEvent) Reset()                    { *m = TradeEvent{} }
func (m *TradeEvent) String() string            { return proto.CompactTextString(m) }
func (*TradeEvent) ProtoMessage()               {}
func (*TradeEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TradeEvent) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *TradeEvent) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TradeEvent) GetEventTime() string {
	if m != nil {
		return m.EventTime
	}
	return ""
}

func (m *TradeEvent) GetMarketName() string {
	if m != nil {
		return m.MarketName
	}
	return ""
}

func (m *TradeEvent) GetTradeID() string {
	if m != nil {
		return m.TradeID
	}
	return ""
}

func (m *TradeEvent) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *TradeEvent) GetQuantity() float64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *TradeEvent) GetTotal() float64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Auth struct {
	Key    string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Secret string `protobuf:"bytes,2,opt,name=secret" json:"secret,omitempty"`
}

func (m *Auth) Reset()                    { *m = Auth{} }
func (m *Auth) String() string            { return proto.CompactTextString(m) }
func (*Auth) ProtoMessage()               {}
func (*Auth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Auth) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Auth) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type OrderEvent struct {
	Exchange              string  `protobuf:"bytes,1,opt,name=exchange" json:"exchange,omitempty"`
	OrderID               string  `protobuf:"bytes,2,opt,name=orderID" json:"orderID,omitempty"`
	UserID                string  `protobuf:"bytes,3,opt,name=userID" json:"userID,omitempty"`
	KeyID                 string  `protobuf:"bytes,4,opt,name=keyID" json:"keyID,omitempty"`
	MarketName            string  `protobuf:"bytes,5,opt,name=marketName" json:"marketName,omitempty"`
	Side                  string  `protobuf:"bytes,6,opt,name=side" json:"side,omitempty"`
	OrderType             string  `protobuf:"bytes,7,opt,name=orderType" json:"orderType,omitempty"`
	BaseQuantity          float64 `protobuf:"fixed64,8,opt,name=baseQuantity" json:"baseQuantity,omitempty"`
	BaseQuantityRemainder float64 `protobuf:"fixed64,9,opt,name=baseQuantityRemainder" json:"baseQuantityRemainder,omitempty"`
	Condition             string  `protobuf:"bytes,10,opt,name=condition" json:"condition,omitempty"`
	Conditions            string  `protobuf:"bytes,11,opt,name=conditions" json:"conditions,omitempty"`
	ExchangeOrderID       string  `protobuf:"bytes,12,opt,name=exchangeOrderID" json:"exchangeOrderID,omitempty"`
	ExchangeMarketName    string  `protobuf:"bytes,13,opt,name=exchangeMarketName" json:"exchangeMarketName,omitempty"`
	Status                string  `protobuf:"bytes,14,opt,name=status" json:"status,omitempty"`
}

func (m *OrderEvent) Reset()                    { *m = OrderEvent{} }
func (m *OrderEvent) String() string            { return proto.CompactTextString(m) }
func (*OrderEvent) ProtoMessage()               {}
func (*OrderEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *OrderEvent) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *OrderEvent) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *OrderEvent) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *OrderEvent) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *OrderEvent) GetMarketName() string {
	if m != nil {
		return m.MarketName
	}
	return ""
}

func (m *OrderEvent) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *OrderEvent) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func (m *OrderEvent) GetBaseQuantity() float64 {
	if m != nil {
		return m.BaseQuantity
	}
	return 0
}

func (m *OrderEvent) GetBaseQuantityRemainder() float64 {
	if m != nil {
		return m.BaseQuantityRemainder
	}
	return 0
}

func (m *OrderEvent) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

func (m *OrderEvent) GetConditions() string {
	if m != nil {
		return m.Conditions
	}
	return ""
}

func (m *OrderEvent) GetExchangeOrderID() string {
	if m != nil {
		return m.ExchangeOrderID
	}
	return ""
}

func (m *OrderEvent) GetExchangeMarketName() string {
	if m != nil {
		return m.ExchangeMarketName
	}
	return ""
}

func (m *OrderEvent) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*TradeEvent)(nil), "common.events.TradeEvent")
	proto.RegisterType((*Auth)(nil), "common.events.Auth")
	proto.RegisterType((*OrderEvent)(nil), "common.events.OrderEvent")
}

func init() { proto.RegisterFile("proto/events/events.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xd1, 0x6e, 0xda, 0x30,
	0x14, 0x86, 0x95, 0x11, 0x08, 0x39, 0x83, 0x6d, 0x3a, 0xda, 0x26, 0x6f, 0x9a, 0x26, 0x94, 0x2b,
	0xae, 0xd8, 0xa4, 0xed, 0x05, 0x26, 0xb1, 0x0b, 0x2e, 0x36, 0xd4, 0x88, 0x17, 0x30, 0xc9, 0x51,
	0x89, 0x68, 0x62, 0xea, 0x38, 0x55, 0xf3, 0x8e, 0x7d, 0x84, 0x3e, 0x4c, 0xe5, 0x63, 0x27, 0x50,
	0x8a, 0xd4, 0xab, 0xf8, 0xff, 0xff, 0x63, 0x1f, 0x9f, 0xcf, 0x81, 0x2f, 0x07, 0xad, 0x8c, 0xfa,
	0x41, 0x77, 0x54, 0x99, 0xda, 0x7f, 0x16, 0xec, 0xe1, 0x34, 0x53, 0x65, 0xa9, 0xaa, 0x85, 0x33,
	0x93, 0xc7, 0x00, 0x60, 0xa3, 0x65, 0x4e, 0x7f, 0xad, 0xc6, 0xaf, 0x30, 0xa6, 0xfb, 0x6c, 0x27,
	0xab, 0x6b, 0x12, 0xc1, 0x2c, 0x98, 0xc7, 0x69, 0xaf, 0x11, 0x21, 0x34, 0xed, 0x81, 0xc4, 0x1b,
	0xf6, 0x79, 0x8d, 0xdf, 0x20, 0xe6, 0x83, 0x36, 0x45, 0x49, 0x62, 0xc0, 0xc1, 0xd1, 0xc0, 0xef,
	0x00, 0xa5, 0xd4, 0x7b, 0x32, 0xff, 0x65, 0x49, 0x22, 0xe4, 0xf8, 0xc4, 0x41, 0x01, 0x91, 0xb1,
	0xbd, 0x57, 0x4b, 0x31, 0xe4, 0xb0, 0x93, 0xf8, 0x11, 0x86, 0x07, 0x5d, 0x64, 0x24, 0x46, 0xb3,
	0x60, 0x1e, 0xa4, 0x4e, 0xd8, 0xdb, 0xdd, 0x36, 0xb2, 0x32, 0x85, 0x69, 0x45, 0xc4, 0x41, 0xaf,
	0xed, 0x0e, 0xa3, 0x8c, 0xbc, 0x11, 0x63, 0xb7, 0x83, 0x45, 0xf2, 0x13, 0xc2, 0x3f, 0x8d, 0xd9,
	0xe1, 0x07, 0x18, 0xec, 0xa9, 0xf5, 0x23, 0xd9, 0x25, 0x7e, 0x86, 0x51, 0x4d, 0x99, 0x26, 0xe3,
	0xe7, 0xf1, 0x2a, 0x79, 0x18, 0x00, 0xac, 0x75, 0x4e, 0xfa, 0x75, 0x20, 0x02, 0x22, 0x65, 0x2b,
	0x57, 0x4b, 0x7f, 0x46, 0x27, 0xed, 0xe1, 0x4d, 0xcd, 0x81, 0x63, 0xe2, 0x95, 0xbd, 0xe4, 0x9e,
	0xda, 0xd5, 0xd2, 0xb3, 0x70, 0xe2, 0x0c, 0xd3, 0xf0, 0x05, 0x26, 0x84, 0xb0, 0x2e, 0x72, 0xc7,
	0x22, 0x4e, 0x79, 0x6d, 0xc1, 0x73, 0xb3, 0x8d, 0x7d, 0x91, 0xc8, 0x81, 0xef, 0x0d, 0x4c, 0x60,
	0xb2, 0x95, 0x35, 0x5d, 0x75, 0xb0, 0x1c, 0x93, 0x67, 0x1e, 0xfe, 0x86, 0x4f, 0xa7, 0x3a, 0xa5,
	0x52, 0x16, 0x55, 0x4e, 0x5a, 0xc4, 0x5c, 0x7c, 0x39, 0xb4, 0x7d, 0x33, 0x55, 0xe5, 0x85, 0x29,
	0x54, 0x25, 0xc0, 0xf5, 0xed, 0x0d, 0x3b, 0x49, 0x2f, 0x6a, 0xf1, 0xd6, 0x4d, 0x72, 0x74, 0x70,
	0x0e, 0xef, 0x3b, 0x7a, 0x6b, 0x4f, 0x6e, 0xc2, 0x45, 0xe7, 0x36, 0x2e, 0x00, 0x3b, 0xeb, 0xdf,
	0x91, 0xcd, 0x94, 0x8b, 0x2f, 0x24, 0xfc, 0x9c, 0x46, 0x9a, 0xa6, 0x16, 0xef, 0xfc, 0x73, 0xb2,
	0xda, 0x8e, 0xf8, 0xaf, 0xff, 0xf5, 0x14, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x60, 0xa8, 0xf1, 0x12,
	0x03, 0x00, 0x00,
}
